### ISSUE TITLE
Unhandled EBADF in zsock_resolve

### ISSUE THREAD

**Issue by pulltab** [zeromq/czmq#1011]
I have detected what I believe to be a bug when creating / destroying czmq router sockets.

Here is a minimalistic example which exposes the issue:

````
#include <assert.h>
#include <czmq.h>

int main(int argc, const char** argv){

    // Happy path open/close
    zctx_t* context = NULL;
    zsock_t* router = NULL;

    context = zctx_new();
    assert(context);

    router = zsock_new(ZMQ_ROUTER);
    assert(!errno); //This fails as errno is EINVAL
    assert(router); 

    zsock_destroy(&router);
    zctx_destroy(&context);

    return 0;
}
```

As detailed in comment above, the assert(errno) fails as errno is set to EINVAL after invoking zsock_new.  Note, the variable router is pointing to a value which is not nulI.  I, along with a colleague, traced the issue to https://github.com/zeromq/czmq/blob/master/src/zsock.c#L1528 where an un-handled EBADF seems to be the root cause of the issue.  This was confirmed by adding an assert to the line indicated above.

**Comment by pulltab** [comment]
I should also mention that I have recreated this on both master as well as the 3.0.0 release.

**Comment by hintjens** [comment]
(a) You do not use errno as a return code. It will hold arbitrary values. The only valid return code is that described in the man page for any given function. (b) CZMQ 3.x does not use zctx any more. Here is a correct minimal test case:

#include <czmq.h>

    int main (void)
    {
        zsock_t *router = NULL;
        router = zsock_new(ZMQ_ROUTER);
        assert (router); 
        zsock_destroy(&router);
        return 0;
    }
