### ISSUE TITLE
Compiling czmq vs2013

### ISSUE THREAD

**Issue by pasternake** [zeromq/czmq#1020]
In "Pre-Built event" option of project need to change Command Line to (add d quotes) to prevent error if roots using spaces

copy "$(BuildRoot)platform.h" "$(RepoRoot)include\"

**Comment by hintjens** [comment]
This file is generated by zproject; do you want to send a patch to that
project?

**Comment by pasternake** [comment]
I'm new on ZeroMQ. But want to do patch. Have I start with https://github.com/zeromq/zproject ?

**Comment by hintjens** [comment]
Yes, start with zproject, read our contribution process at
http://rfc.zeromq.org/spec:22, and check the various MSVC scripts in
zproject.

**Comment by pasternake** [comment]
Hello!
By now done with gls and zproject. Fixed zproject_vs2013.gsl file. Some issues with 2008... Tested with default project.xml (myproject). Are there project.xml files for czmq, libzmq and libsodium for continue testing. Sorry, but didn't find them in rep's.

**Comment by sappo** [comment]
Hi @pasternake zproject targets c projects that use the CLASS coding style (http://rfc.zeromq.org/spec:21). Those are for example czmq and zyre. libzmq is written in c++ and libsodium doesn't use CLASS. 

As far as the project.xml is concerned you'll find those in the respective project root directories.

**Comment by hintjens** [comment]
CZMQ uses zproject, the others do not.

**Comment by hintjens** [comment]
Vs20xx is now working, closing this issue.
