### ISSUE TITLE
LICENSE and other files missing in release tarball czmq-3.0.1.tar.gz

### ISSUE THREAD

**Issue by vyskocilm** [zeromq/czmq#1021]
czmq master does have following files in the root: AUTHORS CONTRIBUTING.md INSTALL LICENSE NEWS README.md README.txt, where the release tarball http://download.zeromq.org/czmq-3.0.1.tar.gz does have only AUTHORS and NEWS. Especially missing LICENSE file is a big problem for downstream distributions.

**Comment by hintjens** [comment]
Thanks for catching this. I'll fix it and make a new release tarball
immediately.

Note however that every source file has the license in its header.

**Comment by hintjens** [comment]
OK, done.
