### ISSUE TITLE
ZMQ doesn't work with the raw socket in Linux but works in Windows

### ISSUE THREAD

**Issue by henrywoo** [zeromq/czmq#1024]
I have a client program written with raw socket communicating with a server. It uses 'select' to poll the socket descriptor and get the message from the server. After getting message, I use a ZMQ socket to send the message out.

This works perfectly in windows. But in Linux, after I call the ZMQ 'send' function, I cannot receive message from the server any more. It seems the raw socket has been affected somehow.

The program is a multithread program but I have dealt with ZMQ carefully. The client program is running in a thread A and the ZMQ socket is only used by that thread A. I think I used ZMQ correctly as it is working well in Windows. But how comes the issue in Linux?

Anybody knows if this is normal? I am suspecting this is a ZMQ issue. As long as I remove the ZMQ 'send' function, the program works well. Anybody knows how to solve this issue? and why it is working well in Windows, not in Linux?

**Comment by hintjens** [comment]
Please don't cross-post issues to multiple projects.

**Comment by jemc** [comment]
For reference: https://github.com/zeromq/libzmq/issues/1438
