### ISSUE TITLE
Problem: zhash_autofree implies the value must be a string, but the documentation does not mention this

### ISSUE THREAD

**Issue by mitchellwrosen** [zeromq/czmq#1032]
A zhash container appears to be able to store arbitrarily typed values (`void*`) indexed by a string key (`char*`). However, if `autofree` is set, there are a couple places in `zhash.c` that cast the value to a `char*` and then `strdup` it. This will surely cause problems if the value was not a `char*` to begin with.

Solution: Update documentation? Maybe don't strdup the value?

**Comment by jemc** [comment]
Of your two suggestions, I would suggest updating the documentation.  We already have `zhashx` that is better suited to more complex use cases like these.

**Comment by mitchellwrosen** [comment]
That's fine, thanks for the suggestion. I just checked out `zhashx` and the documentation says "zhashx is an extended hash table container with more functionality than zhash, its simpler cousin." How vague is that?? How is someone supposed to know when exactly to use it over `zhash`? :(

**Comment by hintjens** [comment]
Good point. zhashx is mainly aimed at storing objects, since it has hooks
for destruction, copying, sorting. It also lets you navigate in both
directions...
