### ISSUE TITLE
/usr/bin/makecert conflicts with mono-devel

### ISSUE THREAD

**Issue by vyskocilm** [zeromq/czmq#1038]
Hi,

this issue has been found by Arch Linux [1] and Fedora [2]

[1] https://aur.archlinux.org/packages/czmq/
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1196484

and appered in my submission to openSUSE as well. Thus you can't have installed czmq and mono-devel at the same time. As mono uses the name since 2003, I recommend to rename the czmq's tool instead to canonical name shared by all the distros.

**Comment by gwerbin** [comment]
Would it be possible to tag a release with this fix in it? Would be nice for fixing the conflict in Homebrew.

**Comment by bluca** [comment]
We have many things left to do before that, including a libzmq release. API will be broken so we cannot just release it, sorry, it will take some time.

**Comment by gwerbin** [comment]
@bluca would it be possible to make this change on top of the last stable release and release it and just bump the version? If you don't want to do that, I can look into at least updating the Homebrew formula to rename `makecert` to `zmakecert`.

**Comment by bluca** [comment]
@gwerbin - our policy (as described in the C4 process) is not to branch. I would have to revert many changes to make master again API/ABI compatible with 3.0.2. I can look into it, but no promises, as I expect it would get pretty messy.

If it's possible for you to have a workaround in the formula, I would ask to please go ahead with it. We have a few things to go through before we can release zmq 4.2 and czmq 4.0, and we are all volunteers so time is what it is :-) But we are almost there!

**Comment by gwerbin** [comment]
OK. Is there any reason I can't just `mv makecert zmakecert` for this change?

**Comment by bluca** [comment]
That should be fine

**Comment by gwerbin** [comment]
I tried to incorporate this into the Homebrew formula for CZMQ and it ended up producing a strange error on build. Do you guys have any ideas? Do I need to patch the self-tester function?

https://github.com/Homebrew/homebrew-core/pull/5958#discussion_r87709953

**Comment by bluca** [comment]
Note that we have done a release now, so 4.0.0 has the rename

**Comment by gwerbin** [comment]
Great, so that change is unnecessary if I just bump the CZMQ version in Homebrew?

**Comment by bluca** [comment]
Yes.
Please read the release notes, as 4.0 introduced ABI and API breakages.
