### ISSUE TITLE
problems with "make check" over RPI 2

### ISSUE THREAD

**Issue by massimovassalli** [zeromq/czmq#1057]
Hi,
I have some problems while installing czmq on RPI v2. When checking the compilation (make check) the procedure hangs after zgossip_msg (that is OK) and the only way to go further is to block the check. I'm using czmq-3.0.2 in a Raspberry PI 2 with zeromq-4.1.2 and exactly the same configuration worked for Raspberry PI 1 B+. 
How to manage this issue ?
Thanks,
Massimo

**Comment by jemc** [comment]
@massimovassalli - If possible, it would be most helpful if you could get a gdb session running and print backtraces for all threads.

To do this:

- Install `gdb` via your package manager and be sure `which gdb` shows it exists on your machine in your `$PATH`.
- Run `make debug` instead of `make check` - this will load the test binary into a `gdb` session.
- In the `gdb` prompt, type the `run` command to run the tests.
- When the tests hang, hit Ctrl+C to interrupt the program and get a `gdb` prompt again.
- Type `thread apply all bt` to get backtraces for all threads and paste the result so we can see where they hang (you may need to press "enter" a few times to get through all of the backtraces.

**Comment by massimovassalli** [comment]
Dear @jemc , thanks for your answer.

I tried your steps. When running make debug and than run, I got no error and the script completed. After quitting the gdb environment I decided to re-try make check and ... I got the following error:

lt-czmq_selftest: src/zsys.c:1636: zsys_test: Assertion `!zsys_file_stable ("./.testsys/subdir")' failed.
 * zsys: Makefile:1934: recipe for target 'check-local' failed
make[2]: *** [check-local] Aborted
make[2]: Leaving directory '/home/pi/czmq-3.0.2'
Makefile:1778: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/pi/czmq-3.0.2'
Makefile:1369: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

have you any suggestion ?
Thanks a lot,
Massimo

**Comment by jemc** [comment]
It looks like a poor test, honestly.  The test is creating a file, doing a few other things, then calling `zsys_file_stable` to see if the file is more or less than one second old, asserting that it is less.  So on slower platforms, you have the potential to see this issue pop up where it takes more than a second to get to the assertion, causing test failure.  I'd recommend trying to move the `assert (!zsys_file_stable ("./.testsys/subdir"));` line to right beneath the `rc = zsys_dir_create ("%s/%s", ".", ".testsys/subdir");` line and see if that helps.

**Comment by massimovassalli** [comment]
Dear Joe,
I tried moving the suggested line, but the output did not change. I thus
cleaned everything, regenerated scripts and configured them, compiled and
checked, but nothing changed. I'm also wondering 1. why it does not hang
any more and 2. why is the installation on the slower Raspberry1 going
better ?

Being a very fair C programmer, I decided to give a start back. I cloned
the latest czmq and I went through all steps so that ... everything
magically worked :-) Sorry for being not very helpful and thanks once more
for the support.

Massimo

On 7 August 2015 at 17:20, Joe Eli McIlvain <notifications@github.com>
wrote:

> It looks like a poor test, honestly. The test is creating a file, doing a
> few other things, then calling zsys_file_stable to see if the file is
> more or less than one second old, asserting that it is less. So on slower
> platforms, you have the potential to see this issue pop up where it takes
> more than a second to get to the assertion, causing test failure. I'd
> recommend trying to move the assert (!zsys_file_stable
> ("./.testsys/subdir")); line to right beneath the rc = zsys_dir_create
> ("%s/%s", ".", ".testsys/subdir"); line and see if that helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zeromq/czmq/issues/1057#issuecomment-128730892>.
>



-- 
Dr Massimo Vassalli
Institute of Biophysics
National Research Council
Genova - Italy
T: +39 010 6475 571

**Comment by jemc** [comment]
I'm not sure what to tell you other than that the latest master may have fixed some other bug that caused the 3.0.2 revision you had to hang.

**Comment by bluca** [comment]
Closing since it was reported as fixed on a later version.
