### ISSUE TITLE
Problem: zrex fails to match

### ISSUE THREAD

**Issue by sappo** [zeromq/czmq#1065]
Hi, I just stumbled upon the following regex with must match but doesn't:

```
zrex_t *rex = zrex_new ("[a-z]+\\d+");
zrex_matches (rex, "abc123");
```

It seems like a bug in our slre version. The newest version of slre doesn't have this bug, but slre has changed the license to GPL. Does that prevent us from upgrading?

**Comment by hintjens** [comment]
Hmm... We cannot include GPL code. Either we fix or we replace. Pity, slre
was small and usable.

**Comment by Asmod4n** [comment]
https://github.com/laurikari/tre looksquite good, and is 2-clause BSD.
Fixing a bug here would mean maintining a fork, or?

**Comment by sappo** [comment]
The newest version of srle seems like a complete rewrite, so finding that bug might be an complicated undertaking.

**Comment by hintjens** [comment]
I already forked and cleaned up the code,  iirc it had already got lost in
v2 silliness. It's hard to find a minimal regexp library. Needs to be a
single source, ideally.

**Comment by hintjens** [comment]
There are two options I know. PCRE is one standard. Another option is TRE: https://github.com/laurikari/tre

The main issue is support for exotic platforms (Windows) where one cannot depend on external packages. In the past this has meant re-packaging the library and wrapping its build scripts. I've done this for PCRE in the past (in OpenAMQ and we could re-use that work quite easily).

See https://github.com/imatix/openamq/tree/master/tooling/foreign/pcre

**Comment by sappo** [comment]
My search for a single file regex implementations that is maintained and has a proper license sadly returned empty handed. 

Regarding the two options, PCRE is obviously the veteran in this area and is already installed on a lot of linux and bsd systems. Further if packaging can be easily done I would prefer PCRE over TRE.

**Comment by Asmod4n** [comment]
By looking at zproject, it already has a way to build shared libraries which will then be linked dynamically, right?
Shouldn't it then be adoptable to statically link a library?
