### ISSUE TITLE
FreeBSD 10.2 compatibility

### ISSUE THREAD

**Issue by crypto750** [zeromq/czmq#1068]
I am compiling code making use of libzmq/czmq on FreeBSD 10.2.
libzmq/czmq were compiled from recent github source.
Compilation fails with an error message. The code compiles ok on Linux though.
Is this a FreeBSD libzmq/czmq specific platform issue or application code error?

```
[ 79%] Building CXX object src/ipc/CMakeFiles/client_ipc.dir/wap_proto.c.o
CC: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
/root/bitmonero/src/ipc/wap_proto.c:2547:5: error: no matching function for call to 'zlist_append'
zlist_append (blocks_block_ids, "Name: Brutus");
^~~~~~~~~~~~
/usr/local/include/zlist.h:72:5: note: candidate function not viable: no known conversion from 'const char [13]' to 'void ' for 2nd argument
zlist_append (zlist_t *self, void *item);
^
/root/bitmonero/src/ipc/wap_proto.c:2548:5: error: no matching function for call to 'zlist_append'
zlist_append (blocks_block_ids, "Age: 43");
^~~~~~~~~~~~
/usr/local/include/zlist.h:72:5: note: candidate function not viable: no known conversion from 'const char [8]' to 'void *' for 2nd argument
zlist_append (zlist_t *self, void *item);
^
2 errors generated.
** Error code 1
```

Source code of the app:

https://github.com/monero-project/bitmonero/blob/development/src/ipc/wap_proto.c#L2547

**Comment by jemc** [comment]
It's not a problem with CZMQ, but a problem with your application (`/root/bitmonero/src/ipc/wap_proto.c`) and/or your compiler flags (the defaults of which in this case are determined by FreeBSD and Debian).  Debian's default compiler flags were allowing you to pass `char *` arguments to a `void *` parameter, but FreeBSD's default flags are not allowing this.

You should use an explicit casts to `void *` here:
```c
zlist_append (blocks_block_ids, (void *) "Name: Brutus");
```
```c
zlist_append (blocks_block_ids, (void *) "Age: 43");
```
