### ISSUE TITLE
Problem: ./generate.sh fails with fatal error

### ISSUE THREAD

**Issue by sappo** [zeromq/czmq#1072]
The error occurs the second time ./generate.sh is executed. To reproduce this error do the following:
```
git clone https://github.com/zeromq/czmq.git
cd czmq
./generate.sh    # Everything works fine
./generate.sh    # Fatal error (see below)
```
To following error is thrown:
```
Fatal error in application - aborted
Abort.  Compile with SMT_DETECT for more info.
Aborted (core dumped)
```
This might be a bug in gsl but I'm not sure.

**Comment by hintjens** [comment]
Yes, an issue in GSL (SMT is an ancient inproc messaging system we used in
previous centuries)

**Comment by sappo** [comment]
OK, I'll create an issue over there.
