### ISSUE TITLE
Problem: Does zdispatcher belong in czmq?

### ISSUE THREAD

**Issue by sappo** [zeromq/czmq#1076]
This is regarding my pull request #1075.

@hintjens already voiced concerns that a dispatcher perhaps belongs in a broker. I'm divided on this topic, so I'd like to get some input :)

Here are the pros and cons IMO:

Pro:
* easily forward messages to handlers based on URIs or URNs 
* easily extract parameters from URIs or URNs while dispatching
* easy to include as it is part of czmq

Con:
* no reaping for disappeared handlers (may be the breaking point)
* no responses (though this has been by design)

Fixing the cons will probably make a it a fully blown broker?!

**Comment by hintjens** [comment]
My experience in general has been, build classes in other projects and then
bring them to CZMQ when they're stable and reusable.

My naive assumption is this is part (half) of a request-reply protocol that
belongs in a broker.

Can you explain more about the problem you're solving with this?

**Comment by sappo** [comment]
Your naive assumption is correct. 

I'm writing a HTTP to XRAP gateway and somehow I got lost with the dispatcher as the other half which is sending the responses back to a dedicated server socket didn't quiet work. But after a thorough view at malamute I think I'll experiment with zproto clients and servers as that seems very promising. 

Thus in violation of the contributers guideline ("czmq is not a playground") I'll revert this pull request.
