### ISSUE TITLE
Problem: czmq doesn't have any CI test for windows

### ISSUE THREAD

**Issue by sappo** [zeromq/czmq#1094]
Hence Travis CI doesn't support windows we cannot test directly on a windows host, but we can cross compile the code.

@pijyoi Do you still have a running build using MXE to cross compile for mingw. All my efforts failed so far :(

**Comment by pijyoi** [comment]
I just tried it out with a fresh build of MXE. mingw32 got dropped, have to
use MinGW-w64.

compile zeromq-4.1.2
====================
./configure --host=i686-w64-mingw32.static --prefix=$HOME/mingw32
--without-libsodium
make
make install

compile czmq master
===================
export PKG_CONFIG_PATH_i686_w64_mingw32_static=$HOME/mingw32/lib/pkgconfig
CFLAGS="-DLIBCZMQ_EXPORTS -D__USE_MINGW_ANSI_STDIO" ./configure
--host=i686-w64-mingw32.static --prefix=$HOME/mingw32
sed -i.bak s/-pedantic// Makefile
make
make install

notes
=====
make clean fails
make[1]: zproject_mkman: Command not found


# removal of -pedantic to fix the following
src/zsock.c: In function 'zsock_vsend':
src/zsock.c:677:32: error: ISO C does not support the 'I64' ms_printf
length modifier [-Werror=format=]
             zmsg_addstrf (msg, "%" PRIu64, va_arg (argptr, uint64_t));

# define __USE_MINGW_ANSI_STDIO to fix the following
trie.c: In function 's_ztrie_print_tree_line':
src/ztrie.c:614:21: error: unknown conversion type character 'z' in format
[-Werror=format=]
             printf ("%s (params: %zu, endpoint: %s, type: %d)\n",
self->token,
                     ^
src/ztrie.c:614:21: error: format '%s' expects argument of type 'char *',
but argument 3 has type 'size_t {aka unsigned int}' [-Werror=format=]
src/ztrie.c:614:21: error: format '%d' expects argument of type 'int', but
argument 4 has type 'char *' [-Werror=format=]
src/ztrie.c:614:21: error: too many arguments for format
[-Werror=format-extra-args]

**Comment by sappo** [comment]
Thanks, do you know which packages you'd installed for MXE. A complete build would probably unsuitable for a test run ;)

zproject_mkman is installed by zproject so the failing clean is not that bad.

The new "-Werror=format=" causes the ISO C errors as window/mingw is not ISO C, so it's okay to disable it.

**Comment by pijyoi** [comment]
Only "make gcc". Nothing else.

**Comment by twhittock** [comment]
This is good now, right
