### ISSUE TITLE
zmsg_send/zmsg_recv can't recover from EINTR

### ISSUE THREAD

**Issue by maxkozlovsky** [zeromq/czmq#1098]
zmsg_send()/zmsg_recv() can't recover from being interrupted in the middle of sending.

zmsg_send() will leak a frame if zframe_send() is interrupted (or fails with any other error) since it pops the frame of the list first before sending. zframe_send() will destroy a frame when successful and leave the frame untouched if fails. zmsg_send() should push back the frame on the list in case of an error to allow the caller to send the rest of the message after handling the interrupt.

zmsg_recv() will destroy a partially received message if interrupted in a middle of receive, causing the message to be permanently lost. Addressing this problem probably requires an api change to return an error and partially received message to allow the caller to complete the receive after handling the interrupt. An alternative is to retry receiving the frame on EINTR if already received some frames.

**Comment by hintjens** [comment]
Losing data on interrupt is fine IMO, unless you can explain a case where
it should recover. The whole CZMQ API and higher use "empty returned
message" as a signal for "process interrupted" so it goes far deeper than
an API change.

**Comment by maxkozlovsky** [comment]
Hi,

I've tried to run my application that uses czmq under profiler (which uses
timer interrupts) and it caused all kinds of failures with messages being
lost or partially delivered. Using a profiler should not cause a data loss.
The user of the API should be able to recover from EINTR failures.

For example, similar function unix sendmsg() will return EINTR only when no
data was sent. From manpage:

[EINTR]            A signal interrupts the system call before any data is
transmitted.

Max

**Comment by Asmod4n** [comment]
regarding ```zmsg_send```, a change to use zlist_first/next should resolve the issue, no? Would only require a small change to the ZFRAME_MORE logic.

**Comment by maxkozlovsky** [comment]
Pushing the frame back on error will probably be a smaller change compared
to the current code. Using zlist_first() will require saving the frame size
before calling zframe_send() to be able to adjust the message size after
send, or not using zframe_send() at all and calling zmq_sendmsg() directly.

**Comment by hintjens** [comment]
Surely it's simpler just to disable EINTR using zsys_handler_set(). The
code should not be changed to run under a profiler IMO.

**Comment by maxkozlovsky** [comment]
Not sure how zsys_handler_set() will help. As I understand
zsys_handler_set() only affects the behavior on SIGINT and SIGTERM. It does
not change what happens when other signals are received and caught by the
application and/or system libraries.

If there is a way to prevent zmq to return EINTR altogether that should
work as workaround.

**Comment by hintjens** [comment]
Hmm... the profiler isn't sending signals?

This is a topic we've hit before with libzmq though I don't remember the
outcome.

**Comment by maxkozlovsky** [comment]
The profiler is starting the timer and handling the signals. Each thread
has its own timer so each thread receives its own signal every tick. I was
using google perftools https://github.com/gperftools/gperftools, though
gprof has the same behavior.

**Comment by hintjens** [comment]
Assume you cannot change the API (nor would it make sense to expose this to
the caller). You can change the way the code handles EINTR to retry, and
try to make this work under the profiler. We can then see how to generalize
that. I'll refine my statement about "not changing the code to be smart
about profilers" to "not changing applications". Doing this inside CZMQ is
fine IMO.

**Comment by maxkozlovsky** [comment]
I made the change to retry on EINTR internally and it fixed the problems
for me. It probably would be better to follow sendmsg/recvmsg error
handling policy and still return EINTR if the send or receive of the first
frame in multipart message fails. I can try to modify the code below to do
that and resend if you agree this would be the right approach.

diff --git a/src/zmsg.c b/src/zmsg.c

index 99dee8a..60b334d 100644

--- a/src/zmsg.c

+++ b/src/zmsg.c

@@ -104,6 +104,8 @@ zmsg_recv (void *source)

     while (true) {

         zframe_t *frame = zframe_recv (handle);

         if (!frame) {

+            if (errno == EINTR)

+                continue;

             zmsg_destroy (&self);

             break;              //  Interrupted or terminated

         }

@@ -139,8 +141,12 @@ zmsg_send (zmsg_t **self_p, void *dest)

         while (frame) {

             rc = zframe_send (&frame, handle,

                               zlist_size (self->frames) ? ZFRAME_MORE : 0);

-            if (rc != 0)

-                break;

+            if (rc != 0) {

+                if (errno == EINTR)

+                    continue;

+                else

+                    break;

+            }

             frame = (zframe_t *) zlist_pop (self->frames);

         }

         if (rc == 0)

**Comment by hintjens** [comment]
These changes look fine. Would you send a pull request?

**Comment by maxkozlovsky** [comment]
Ok I'll do that.

**Comment by maxkozlovsky** [comment]
commit afacb649
