### ISSUE TITLE
zdir self-tests fail: Assertion failed: (subdir), function s_posix_populate_entry

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1107]
I plan to write a nice Ruby binding for CZMQ based on the official, generated, low-level FFI bindings (https://github.com/paddor/cztop). Since up until recently there had been some syntax errors in those, I'm trying to use the most recent version of CZMQ. Unfortunately, when I try to install it, the self-tests fail with the following error:

```
Assertion failed: (subdir), function s_posix_populate_entry, file src/zdir.c, line 93.
Running czmq selftests...
 * zactor: OK
 * zauth: OK
 * zarmour: OK
 * zbeacon: OK
 * zcert: OK
 * zcertstore: OK
 * zchunk: OK
 * zclock: OK
 * zconfig: OK
 * zdigest: OK
 * zdir: make[2]: *** [check-local] Abort trap: 6
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

See https://gist.github.com/paddor/4a64778ae3b77f54bc3a for the complete output of ZMQ and CZMQ installation.

Additional info: I'm running OSX 10.10.5, but got the same error on 10.11 first. I tried with the most recent stable release of ZMQ but also with its HEAD version. Same outcome. My Xcode is up-to-date (7.0) and its command line tools are installed, of course. `brew doctor` reports no issues.

**Comment by sappo** [comment]
Hi @paddor, there's not much to go on. The zdir test failed to create a subdirectory, do you have sufficient access writes to create directories when you run `make check`?

**Comment by paddor** [comment]
Well, honestly I have no idea where Homebrew creates the build directory and runs all these commands. I just ran the commands in a manually checked out repository of CZMQ and `make check` reported no errors. I guess that means there's something wrong with the Homebrew formula. But what I noticed is that `configure` reports `configure: WARNING: unrecognized options: --with-libsodium`. Checking `./configure --help`, I really can't see that option. Has it recently been removed or something?

**Comment by paddor** [comment]
Sorry, I just checked the formula. Seems like `--with-libsodium` will get passed through to ZMQ itself.

**Comment by sappo** [comment]
I sadly cannot provide any help regarding homebrew.

The `--with-libsodium` flag is a relic as sodium had to be linked manually. Currently it is linked automatically if found and you'll have the option to exclude it via `--without-libsodium`.

**Comment by paddor** [comment]
Thanks for the help. I'll open an issue over at Homebrew.
