### ISSUE TITLE
Problem: zpoller does not work with ZMQ_CLIENT sockets

### ISSUE THREAD

**Issue by taotetek** [zeromq/czmq#1123]
Versions: libzmq and czmq head as of 2015-10-17

Test case:

``` c
#include <czmq.h>                                                                                         

void                                                                                                      
main ()                                                                                                   
{                                                                                                         
    zsock_t *client = zsock_new_client ("tcp://127.0.0.1:9999");                                          
    assert (client);                                                                                      

    zsock_t *server = zsock_new_server ("tcp://127.0.0.1:9999");                                          
    assert (server);                                                                                      

    zpoller_t *poller = zpoller_new (server, NULL);                                                       
    assert (poller);                                                                                      

    zstr_send (client, "Hello, World");                                                                   

    zsock_t *which = (zsock_t *) zpoller_wait (poller, -1);                                               
    assert (which == server);                                                                             
    char *message = zstr_recv (which);                                                                    
    assert (streq (message, "Hello, World"));                                                             
    zstr_free (&message);                                                                                 

    zpoller_destroy (&poller);                                                                            
    zsock_destroy (&client);                                                                              
    zsock_destroy (&server);                                                                              
}
```

Output:

```
poller_test: poller_test.c:18: main: Assertion `which == server' failed.
Aborted (core dumped)
```

**Comment by taotetek** [comment]
Potentially relevant libzmq issue:

https://github.com/zeromq/libzmq/pull/1535

**Comment by taotetek** [comment]
So reading through this I'm assuming the issue is zpoller is using zmq_poll, and we need to be using zmq_pollfd_poll instead ( https://github.com/somdoron/libzmq/blob/4da5ff6a7d12ffcca8041cd35a9dfe1bb475b9a7/include/zmq.h#L422 ) in czmq.

Not immediately sure of the best way to handle this without breaking backwards compat while not getting too messy is.  Is it time to deprecate zpoller and start a new version?

**Comment by somdoron** [comment]
I think the best way to handle this is actually porting zpoller to zmq, and use that when compiling with current version and fallback to current implementation when older version.

There is another reason to do it, every binding is  usually implementing something like zpoller, have it once implemented in zmq (and support both server &client sockets) will make everything much easier.

**Comment by taotetek** [comment]
@somdoron allowing simpler bindings on top of a better zpoller api in zmq makes sense to me.  I'm being over-eager because the thread safety of CLIENT / SERVER is immensely useful in some problems I have ;)

**Comment by hintjens** [comment]
So time to start porting some of the CZMQ classes into libzmq?

**Comment by somdoron** [comment]
I guess so :-) I have some time next week, I can can try and port it.

@hintjens is it possible to make zloop based on zpoller?

**Comment by Asmod4n** [comment]
Would love to have a zloop api where you can throw in everything, zsocks, zactors, libzmq sockets and normal sockets/FD :)

**Comment by hintjens** [comment]
Not sure about layering zloop on zpoller... I don't think so.

We could add zmq_sock_is () to identify sockets, and we can maybe cheat to
detect sockets/FDs.

**Comment by somdoron** [comment]
Following PR port the zpoller to libzmq (with small changes to the API to make it more like zmq API):
https://github.com/zeromq/libzmq/pull/1611

The plan is that zpoller will call zmq_poller (when using libzmq v4.2).

**Comment by somdoron** [comment]
I think we can close this, as zpoller should (which mean tested) work with CLIENT and SERVER sockets.
