### ISSUE TITLE
czmq does not use libsodium

### ISSUE THREAD

**Issue by madebr** [zeromq/czmq#1133]
I could not find a reference to `sodium.h` in any c source or header file.

- CMake does not have any reference
- Only some build scripts and the visual studio projects so have references

Is it safe to say that these references are outdated and can be removed?

**Comment by Asmod4n** [comment]
libzmq uses libsodium for CURVE security, which czmq builds upon.

**Comment by madebr** [comment]
Thanks. Good to know. The dependency was not clear to me.
