### ISSUE TITLE
problem: saving routing id on the socket violate SERVER thread safety

### ISSUE THREAD

**Issue by somdoron** [zeromq/czmq#1144]
The following violate the thread safety of SERVER sockets, if two threads try to receive a message they will both override the routing_id.

https://github.com/zeromq/czmq/blob/master/src/zsock.c#L48

Suggested solution: can we use TLS (thread local storage) to save the routing id?

**Comment by somdoron** [comment]
Actually at the moment this is not used at all

**Comment by hintjens** [comment]
It's OK since CZMQ zsock_t instances are not threadsafe.

**Comment by somdoron** [comment]
so if I want to use the SERVER from multiple threads (multiple workers with broker, for example) it is not yet possible using zsock_t?

**Comment by hintjens** [comment]
Right, none of the CZMQ classes are threadsafe. Period.

**Comment by somdoron** [comment]
Or if I want thread safety I should use zframe_t?

**Comment by hintjens** [comment]
Yes, zframe or zmsg will work.
