### ISSUE TITLE
usage of Zpoller in python binding

### ISSUE THREAD

**Issue by maccradar** [zeromq/czmq#1147]
I am trying to use the Zpoller class from the python binding together 
with the zyre binding. Following minimal example fails for me:

 >>> from czmq import Zpoller
 >>> from zyre import Zyre
 >>> node = Zyre("test")
 >>> node.start()
0
 >>> poller = Zpoller(node.socket(), None)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/home/jphilips/workspace/czmq/bindings/python/czmq.py", line 
1782, in __init__
     self._as_parameter_ = lib.zpoller_new(args[0], *args[index()-1:]) # 
Creation of new raw type
NameError: global name 'index' is not defined
 >>>

There seems to be something strange going on in this zpoller_new call. 
Shouldn't it be *args[-1:], i.e. without the index()?

Or how does one use this Zpoller, because I am confused at the moment ...

**Comment by twhittock** [comment]
There is a bug in the binding which does not escape the index call in the
caustic case. I'll take a look tonight gmt, unless someone else gets to it
first.

**Comment by twhittock** [comment]
Variadic, not caustic. Autocorrect.

**Comment by twhittock** [comment]
#1148 should resolve this

**Comment by jemc** [comment]
Thanks, @twhittock.

**Comment by maccradar** [comment]
if it should be variadic why the assert(len(args) == 2) on czmq.py:1781 ?
