### ISSUE TITLE
Zpoller python binding calls a variadic function zpoller_new but asserts on argument list of 2

### ISSUE THREAD

**Issue by maccradar** [zeromq/czmq#1149]
continuing on #1147 and #1148, why does Zpoller is implemented to be variadic but asserts on the length of arguments?

czmq.py lines 1781-1782
```python
assert(len(args) == 2)
self._as_parameter_ = lib.zpoller_new(args[0], *args[1:]) # Creation of new raw type
```

args[1:] is always only one element long...

**Comment by jemc** [comment]
Fix to zproject was https://github.com/zeromq/zproject/pull/273
