### ISSUE TITLE
Inconsistency between documentation and API: zsock_new_server/zsock_new_client

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1154]
According to the documentation on http://api.zeromq.org/czmq3-0:zsock, there's no such functions as `zsock_new_server` and `zsock_new_client`. But according to the API (https://github.com/zeromq/czmq/blob/master/api/zsock.xml#L97), the actual source, and the README.md there are. I guess that means the documentation is lacking those.

What are SERVER and CLIENT sockets anyway?

**Comment by hintjens** [comment]
The online docs are somewhat behind.

Client and server sockets are documented in http://rfc.zeromq.org/spec:41
and the libzmq zmq_socket man page.

**Comment by paddor** [comment]
Oh, I see. Thank you for the info.
