### ISSUE TITLE
zsock_option functions as stand-alone API class or embedded within zsock class?

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1164]
I'm improving the generated Ruby bindings of CZMQ. I've noticed that the zsock_option functions ([documentation](http://api.zeromq.org/czmq3-0:zsock-option)) don't have a corresponding XML API file. So I created a GSL file which does that, as the class `zsock_option` (at least for the major ZMQ version 4). See [comparison](https://github.com/zeromq/czmq/compare/master...paddor:better_ruby_bindings?expand=1).

However, I've hit a problem. Those functions aren't prefixed with the expected class name `zsock_option_`, but `zsock_` instead.

I hesitated adding these functions to the existing `zsock` class XML API, because those functions are documented to
> [...] take a void * "polymorphic" reference, which can be either a zsock_t or a zactor_t reference, or a libzmq void *.

I could just add them to the existing `zsock` class XML API. To set any options on a zactor_t object using a binding later, one would have to create an instance of the Zsock class with a given zactor_t pointer or something.

I thought it'd nicer to have these functions grouped in a ZsockOption class which can be used for any of the three supported reference types, either by exposing them all as singleton methods. To do this, the `<class>` tag in the XML API files would have to support a new attribute, like `function_prefix = "zsock_"`. A nicer approach would be generating a Ruby module which can be mixed into the Zsock and Zactor classes (although this would require additional information from the API file).

Maybe the Zactor functionality doesn't make a lot of sense in a high-level binding anyway, so one could ignore that requirement, which makes the integration directly into the `zsock` class sound even better.

Which approach sounds better to you? Any other ideas?

**Comment by paddor** [comment]
Huh, I've just seen that some of the instance methods defined in the API for zsock have an attribute `polymorphic = "1"`. I guess this means that the polymorphic zsock_option functions can and should be added there.

**Comment by jemc** [comment]
The `polymorphic` option was recently added, and as far as I know, only implemented in the python bindings so far, as it was the motivation to support it was from users/authors of those bindings.  The ruby bindings (and others) would have to be updated to support `polymorphic`.

In python, this is easier, since all instance methods can also be called as singleton/class methods with an explicit `self` object passed in as the receiver instance.

My first thought about the best way to support `polymorphic` in ruby is to imitate the python behavior:
1. Define a singleton method where the first argument is the polymorphic receiver object (the explicit "self") - `def self.function_name(receiver, arg1, arg2)`.
2. Define an instance method as usual, where `self` is the implicit receiver - `def function_name(arg1, arg2) end`

This way, the user can choose to call it on the intended class, or with any other object as the receiver.  If the object `respond_to?(:__ptr)`, then we use the pointer in the FFI call, otherwise we trust the user is sending a valid FFI pointer object or equivalent (like `nil` to functions where a `NULL` pointer is a valid, safe call).

**Comment by sappo** [comment]
@paddor the class zsock_option violates the CLASS style guide by intention and zproject only aims to be compliant to CLASS. Hence must not fix this issue there.

Further always go for the simplest possible solution. Which in this case is to define the zsock_option methods within the api/zsock.xml. As Zsock already polymorphic I don't see why we cannot combine them into one class. The difficulty is that zsock_option is generated. For the source part we could rename the generate file to zsock_option.inc and include it within zsock. This approach is used by zproto (e.g.used by zgossip). The header part is a bit trickier as it is generated by zproject. One solution that pops into my head is to generate the api/zsock_option.xml and teach zproject to read methods from another xml file. This is already done for the license file.

**Comment by jemc** [comment]
@sappo's idea about how/where to generate the API XML for socket options is a good one.  We are already generating the C code for the socket options using a CZMQ-specific GSL script, so we would want to generate the API XML as well using this same script into a `api/zsock_option.inc` file, then somehow reference/include that file from `api/zsock.xml`.

**Comment by paddor** [comment]
@jemc @sappo Thanks for your answers. I agree, the simplest solution would be to integrate the methods directly into the `zsock` API XML. It also makes sense to provide a class and an instance version for polymorphic methods.

I like the include approach, just like with the license. Working on it...

**Comment by paddor** [comment]
Sorry, but does that `<include filename="some file" />` work at all? I can't get it to work because it's probably name clashing with the `.include` command of GSL. I changed it to `<pull filename="some file" />`, added the `XML.load_file(...)` and `copy` code to `zproject_class_api.gsl` (from zproject) and also fixed the paths of the included ("pulled") licenses in all the XML API files. The path has to be given relative to where the `gsl` command is started, not relative to the pulling file.

The question is: What to do with the other handful of XML files in src/ which use the `<include />` tag?

As I'm writing this, I see that `zproject.gsl` from zproject actually has a `resolve_includes()` function which at least resolves the includes in the `project.xml` file, using actual `<include>` tags. It also uses the function `project.load_file(filename)`, which I can't find in the GSL documentation. Can someone tell me what's going on? I'm confused.

Thanks.

**Comment by paddor** [comment]
Oh, `project` is an XML item, and the `XML.load_file()` can be called directly on it. Polymorphism all over the place...

The rest still doesn't sense.

**Comment by paddor** [comment]
It all seems to work now. Creating pull requests ...

**Comment by paddor** [comment]
@jemc 
>This way, the user can choose to easily call it on the intended class (`ZSock#function_name`), or with any other object as the receiver (in a call to `ZSock.function_name`).  If the given receiver object `respond_to?(:__ptr)`, then we use the pointer in the FFI call, otherwise we trust the user is sending a valid FFI pointer object or equivalent (like `nil` to functions where a `NULL` pointer is a valid, safe call).

I almost forgot about this. I agree that testing for the existence of #__ptr is a good idea and use it, if available. Also the trusting part, if the user wants to provide any other kind of object. But `nil`? Sounds strange to me. But okay, we can't know for all possible C functions in advance if it makes sense or not.

Just committed it in paddor/zproject@36f9b0a1f566f9da0948147878f07506df346179

**Comment by hintjens** [comment]
@paddor I've cleaned this up somewhat. Take a look, it's possible I broke something.
