### ISSUE TITLE
problem: czmq-jni does not expose accessor methods for ZList

### ISSUE THREAD

**Issue by awynne** [zeromq/czmq#1181]
I was expecting to see all the zlist accessors (http://czmq.zeromq.org/manual:zlist) in ZList.java (https://github.com/zeromq/czmq/blob/master/bindings/czmq-jni/src/main/java/org/zeromq/czmq/ZList.java)

**Comment by awynne** [comment]
this problem is in the generated binding as well

**Comment by hintjens** [comment]
OK, working on it.

**Comment by hintjens** [comment]
So all the accessor methods are there, except those which use callbacks (sort, comparefn, freefn). 

Zlist works with and returns CZMQ object references (long): to get the reference for any object, use Object.self. And to turn 'reference' into an object, use new Class (reference).

**Comment by awynne** [comment]
So I think you are saying that if I have a Zlist containing String objects, then I could convert a Zlist to a java List like so:

	private List<String> toStringList(Zlist zlist) {
		ArrayList<String> jlist = new ArrayList<>();
		
		long ptr = zlist.first();
		while (ptr > 0) {
			Zstr zstr = new Zstr(ptr);
			jlist.add(zstr.toString());
			ptr = zlist.next();
		}
		
		return jlist;
	}

However, there is no Zstr(String) constructor.  Is this an omission or do I misunderstand?

**Comment by hintjens** [comment]
Well, you could do this with e.g a list of zframes, using "new Zframe
(ptr)"... zstr is a static class, there are no zstr instances.

**Comment by hintjens** [comment]
Fixed with zstr_str ().
