### ISSUE TITLE
Problem: CZMQ codebase is filled with useless OOM checks

### ISSUE THREAD

**Issue by hintjens** [zeromq/czmq#1193]
This code was added at a point, to make CZMQ continue safely if a process ran out of memory.

It makes the codebase more complex in practically every method. 

Actually testing out-of-memory conditions shows that these checks do not work: libzmq and other libraries randomly die when the heap is exhausted.

I'd like to replace all these checks with asserts. Poorly-sized memory limits are not a recoverable problem IMO.

Solution: rip out OOM error handling and replace with asserts.

**Comment by Asmod4n** [comment]
The problem with asserts is, they can be turned off. So in some cases you have to check for NULL or do something else like abort(); maybe.

**Comment by hintjens** [comment]
I don't think we ever turn off the asserts in libzmq or CZMQ. Anyone doing
that in production code gets what they deserve...

**Comment by Asmod4n** [comment]
Debian does this with release packages by default I believe, they are turned on for debug packages. I could beer wrong tho.

**Comment by bluca** [comment]
I can confirm in Debian both libzmq and CZMQ are built with the default options, so asserts are in. And rightly so :-)

https://anonscm.debian.org/cgit/collab-maint/czmq.git/tree/debian/rules
https://anonscm.debian.org/cgit/collab-maint/zeromq3.git/tree/debian/rules

**Comment by Asmod4n** [comment]
yay :)
