### ISSUE TITLE
Problem: in jni binding, there is no task to publish artifacts locally

### ISSUE THREAD

**Issue by awynne** [zeromq/czmq#1204]
Solution: add the following configuration block to build.gradle (something like this should be done for all projects that have jni bindings, actually)

```
publishing {
    publications {
        jniJar(MavenPublication) {
            artifacts {
                artifact "build/libs/${project.name}-${version}.jar"
            }
        }
    }   
}
```

**Comment by c-rack** [comment]
Thanks, could you send a pull request please?

**Comment by hintjens** [comment]
I'll do this (has to go into zproject).

**Comment by c-rack** [comment]
A warning header in `gradle.build` would help others to find the right direction. I have opened https://github.com/zeromq/zproject/pull/349 to fix this.

**Comment by c-rack** [comment]
@awynne Fixed by https://github.com/zeromq/czmq/commit/89059fb50f5952a7c1da049f840d3c3262a19edb

**Comment by hintjens** [comment]
@awynne I've added that rule and it seems to break things. I've no experience with gradle, to fix this. Could you make it work by hand, and then I'll backport those fixes into zproject. We can adopt this approach for any similar changes (don't be put off by the warning header, just if someone regenerates the project, the changes will be lost).

**Comment by awynne** [comment]
submitted a handwritten fix via a pull request.  @hintjens pls backport as you suggested.

**Comment by hintjens** [comment]
Thanks!
