### ISSUE TITLE
czmq does not support ipv6

### ISSUE THREAD

**Issue by syenna** [zeromq/czmq#1236]
Add support for ipv6
- ipv6 mode can be chosen by setting the environment variable (ZSYS_IPV6=1). Set ZSYS_IPV6_ADDRESS and ZSYS_MCAST_ADDRESS for zbeacon to chose the right address and multi-cast address.
- ipv4 mode should work with no changes to existing applications

**Comment by syenna** [comment]
Submitted a pull request #1237 for this issue.

**Comment by syenna** [comment]
Pull request is merged on to the master branch.

**Comment by c-rack** [comment]
@syenna You may already know this, but it is possible to auto-close an issue via commit message:
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by syenna** [comment]
I did not know about that. Thanks!

**Comment by hintjens** [comment]
@syenna, nice work, and thanks for the patches.
