### ISSUE TITLE
zcert_save() doesn't fail with empty string as filename

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1244]
During testing of cztop, I realized that zcert_save() doesn't fail when given the empty string as filename. It just creates one file (insted of two): "_secret".

Shouldn't this return an error code?

**Comment by c-rack** [comment]
Good catch. It should either return an error code or `assert(*filename != '\0')` at the beginning:
https://github.com/zeromq/czmq/blob/master/src/zcert.c#L276-L290

**Comment by c-rack** [comment]
Or we just check the return code of the `zcert_save_public` call and return it if not equal to zero:
https://github.com/zeromq/czmq/blob/master/src/zcert.c#L283

I have not tried it, but I'd guess that trying to save a file with empty filename will fail.

**Comment by paddor** [comment]
Okay. I'll try.

**Comment by paddor** [comment]
Yes, zconfig_save() does return -1 if filename is empty.

**Comment by c-rack** [comment]
Closed by #1245
