### ISSUE TITLE
zcert_set_meta() cannot unset a key

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1246]
AFAICS, giving a NULL format as value doesn't work and thus, there is no way to unset metadata. See https://github.com/zeromq/czmq/blob/master/src/zcert.c#L171-L180.

**Comment by c-rack** [comment]
Adding a dedicated `void zcert_unset_meta (zcert_t *self, const char *name)` which just calls `zhash_delete (self->metadata, name)` might be better than adding this functionality to `zcert_set_meta`. Just my 2 cents...

**Comment by paddor** [comment]
Sure, makes no difference to me. I'll come up with a patch...

**Comment by c-rack** [comment]
Great, @hintjens and I have the finger on the trigger :-)

**Comment by c-rack** [comment]
Thanks!

Regarding b66016fb509ae8af5a53588f67f23a15704359ea, assert'ing also the name and the format wouldn't harm, too.

**Comment by paddor** [comment]
You're welcome. :)
