### ISSUE TITLE
Ruby binding: fresh strings from zstr_recv() or zstr_str() are autoreleased with free() instead of zstr_free()

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1251]
I have a solution, but it's kind of ugly. I made zproject define a .free() class method on every Ruby Zclass unless there is already a free() singleton method. The fallback implementation would just call LibC.free, like it already does.

The ugly part is that this .free() class method is only used for fresh strings, so the name is very misleading. Renaming it is not possible because zstr_free() dictates that name.

What to do?

**Comment by paddor** [comment]
Now I have a solution that doesn't define a new .free() method on every Ruby Zclass, it'll just use LibC.free if the class doesn't provide a _free() singleton method.

But it's still kinda ugly, I think. For this solution to work, I have to pass the API class instance through ruby_resolve_method() to ruby_resolve_container() to be able to check if the class has a _free() singleton method.

Any ideas?

**Comment by jemc** [comment]
It's not actually necessary to use `zstr_free`, especially in a language binding.

The `zstr_free` function is there to help C programmers write code that makes it easier not to shoot themselves in the foot.  It's constructed in such a way as to nullify the caller's reference, so that the caller won't accidentally hold a pointer to freed (inaccessible) memory - it will instead hold a NULL pointer, which is easy to detect and ignore/assert.

So, there's no reason the Ruby bindings need to use `zstr_free` for anything, quite honestly.  References are handled in a different way and the same idiom doesn't really apply.

**Comment by hintjens** [comment]
The other difference between zstr_free() and free() is that if libczmq is a DLL, then they happen in different heaps. Windows does not like it if you allocate memory inside a DLL and then free it in the caller's memory space. We deal properly with all objects, calling _destroy. However CZMQ returns fresh strings in various places, which need some CZMQ API to free them.

**Comment by paddor** [comment]
Oh great. Then I'll just leave it as it is. And thanks for the explanation. :-)

**Comment by paddor** [comment]
Oh, so it's not great. But there's no zstr_destroy method. Would zstr_free() make it work on Windows?

**Comment by jemc** [comment]
@paddor - As far as I know, there are no *instances* of `zstr` - the methods are all `singleton` methods.  Thus there is nothing to create or destroy.  The `zstr` "class" is simply a collection of convenience functions, not a proper "class" in the sense that it can create/destroy instances.

**Comment by paddor** [comment]
That is true. But zstr_recv() and zstr_str() still return fresh strings.

**Comment by jemc** [comment]
@paddor - Yes, but they return `string`, not `zstr`, and `string` is primitive type known to the bindings, independent of `zstr` or any other class.  The `fresh` strings returned should be treated like `fresh` strings returned from any other method, and freed with `free`.

**Comment by hintjens** [comment]
There are various methods in various classes that return fresh strings... I
didn't name it zstr_destroy because that would suggest there was a zstr
object.

**Comment by paddor** [comment]
So even on Windows, one can call free() to free those kinds of strings, and not zstr_free()?

**Comment by jemc** [comment]
Ah, sorry - I can't speak for windows - no idea about that wacky platform anymore.

But the strings returned by the `zstr` method are no different from any other fresh string, so the windows way of freeing a fresh string will apply "across the board", not just for `zstr` methods.

**Comment by paddor** [comment]
Haha, same here. I couldn't care less. But I think CZMQ does care about Windows.

What about the different heaps that @hintjens mentioned?

**Comment by jemc** [comment]
Looking at the `zstr_free` implementation, [it just calls `free`](https://github.com/zeromq/czmq/blob/1101ecd3c3b9b10ce043babebe8acce90eb2202e/src/zstr.c#L245)...

I don't see any IFDEFs for windows there, so `free` work on windows too *shrug*.

**Comment by hintjens** [comment]
It's free () but in a different memory space (that of the DLL). A DLL is shared between multiple applications. If you malloc in a DLL you must free in the same DLL...

**Comment by paddor** [comment]
I'll create a PR on zproject with my solution, then ...

**Comment by paddor** [comment]
Well, the problem only exists because the Ruby binding wraps fresh strings in FFI::AutoPointer. I guess I could just monkey patch the two affected methods in the czmq-ffi-gen gem. This way, zproject can stay the same and we still get correctly autofreed strings, even from zstr.

**Comment by jemc** [comment]
> [...] we still get correctly autofreed strings, even from zstr

There's *no difference* between fresh strings returned from `zstr` and those returned from any other function or method.  So the solution should not make a distinction between them, if that's what you're suggesting...

**Comment by paddor** [comment]
I get that. But according to what @hintjens says, zstr_free() has to be used anyway, to keep Windows happy. Right? Maybe I'm missing something, I don't know too much about shared/dynamic libraries/DLLs.

**Comment by jemc** [comment]
@paddor Have you observed/reproduced a problem with zproject fresh strings on windows?  Pursuing a solution to a problem that doesn't directly affect you and you can't reproduce on your platform is a recipe for bad solutions.

I'd suggest that solving any windows related issues in the Ruby bindings should be driven by a developer who uses windows and wants to use the Ruby bindings, who can at least reproduce/test the problem.  Even better, that developer may have experience dealing with such issues in the past, and bring an elegant idiomatic approach.  None of the three of us in this thread use windows, so we're not the best candidates for an elegant solution.

**Comment by paddor** [comment]
Okay, agreed. Sorry. :sweat_smile:
