### ISSUE TITLE
Zpoller can't poll for writing

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1257]
Would it be feasible to add support for polling for writing in zpoll?

To be able to port celluloid-zmq (see celluloid/celluloid-zmq#56) from ffi-rzmq to cztop, it'll need to poll for for writing. And I want to do this without using the zmq_poll interface directly in cztop.

`git log src/zpoller.c` tells me that zpoller originally was intended to be a solution to the 80% usecase. I think this feature would make it 95% (still no support for file handles).

**Comment by hintjens** [comment]
You could add a zpoller_add_writer () method, and see if that works for you (with no other API changes; you'll get back the socket ref if it's ready for writing). Though I'd also suggest using zloop, which does 100%.

**Comment by Asmod4n** [comment]
Celluloid-zmq cannot use zloop, it's doing the polling etc in ruby.
It would be useable if zloop would offer a run_once method.

**Comment by somdoron** [comment]
actually if you can compile with source both czmq and zeromq you can add the writer ability pretty easily, because zpoller in master is using zmq_poller from zeromq and zmq_poller support polling on out.

You might need a new zmq_poller method to check if the socket already register and then call modify instead of add, something like

ZMQ_EXPORT int zmq_poller_is_registered (void* poller, void *socket);
ZMQ_EXPORT int zmq_poller_events (void* poller, void *socket);

and maybe the same for FD. Anyway it should be pretty simple.

Take a look at the following:

https://github.com/zeromq/libzmq/blob/master/include/zmq.h#L439
https://github.com/zeromq/czmq/blob/master/src/zpoller.c#L86

Let me know if you want to go that way, I can help.

**Comment by somdoron** [comment]
Ok, because zpoll_wait doesn't return the event you might also need 2 new methods on zpoller:

int zpoller_is_in (zpoller_t* self);
int zpoller_is_out (zpoller_t* self);

**Comment by hintjens** [comment]
In most cases you don't need the event as you're either waiting to read or
write, not both.

**Comment by paddor** [comment]
Thanks for the info. I'll come up with a solution.

Just one question: What's the big [#ifdef ZMQ_HAVE_POLLER](https://github.com/zeromq/czmq/blob/master/src/zpoller.c#L25-L210) for? It kind of splits the whole file in two.

**Comment by somdoron** [comment]
So zmq_poller is a new thing in zeromq master, so the zpoller is split into two implementations, one (complicated) based on zmq_poll and the new one (inside the ZMQ_HAVE_POLLER ifdef) which is using zmq_poller (much simpler). zmq_poller has support to the ZMQ_POLL_OUT event

**Comment by paddor** [comment]
Thanks for the info. I'm coming up with a solution.

I think I'll

* add `add_writer()`
* rename `add()` to `add_reader()`
* provide a macro so `add()` still works
* add `zlist* readers_ready()`
* add `zlist* writers_ready()`

to both implementations.

Does that sound sane?

**Comment by paddor** [comment]
Looks like `zmq::socket_poller_t::wait` returns after finding the first event, which means I won't be able to build a list of readable/writable sockets.

Is the normal style to just repeatedly call `wait()` repeatedly to get the affected sockets back one by one, even if the multiple sockets might become readable/writable during the first call to `wait()`?

I see that the Ruby code in celluloid-zmq iterates through the list of readable and writable sockets in each reactor tick. But maybe that isn't actually necessary. Any ideas?

**Comment by somdoron** [comment]
zpoller design is not to provide a list, so you should iterate through calling the zpoller_wait. I would keep it that way. 

Also I don't think changing add to add_reader is a good idea, as you are changing the API of the library, MACRO will only solve it for static linking, not dynamic linking and bindings.

so this is what I would do:

* Add add_writer
* If you really need it (as Pieter mention, you usually don't register for both reader and writer) add zpoller_is_out and zpoller_is_in which will be relevant to the last received socket.

I think it will be simpler to implement and would not change the API for zpoller.

**Comment by hintjens** [comment]
Please don't make the simple api more complex. The main point of zpoller
was to hide the reader/writer choice as this is irrelevant to most users.
Also do you really need those lists? Do you poll on reading and writing at
the same time? And if you do, why not use zloop instead of expanding
zpoller...?

Keep it minimal...

**Comment by paddor** [comment]
Thanks for the feedback. Of course I wouldn't poll for reading and writing on the same socket at the same time, but for multiple sockets (some for reading, some for writing) as needed in Celluloid. Can't really use zloop because it needs to be tick-wise, like run_once() instead of run().

Never mind. I'll come up with a solution based on zmq_poll() directly.

**Comment by somdoron** [comment]
So just call zpoller_wait with zero timeout until you get NULL. That is the
way to iterate over ready sockets.

**Comment by paddor** [comment]
Zpoller can only poll for reading.

**Comment by paddor** [comment]
Or did you mean after adding zpoller_add_writer(), like @hintjens suggested? I guess that could work...

**Comment by hintjens** [comment]
Yes, just that method, nothing else. This discipline of making minimal
changes is important... Otherwise the API simplicity breaks down over time.
Compare zloop and zpoller and you see the difference.
