### ISSUE TITLE
Zbeacon hangs when one beacon disappears

### ISSUE THREAD

**Issue by gregkmoff** [zeromq/czmq#1260]
I have the following configuration:
- a set of VM nodes on a 172.16.0.0/12 subnet
- each node running a beacon
- VM nodes interconnected using a shared bridge
- the host also is connected to the bridge and is running a beacon

When I start everything up, all nodes can see all beacons.  That's good.  When I kill one beacon and restart it, I see the following:
- the remaining beacon processes seem to hang on their listener beacon
- the newly restarted beacon sees all beacons

My processes are based on the zbeacon examples.  Also, each node runs the same exact binary as the host.

Are there any known issues with czmq and bridges?

**Comment by hintjens** [comment]
This is not a known problem. Since you can reproduce it, perhaps you would
like to investigate where the zbeacon code is hanging, and send a patch?
