### ISSUE TITLE
libzmq 4.1 socket options ZMQ_CONNECT_RID, ZMQ_HANDSHAKE_IVL not available in czmq

### ISSUE THREAD

**Issue by goddanao** [zeromq/czmq#1261]
Problem: Libzmq 4.1 introduces socket options ZMQ_CONNECT_RID (set only), ZMQ_HANDSHAKE_IVL (get/set) which are not mapped in src/sockoptions.xml
Solution: Map them in src/sockoptions.xml and regenerate.

**Comment by bluca** [comment]
Fixed in https://github.com/zeromq/czmq/pull/1536
