### ISSUE TITLE
jni build is failing using latest czmq from master

### ISSUE THREAD

**Issue by awynne** [zeromq/czmq#1264]
I did a fresh clone, then ran gradlew test:

```
:test
java: src/zdir.c:1000: zdir_test: Assertion `zpoller_wait (watch_poll, 1001) == watch' failed.
 * zproc: OK
 * zcert: OK
 * zdir: :test FAILED

FAILURE: Build failed with an exception.
```

**Comment by awynne** [comment]
the build works if i check out the last commit from 12/17 (913b0b4)

**Comment by hintjens** [comment]
Something broke in a recent patch to libzmq master... I'll find out what it
is.

**Comment by hintjens** [comment]
Sorry, my last comment was wrong. Can you run this again a couple of times and see if dies consistently, or just now and then...

**Comment by hintjens** [comment]
@awynne did this problem persist?

**Comment by hcarty** [comment]
I've seen this problem intermittently with the 3.0.2 tarball during `make test`, from a simple `./configure && make && make test && make install` case on Ubuntu 14.04 64bit, compiling against zeromq 4.1.3 from Chris Lea's PPA (https://launchpad.net/~chris-lea/+archive/ubuntu/zeromq).

**Comment by hintjens** [comment]
No further data on this, closed.
