### ISSUE TITLE
UDP_FRAME_MAX not prefixed by ZSYS_

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1268]
I'd like to check if CURVE security is available by using `zsys_has_curve()` from within Ruby. Since there's no API file for zsys yet (and thus the generated FFI binding doesn't support it), I just wanted to create it.

Unfortunately, the constant `UDP_FRAME_MAX`, which is defined in zsys.h, would automatically get the prefix `ZSYS_` by zproject. 

What's the best solution?

* adapt code within czmq to use the prefixed one
* add macro alias to still support non-prefixed one

**Comment by hintjens** [comment]
The place to add this is the new zproc class. The zsys class will remain
for internal use. It's not at the right level to be exposed to bindings IMO.
