### ISSUE TITLE
zloop_start does not terminate when ticket handler returns -1

### ISSUE THREAD

**Issue by StevenButner** [zeromq/czmq#1278]
While running on an Ubuntu 14.04LTS (x64) system it was found that when a ticket timeout handler returns -1 to a zloop reactor, zloop_start does not terminate.  The API description for zloop_start says that it terminates and "returns 0 if interrupted, -1 if cancelled by a handler."

It is clear from the inspection of source code at line 781 of zloop.c that the variable "rc" is never assigned the return code of -1 which is needed in order to make the zloop_start routine terminate.  I have posted this observation based on CZMQ-3.0.1 on the zeromq-dev-request and Pieter suggested that I check to see if it remains in CZMQ-3.0.2 and, if so, generate a pull request. I checked 3.0.2 and found that, indeed, the same bug exists.

This issue is being created per the C4 process in order that I can generate the pull request needed to fix it.

**Comment by hintjens** [comment]
Closed.
