### ISSUE TITLE
Android build fails in binding/jni

### ISSUE THREAD

**Issue by vimal-gsv** [zeromq/czmq#1287]
Android build in binding jni. 
FAIL AT zsock:test
log
--------
czmq/bindings/jni$ gradle build
:compileJava
:processResources UP-TO-DATE
:classes
:generateJniHeaders
:initCMake
-- The CXX compiler identification is GNU 5.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found JNI: /usr/java/jdk1.7.0_79/jre/lib/amd64/libjawt.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vnd2kor/bezirk/git/tmp/czmq/bindings/jni
:buildNative
Scanning dependencies of target czmqjni
[  5%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zarmour.c.o
[ 10%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zcert.c.o
[ 15%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zcertstore.c.o
[ 20%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zconfig.c.o
[ 25%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zdir.c.o
[ 30%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_ZdirPatch.c.o
[ 35%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zfile.c.o
[ 40%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zframe.c.o
[ 45%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zhash.c.o
[ 50%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zhashx.c.o
[ 55%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Ziflist.c.o
[ 60%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zlist.c.o
[ 65%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zloop.c.o
[ 70%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zmsg.c.o
[ 75%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zpoller.c.o
[ 80%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zproc.c.o
[ 85%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zsock.c.o
[ 90%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zstr.c.o
[ 95%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Ztrie.c.o
[100%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zuuid.c.o
Linking C shared library libczmqjni.so
[100%] Built target czmqjni
:jar
:assemble
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:testjava: src/zsock.c:1709: zsock_test: Assertion `rc == 0' failed.

 * ztrie: OK
 * zuuid: OK
 * zconfig: OK
 * ziflist: OK
 * zhashx: OK
 * zstr: OK
 * zframe: OK
 * zdir: OK
 * zmsg: OK
 * zcert: OK
 * zsock: :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 134

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.05 secs

**Comment by hintjens** [comment]
Hmm, this works fine for me. Can you try running './configure && make check' in the CZMQ root directory? We need a line number and error message (usually an assertion failure).

**Comment by vimal-gsv** [comment]
i did ./configure and make check. it fails
also added "export TOOLCHAIN_VERSION=4.9" to your .bashrc.
and gave a build in jni, that fails

============================================================================
make[3]: Leaving directory '/home/vnd2kor/bezirk/git/tmp/czmq'
/bin/bash ./libtool --mode=execute ./src/czmq_selftest
Running czmq selftests...
 * zactor: OK
 * zauth: OK
 * zarmour: OK
 * zbeacon: OK
 * zcert: OK
 * zcertstore: OK
 * zchunk: OK
 * zclock: OK
 * zconfig: OK
 * zdigest: OK
 * zdir: OK
 * zdir_patch: OK
 * zfile: OK
 * zframe: OK
 * zgossip: OK
 * zhash: OK
 * zhashx: OK
 * ziflist: OK
 * zlist: OK
 * zlistx: OK
 * zloop: OK
 * zmonitor: OK
 * zmsg: OK
 * zpoller: OK
 * zproc: OK
 * zproxy: OK
 * zrex: OK
lt-czmq_selftest: src/zsock.c:1709: zsock_test: Assertion `rc == 0' failed.
 * zsock: Makefile:2201: recipe for target 'check-local' failed
make[2]: *** [check-local] Aborted (core dumped)
make[2]: Leaving directory '/home/vnd2kor/bezirk/git/tmp/czmq'
Makefile:2035: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/vnd2kor/bezirk/git/tmp/czmq'
Makefile:1591: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
.
[Uploading czmq-build-error.txt…]()

**Comment by hintjens** [comment]
So this has nothing to do with JNI; if "make check" fails in root we have another issue. Let me close this and make a new issue...
