### ISSUE TITLE
Problem: cannot compile czmq without libsodium

### ISSUE THREAD

**Issue by sappo** [zeromq/czmq#1294]
In commit f6148067 the libsodium dependency has been added to czmq which by default uses libsodium. That's fine though it it not possible to compile without libsodium. I tried `configure --without-libsodium` which does not work.

**Comment by hintjens** [comment]
Can you post the actual error, rather than "does not work"? Thanks ☺

**Comment by sappo** [comment]
That will be useful, indeed :P
No mather the arg_with value, if libsodium is not installed the error message in line 100 (https://github.com/zeromq/czmq/blob/master/configure.ac#L100) is thrown.

I do have a workable solution which I will commit to zproject shortly. Just have to make sure not breaking anything by doing so.

**Comment by hintjens** [comment]
Ah, we have "optional" in the use element.

**Comment by sappo** [comment]
@hintjens yep, figured that out after creating a complicated solution. On the upside this did refresh my autoconf skills :)
