### ISSUE TITLE
Problem: zarmour_encode & zmsg_encode have non-object returns

### ISSUE THREAD

**Issue by hintjens** [zeromq/czmq#1300]
This method returns a byte array and a size (via size_t ref). This is nasty, for a number of reasons. We should ban this kind of allocation. It should return a new zchunk.

Can we break the API here?

Note zmsg_encode does the same, except the other way around :-(

Solution: fix both these to return allocated zchunk's.

**Comment by paddor** [comment]
I'd welcome this change. But yeah, I guess it'd break some user code, especially zarmour_encode.
