### ISSUE TITLE
zloop can't work with SERVER sockets

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1317]
After adding a SERVER socket to the zloop and then calling `zloop_start()`, it returns immediately with 0.

Works fine with PAIR socket.

**Comment by somdoron** [comment]
This is known issue. But you can use zpoller, which support SERVER and CLIENT sockets.

**Comment by paddor** [comment]
Okay, thanks.

**Comment by paddor** [comment]
Closing because it's a duplicate of zeromq/czmq#1123.

**Comment by somdoron** [comment]
The best way to make it work is to make zloop use zmq_poller, however zloop is complicated and we will have to split implementation to support version without ZMQ_POLLER. 

The good news is that zmq_poller already does a lot of what zloop is doing, zmq_timers is doing the rest, so it will simplify the zloop code.

**Comment by paddor** [comment]
Sounds good. Not urgent, though. Thanks for the info.
