### ISSUE TITLE
Question: building without self_test.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#1320]
Is it no longer possible to build without `czmq_selftest`?

I see `--without-zmakecert` has been changed to `--disable-zmakecert` but `--without-czmq_selftest` has been removed.

**Comment by evoskuil** [comment]
Related to the above question is this error. Building either `czmq_selftest` or `zmakecert` results in this linker error on my Ubuntu build. I've been avoiding this by not building these, but without that option...
```
  CC       src/src_zmakecert-zmakecert.o
  CC       src/src_czmq_selftest-czmq_selftest.o
  CCLD     src/libczmq.la
  CCLD     src/czmq_selftest
  CCLD     src/zmakecert

/usr/bin/ld: /home/eric/bs-prefix//lib/libzmq.a(usrsrc_libzmq_la-/bindecoder_allocators.o)/ld:: undefined / referencehome/eric to/bs- symbolprefix/ 'ceil@@lib/libzmq.aGLIBC_2.2.5(src_libzmq_la'
/-decoder_allocators.o/lib/): undefinedx86_64- reference linux-gnuto /libm.so.6symbol 'ceil@@GLIBC_2.2.5'
//lib/x86_64: -linuxerror adding-gnu symbols/libm.so.6::  errorDSO missing adding from  command symbols:line
DSO missing from command line

collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[1]: *** [src/zmakecert] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [src/czmq_selftest] Error 1
```
It appears that `libm` is either missing or improperly ordered in the dependencies for these two builds.

**Comment by pmienk** [comment]
This appears related to recent change zeromq/zproject@974252bca452c9b67d6e8a425cb32a6333ad0776.  I'm curious as to why the test project is a noinst_PROGRAMS as well as check_PROGRAMS.  zeromq/zproject#469 indicates an acknowledgement of the cost on dependents and a desire to avoid it for generated projects.

**Comment by hintjens** [comment]
My bad, I removed the --disable-czmq-selftest yesterday. As the cost of
building this is so low, and the option solves no clear problem, I removed
it.

I take it you want it back? it's in zproject.

The link error you're getting is from somewhere else, and probably deserves
fixing anyhow.

**Comment by evoskuil** [comment]
Thanks, it just helps reduce the total build time. We have had problems hitting the Travis limit.

**Comment by hintjens** [comment]
FWIW I've noticed that CMake builds much faster than autotools. We could
also enable parallel make (I did this for the Android builds).

**Comment by evoskuil** [comment]
We haven't done anything with CMake yet, but we do perform all builds in parallel. This doesn't help on Travis though, since we only get one core. Travis recently extended our build time, so it hasn't been as much of an issue.

**Comment by evoskuil** [comment]
The above fix has been regressed by https://github.com/zeromq/czmq/commit/014a13913af9463c17c046a08aca06c5fa87b408
