### ISSUE TITLE
Problem: link failure building czmq_selftest and zmakecert

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#1323]
Building either `czmq_selftest` or `zmakecert` results in this linker error on my Ubuntu build (static/prefix).
```
  CC       src/src_zmakecert-zmakecert.o
  CC       src/src_czmq_selftest-czmq_selftest.o
  CCLD     src/libczmq.la
  CCLD     src/czmq_selftest
  CCLD     src/zmakecert

/usr/bin/ld: /home/eric/bs-prefix//lib/libzmq.a(usrsrc_libzmq_la-/bindecoder_allocators.o)/ld:: undefined / referencehome/eric to/bs- symbolprefix/ 'ceil@@lib/libzmq.aGLIBC_2.2.5(src_libzmq_la'
/-decoder_allocators.o/lib/): undefinedx86_64- reference linux-gnuto /libm.so.6symbol 'ceil@@GLIBC_2.2.5'
//lib/x86_64: -linuxerror adding-gnu symbols/libm.so.6::  errorDSO missing adding from  command symbols:line
DSO missing from command line

collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[1]: *** [src/zmakecert] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [src/czmq_selftest] Error 1
```
It appears that `libm` is either missing or improperly ordered in the dependencies for these two builds.

**Comment by hintjens** [comment]
Can you help me reproduce this? (I usually run the default autotools build and don't get this error.)

**Comment by evoskuil** [comment]
The build is executed by a libbitcoin build script. The script orchestrates a build for each repo using the standard GNU steps, which basically results in these calls...
```
# libsodium
./autogen.sh
./configure --disable-shared --prefix=/home/eric/czmq-prefix --with-pkgconfigdir=/home/eric/czmq-prefix/lib/pkgconfig
make -j4
make install

# libzmq
./autogen.sh
./configure --disable-shared --prefix=/home/eric/czmq-prefix --with-libsodium --with-pkgconfigdir=/home/eric/czmq-prefix/lib/pkgconfig
make -j4
make install

# czmq
./autogen.sh
./configure --disable-shared --prefix=/home/eric/czmq-prefix --with-pkgconfigdir=/home/eric/czmq-prefix/lib/pkgconfig
make -j4
make install
```
I tried reducing to `-j1` but no difference. I also tried removing libsodium from the build, along with the zmq `--with-libsodium` option, but I encountered compile failures in czmq. Not sure if there is a different issue there. I've emailed the full log to you.

**Comment by Meijuh** [comment]
I have almost the same issue, but with pthread on Debian 8. When I run `./configure --disable-shared` I get the error when running `make`: 

    CCLD     src/makecert
    CCLD     src/test_zgossip
    /usr/bin/ld: src/.libs/libczmq.a(src_libczmq_la-zactor.o): undefined reference to symbol      'pthread_create@@GLIBC_2.2.5'
    //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    Makefile:1062: recipe for target 'src/makecert' failed
    make[1]: *** [src/makecert] Error 1
    make[1]: *** Waiting for unfinished jobs....
    /usr/bin/ld: src/.libs/libczmq.a(src_libczmq_la-zactor.o): undefined reference to symbol       'pthread_create@@GLIBC_2.2.5'
    //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    Makefile:1068: recipe for target 'src/test_zgossip' failed
    make[1]: *** [src/test_zgossip] Error 1

A workaround I found is `make LDFLAGS="-lpthread"`.

**Comment by hintjens** [comment]
So I can't reproduce the problem (sorry for taking so long, I was stuck in other work). However it's definitely due to libm, and you can solve it by passing `-lm` to the linker. I *think* the libm dependency comes via libsodium. 

Try setting LDFLAGS, as @Meijuh suggests: `make LDFLAGS="-lm"`

**Comment by evoskuil** [comment]
No worries, I'm able to work around for now by not building the executables. I'll look into whether this should be added to the libsodium package config.

**Comment by hintjens** [comment]
OK, I reproduced and (I think) fixed it in zproject.
