### ISSUE TITLE
Python bindings test fail

### ISSUE THREAD

**Issue by zoobab** [zeromq/czmq#1345]
I am trying out the python bindings (I use version 2698b432a879a21ce68e7688f93b7e5f16548b59), and the test.py fails:

    zoobab@sabayonx86-64 /home/zoobab/soft/czmq/bindings/python [212]$ python2.7 test.py 
    ........E.
    ======================================================================
    ERROR: test_zmsg (__main__.TestCZMQ)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "test.py", line 708, in test_zmsg
        buffer_size = msg.encode(buffer)
      File "/home/zoobab/soft/czmq-master/bindings/python/czmq/_czmq_ctypes.py", line 4357, in     encode
        return lib.zmsg_encode(self._as_parameter_, byref(c_void_p.from_param(buffer)))
    ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected LP_c_void_p instance    instead of pointer to LP_c_byte
    
    ----------------------------------------------------------------------
    Ran 10 tests in 2.947s
    
    FAILED (errors=1)

This is the same error if I try with python3.4.

**Comment by asokoloski** [comment]
Ah, ok.  I'll take a look.

**Comment by asokoloski** [comment]
Hmm, this is not as simple to fix as I thought.  I'm working on higher level wrappers for some of the czmq classes at the moment, and if I can think of a good way to handle it I'll do so.

**Comment by sphaero** [comment]
This is the same as #1327 I thought we fixed this in the generator?

**Comment by twhittock** [comment]
I pushed a fix for this about a month ago. Sorry didn't notice the issue.
