### ISSUE TITLE
make check fails at zsock selftest on OS X 

### ISSUE THREAD

**Issue by bigusbangus** [zeromq/czmq#1346]
Starting after pull request #1336 09bb247, which added radio dish support the selftest fails for zsock on OS X.  I pulled and compiled the newest versions of libsodium and libzmq and czmq.  Czmq fails the selftest with "Assertion failed: (server), function zsock_test, file src/zsock.c, line 1970." and it appears that zmq_bind is returning an error value, but that is as far as I was able to chase it.  If I revert back to 9af0f53 everything works as expected.

**Comment by bluca** [comment]
A radio-dish test fails in libzmq too, most likely related: https://github.com/zeromq/libzmq/issues/1761

**Comment by somdoron** [comment]
I'm working on it...

**Comment by bluca** [comment]
@bigusbangus - could you please build from libzmq master and try again? We solved the issue there, so if it's still a problem on CZMQ then it was unrelated.

**Comment by bigusbangus** [comment]
Thanks, it's resolved and sorry to post a libzmq bug to czmq.  The newest commits on libzmq and czmq build on OS X without issue.
