### ISSUE TITLE
Creating multiple zactors crash. 60 actors limit reached

### ISSUE THREAD

**Issue by svdev** [zeromq/czmq#1373]
Hello, 

Can anyone have a look at this issue? 
http://stackoverflow.com/questions/35965983/czmq-multiples-zactor-instances-crash

I'm not sure if this is produced by a misuse of zactor (which I cannot see) or due to some bug when using pollers within actors. I've spent quite some time digging it but I cannot see what is the issue. I believe somewhere there is some memory leaking within the zactors created. Anyone can reproduce this ?

Using czmq-3.0.2_1 on a Mac Os X

Some Valgrind output:
$ valgrind --leak-check=full --show-leak-kinds=all ./demo 
....
...
...
==79142== 76,616 bytes in 61 blocks are still reachable in loss record 172 of 175
==79142==    at 0x100009EBB: malloc (in /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==79142==    by 0x10010C43D: operator new(unsigned long) (in /usr/lib/libc++.1.dylib)
==79142==    by 0x10010C48F: operator new(unsigned long, std::nothrow_t const&) (in /usr/lib/libc++.1.dylib)
==79142==    by 0x10008D224: zmq::socket_base_t::create(int, zmq::ctx_t*, unsigned int, int) (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x1000727CA: zmq::ctx_t::create_socket(int) (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x1000A1280: zmq_socket (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x10003B9B6: zsys_socket (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x100031372: zsock_new_checked (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x10003BB59: zsys_create_pipe (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x100012D14: zactor_new (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x10000147B: main (demo.c:170)
==79142==
==79142== 77,872 bytes in 62 blocks are still reachable in loss record 173 of 175
==79142==    at 0x100009EBB: malloc (in /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==79142==    by 0x10010C43D: operator new(unsigned long) (in /usr/lib/libc++.1.dylib)
==79142==    by 0x10010C48F: operator new(unsigned long, std::nothrow_t const&) (in /usr/lib/libc++.1.dylib)
==79142==    by 0x10008D224: zmq::socket_base_t::create(int, zmq::ctx_t*, unsigned int, int) (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x1000727CA: zmq::ctx_t::create_socket(int) (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x1000A1280: zmq_socket (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x10003B9B6: zsys_socket (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x100031372: zsock_new_checked (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x10003BB43: zsys_create_pipe (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x100012D14: zactor_new (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x10000147B: main (demo.c:170)
==79142==
==79142== 1,000,400 bytes in 61 blocks are still reachable in loss record 174 of 175
==79142==    at 0x100009EBB: malloc (in /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==79142==    by 0x100082A6B: zmq::pipepair(zmq::object_t**, zmq::pipe_t**, int*, bool*) (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x10008EDA1: zmq::socket_base_t::connect(char const*) (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x100032138: zsock_connect (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x10003BC32: zsys_create_pipe (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x100012D14: zactor_new (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x10000147B: main (demo.c:170)
==79142==
==79142== 1,000,400 bytes in 61 blocks are still reachable in loss record 175 of 175
==79142==    at 0x100009EBB: malloc (in /usr/local/Cellar/valgrind/3.11.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==79142==    by 0x100082B7B: zmq::pipepair(zmq::object_t**, zmq::pipe_t**, int*, bool*) (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x10008EDA1: zmq::socket_base_t::connect(char const*) (in /usr/local/Cellar/zeromq/4.1.3/lib/libzmq.5.dylib)
==79142==    by 0x100032138: zsock_connect (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x10003BC32: zsys_create_pipe (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x100012D14: zactor_new (in /usr/local/Cellar/czmq/3.0.2_1/lib/libczmq.3.dylib)
==79142==    by 0x10000147B: main (demo.c:170)
==79142==
==79142== LEAK SUMMARY:
==79142==    definitely lost: 0 bytes in 0 blocks
==79142==    indirectly lost: 0 bytes in 0 blocks
==79142==      possibly lost: 0 bytes in 0 blocks
==79142==    still reachable: 2,444,325 bytes in 3,525 blocks
==79142==         suppressed: 34,620 bytes in 426 blocks
==79142==
==79142== For counts of detected and suppressed errors, rerun with: -v
==79142== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 20 from 20)
Killed: 9

**Comment by hintjens** [comment]
I've answered it.

**Comment by svdev** [comment]
You saved my life, thanks !!

**Comment by svdev** [comment]
You saved my life, thanks !!

**Comment by hintjens** [comment]
No worries ☺
