### ISSUE TITLE
Problem : the function zsock_destory doesn't work

### ISSUE THREAD

**Issue by lushixian** [zeromq/czmq#1380]
Hi, 

I am working on a project and come across a problem. Could you give some help on this?
# I have written an example to detailed this problem, as following,
# include ”czmq.h“
# include ”string“
# include ”iostream“

using namespace std;

int main()
{
    void \* context = zsys_init();
    string inProcEndPoint = string("inproc://logging");

```
zsock_t * loggerSock = zsock_new_router(inProcEndPoint.c_str());
assert (loggerSock);    
cout << zmq_ctx_get(context, ZMQ_MAX_SOCKETS) <<endl;
cout << zmq_ctx_get(context, ZMQ_SOCKET_LIMIT) <<endl;
for (int i = 0 ; i < 1023; i ++)
{
    zsock_t * sock = zsock_new_dealer(inProcEndPoint.c_str());
    assert (sock);
    zsock_destroy (&sock);
}
return 0; 
```
# }

When I changed the loop count from "1023" to "1024", the program crashed with the following message, while 1023 is good.

> 1024
> 65535
> src/zsock.c:68 zsock_new_checked: Assertion 'self->handle' failed.

I think that maybe the zscok_destroy function doesn't work. However, maybe some other problems, could you give some help on this?

Thanks~

**Comment by bluca** [comment]
Hi,

The socket deallocation is asynchronous, it's not a problem of zsock_destroy.

Looks like you are hitting the FD limit. Are you on OSX by any chances? If memory serves, the file limit is 1024 there.

If you set: `ulimit -n 65535` it should fix your problem.

**Comment by lushixian** [comment]
hi
I am working on the redhat. the command  'ulimit -n 65535' doesn't fix my problem.  thank your help.

**Comment by lushixian** [comment]
I ran the command 'ulimit -n', the output is "4096", then I ran the program that I wrote again. the output is the same
"1024
 65535
 src/zsock.c:68 zsock_new_checked: Assertion 'self->handle' failed."

**Comment by pijyoi** [comment]
In zmq.h, ZMQ_MAX_SOCKETS_DFLT is defined as 1023. This is the default
value for ZMQ_MAX_SOCKETS.

So it's quite strange that your "zmq_ctx_get(context, ZMQ_MAX_SOCKETS)" is
returning 1024.

**Comment by svdev** [comment]
for (int i = 0 ; i < 1023; i ++) -> 1023 sockets is = ZMQ_MAX_SOCKETS
for (int i = 0 ; i <= 1023; i ++) -> 1024 sockets is > ZMQ_MAX_SOCKETS 
for (int i = 0 ; i < 1024; i ++) -> 1024 sockets is > ZMQ_MAX_SOCKETS

**Comment by bluca** [comment]
@lushixian - you need to increase the internal limit with: `zsys_set_max_sockets(NEW_LIMIT)`. If you want to go above your system's max, which appears to be 4096, you must also use your OS's API to increase it.
