### ISSUE TITLE
./configure fails on OS X (and probably others)

### ISSUE THREAD

**Issue by joegsn** [zeromq/czmq#1422]
HEAD fails to generate a working configure script on OS X, sources for ZMQ & CZMQ from today, due to a change to the configure.ac script since 3.0.2.  The change has been in for a while, I'm new to CZMQ.

In configure.ac, line 104:
`        AC_CHECK_LIB([libzmq], [zmq_init],`

This makes autogen.sh create a configure script which then attempts to link against a library named "libzmq", which would make the filename it's trying to link against be "liblibzmq.dylib" (OS X libs are .dylib, for the uninitiated).

The solution for me was to change the line to
`        AC_CHECK_LIB([zmq], [zmq_init],`
which then tries to link against a library named "zmq", and thus the file named "libzmq.dylib".

**Comment by bluca** [comment]
Hi,

How are you buillding/installing libzmq?

It's all building fine in the OSX CI: https://travis-ci.org/zeromq/czmq/jobs/125628865

**Comment by joegsn** [comment]
I installed ZMQ via the directions on http://zeromq.org/intro:get-the-software#toc2, then followed the directions on http://czmq.zeromq.org/page:get-the-software (with the exception of downloading from git instead of the 3.0.2 release).  
```
git clone https://github.com/zeromq/czmq.git
cd czmq
./autogen.sh
./configure    
make -j 4
make check 
sudo make install
```
Though obviously during ./configure, it failed.

**Comment by joegsn** [comment]
I did a little digging.  The reason the CI build works every time is that is specifies a specific pkg-config binary which also implies the location of a libzmq.pc file so that the CI build knows where to find libzmq.  For a system which lacks pkg-config or which does not have the libzmq.pc file installed correctly (which apparently is my case), then the configure.ac section starting on line 82 is use.  This part completely fails to find libzmq, as it's looking for the wrong name.  From the ./configure (not in ci-build):
```
checking for libzmq... no
checking for zmq_init in -llibzmq... no
configure: error: cannot link with -lzmq, install libzmq
```

**Comment by sappo** [comment]
@joegsn you're dragging us back into the pits of hell where the autotools daemons live ;)

#1423 should fix this issue. Take it out for a spin!

**Comment by bluca** [comment]
Thanks for digging in this! In general we do recommend to use pkgconfig (if it's not in the guide we should add it), but it should work without it at least for libzmq. The CI doesn't use a special pkgconfig binary, just adds the local build prefix to the path where it looks for .pc. This is to allow for sudo-less make install.

**Comment by hitstergtd** [comment]
Interesting. I haven't come across this as I have been using CMake. Is there a reason why we have a dual build system, former and autotools as well? Are there platforms not supported by CMake?

**Comment by bluca** [comment]
Yes, autotools are much better on embedded devices and older Unix environments. But CMake is better on WIndows.
Also it's a precise design choice to avoid tying ourselves to a particular build system. Much better to be flexible and work with all, even if it's a bit more work, but it can be largely abstracted and done in zproject.

**Comment by hitstergtd** [comment]
Ah, I see. Agreed. However, I think there is need to review the complete spread of configurable options supported in configure.ac, as opposed to the CMake build system. I believe I saw the latter to be missing some options couple of days ago, e.g. OpenPGM support, etc.

**Comment by bluca** [comment]
Yes indeed, especially in libzmq where they are all hand-written they fall out of sync sometimes.

**Comment by hitstergtd** [comment]
Yes, I should have been more specific. I did mean the above in reference to libzmq.

**Comment by joegsn** [comment]
@sappo That update solves my problem.  I really didn't mean to drag anyone back into coercing autotools to work right!  I was just sort of following along on the website (which has the same directions as the github readme).

Regarding cmake - I probably would've avoided directions to do this (if both existed) on Mac OS, simply because the libzmq cmake usage generates only the libzmq.framework and a static library, libzmq-static.a.  It sort of makes building a dependent library like czmq (and ultimately for my purposes - cztop) a little difficult.

**Comment by hitstergtd** [comment]
@joegsn - thanks for letting us know.

Since you mention that the cmake build system only generates the framework and static library artefacts, is there anything else that you would like to see?

Ideally if you can send us a pull request it would be most appreciated.

**Comment by joegsn** [comment]
@hitstergtd I haven't tried cmake on czmq, only on libzmq, so I have no idea how czmq's cmake support is.  I also don't know if maybe there's just a flag to cmake to build the OS X .dylib as well, as I have not looked into it in any depth.

**Comment by hitstergtd** [comment]
@joegsn - OK. There is a `ZMQ_BUILD_FRAMEWORK` option in the CMake build infrastrcture, which might be worth looking into if you ever decide to give the CMake build a spin.
