### ISSUE TITLE
README.md: wrong order of gcc args

### ISSUE THREAD

**Issue by AxelVoitier** [zeromq/czmq#1429]
Hi,

In [Linking with an Application](https://github.com/zeromq/czmq#linking-with-an-application) it seems to me (and my computer) that the order of arguments is wrong.
If I am not wrong, the linking args should be specified at the end.
If I actually try the command it fails with "undefined references" errors. If I put the -l args to the end then it works.

Or there is some kind of gcc versions that accept that?

Cheers,
Axel

**Comment by hitstergtd** [comment]
You are quite right -
<http://gcc.gnu.org/onlinedocs/gcc/Link-Options.html>

If you would like to send a pull request, I would be happy to merge it for you. :)

**Comment by AxelVoitier** [comment]
I will then!
