### ISSUE TITLE
Problem: there are no instruction how to build czmq debian packages

### ISSUE THREAD

**Issue by sappo** [zeromq/czmq#1433]
@bluca this seems to be your area of expertise! I don't even have the slightest clue where to start digging.

**Comment by bluca** [comment]
Configure autotools with the desired parameters, then build the release tarball with "make dist".
Copy the tarball in a new working directory, untar it (don't delete it), then copy packaging/debian inside the untarred source tree.
cd into it and to build the package run: "dpkg-buildpackage -uc -us"
You'll need to have all the debian tools installed (dpkg-dev, devscripts, etc).

**Comment by sappo** [comment]
Wonder why I didn't figure that out on myself :-D. Thanks!
I'll try to make travis generate the deb and push it to github releases automatically.

**Comment by bluca** [comment]
:-)

But please hold with the debs. See my message to the mailing list.

**Comment by sappo** [comment]
Makes sense, then I'll add a README with the steps and concentrate to build and publish the tarballs.
