### ISSUE TITLE
Undocumented zproxy behavior is causing assertion

### ISSUE THREAD

**Issue by piskorzj** [zeromq/czmq#1445]
Configuring zproxy actor is not an atomic operation, and received message between setting **FRONTEND** and **BACKEND** is causing assertion in `s_self_switch`.

Here is simple program to reproduce this issue:

```
#include <czmq.h>

int main(int argc, char **argv) {
  zactor_t *proxy = zactor_new (zproxy, NULL);
  assert (proxy);
  
  //  Connect application sockets to proxy
  zsock_t *faucet = zsock_new_push (">inproc://frontend");
  assert (faucet);
  zsock_t *sink = zsock_new_pull (">inproc://backend");
  assert (sink);
  
  zstr_sendx (proxy, "FRONTEND", "PULL", "inproc://frontend", NULL);
  zsock_wait (proxy);
  
  zstr_sendx (faucet, "Hello", "World", NULL);

sleep(1);

  zstr_sendx (proxy, "BACKEND", "PUSH", "inproc://backend", NULL);
  zsock_wait (proxy);

  return 0;
}
```

The easiest solution for this problem is to first configure *output* socket (like PUB, PUSH...) and then *input* ones. However, this is not documented anywhere.

**Comment by sappo** [comment]
Would you like to update the documentation and send a PR?

**Comment by piskorzj** [comment]
Sure, editing zproxy.c is enough?

**Comment by sappo** [comment]
Yes, thanks!

**Comment by piskorzj** [comment]
Problem is not that simple as I thought. Presented *solution* works for unidirectional socket (PUSH/PULL) quite well, however in my use case I need XPUB/XSUB. Now changing order of sockets gives nothing, because SUBSCRIBE also causes assertion.

Here is code snippet to reproduce:
```
#include <czmq.h>

int main(int argc, char **argv) {
  zactor_t *proxy = zactor_new (zproxy, NULL);
  assert (proxy);

  zsock_t *faucet = zsock_new_pub (">inproc://frontend");
  assert (faucet);

  zsock_t *sink = zsock_new_sub (">inproc://backend", "whatever");
  assert (sink);
 
  zstr_sendx (proxy, "BACKEND", "XPUB", "inproc://backend", NULL);
  zsock_wait (proxy);
 
  zstr_sendx (proxy, "FRONTEND", "XSUB", "inproc://frontend", NULL);
  zsock_wait (proxy);
  
  return 0;
}
```

Elegant way of fixing it would be making commands FRONTEND and BACKEND **not** adding sockets to poller, but instead, after configuration RESUME command should be called. But, this is not backward compatible at all.

**Comment by piskorzj** [comment]
I implemented solution that is backward compatible.
