### ISSUE TITLE
Problem: no way to access tuple(s) in zgossip

### ISSUE THREAD

**Issue by mvala** [zeromq/czmq#1459]
I would like to use zgossip and i can send some configuration tuples to the zgossip cluster, but didn't find command i have to send to get specific tuple or tuples back? In documentation there is

> At any point the application can access the node's set of tuples.

Can you give me hint?

**Comment by bluca** [comment]
This is not implemented yet, only the count can be dumped. A new API message for the actor could be added that triggers a dump, perhaps.

**Comment by bluca** [comment]
Of course any received tuple will be delivered to the applicatio:

```
DELIVER key value -- new tuple delivered from network
```

So in theory one could build manually a zhash and maintain it, but it would be duplicated so I do see a case for a way to access the database at any moment.

**Comment by bluca** [comment]
I have implemented 2 new commands:

```
    * KEYS -- return number of keys followed by each key in its own frame
    * TUPLE key -- return value associated with requested key
```

https://github.com/bluca/czmq/commit/d21bf8fe21aa892e99b0a8b1e157872cb39e2061

But thinking about it, it feels a bit awkward to use.

Given all tuples are delivered to the application as DELIVER messages upon receipt, it's really trivial to keep and use them if needed, so I'd be more inclined to just fix the documentation unless there's a particular reason to add the new api.

**Comment by sphaero** [comment]
I've had this discussion with @hintjens in the past for Zyre:
https://github.com/zeromq/zyre/issues/297

I think we decided back then that the Zyre was already sending the Hello's which implies you should already know what peers are available so no need to request this from the API again.

This might apply here as well?

**Comment by bluca** [comment]
Thanks, that insight was helpful. I also agree with that conclusion. I've opened a PR to fix the documentation.

I'll keep the other solution around in my fork if someone comes up with a valid use case for being able to dump the internal state.
