### ISSUE TITLE
czmq --enable-drafts doesn't completely enable the draft api

### ISSUE THREAD

**Issue by joegsn** [zeromq/czmq#1475]
I'd been banging my head against a wall for a bit, trying to figure out how to get the client/server socket types working in czmq.  I'd realized yesterday that the functionality required the --enable-drafts parameter to the configure script, but while that seemed to enable them, they didn't actually work.  A very simple program that would create a zsock_new_server, and then assert that it was valid would error out, because the result was null.

It finally occurred to me that zmq also defines a drafts parameter for building itself.  The cflag define is also used in its header.  But maybe the configure script isn't taking that into account.  When I finally ran it with a CFLAGS="-DZMQ_BUILD_DRAFT_API" environment variable set, then it finally built correctly, and I could use the server/client socket types again.

So, in czmq (with libzmq already being configured/compiled/installed with ./configure --enable-draft=yes), the following was needed for me to build with it all enabled.
```env CFLAGS="-DZMQ_BUILD_DRAFT_API" ./configure --enable-drafts ; make ; make install```

I'm minimally knowledgable about autogen scripts, but I believe this can be solved with a simple patch which would make the configure script add that cflag when --enable-drafts is true. (This two-line addition seemed to work for me.)
```
diff --git a/configure.ac b/configure.ac
index e92970a..8f26527 100755
--- a/configure.ac
+++ b/configure.ac
@@ -422,6 +422,8 @@ if test "x$enable_drafts" = "xyes"; then
     AC_MSG_NOTICE([Building stable and legacy API + draft API])
     AC_DEFINE(CZMQ_BUILD_DRAFT_API, 1, [Provide draft classes and methods])
     AC_SUBST(pkg_config_defines, "-DCZMQ_BUILD_DRAFT_API=1")
+    AC_DEFINE(ZMQ_BUILD_DRAFT_API, 1, [Provide draft classes and methods])
+    AC_SUBST(pkg_config_defines, "-DZMQ_BUILD_DRAFT_API=1")
 else
     AC_MSG_NOTICE([Building stable and legacy API (no draft API)])
     AC_SUBST(pkg_config_defines, "")
```

I think there are probably other compile scripts (for maybe cmake, or windows) which might need adjusting as well, to supports the draft api.

**Comment by bluca** [comment]
You need to use pkg-config, the standard on *nix, when building your applications. Then you will get all the necessary flags. This should not be hacked around in czmq.

```
gcc `pkg-config --cflags --libs libzmq libczmq` foo.c ...
```

Or the equivalent autoconf or cmake macros.

**Comment by somdoron** [comment]
@bluca what do you think about create a page in the docs that explain how to build with draft? we can also add more examples from more OS in reference to the doc page whenever someone has a problem.

**Comment by joegsn** [comment]
So, then the correction in the build process for czmq needs to be to fail if pkg-config is misconfigured, because this is one really frustrating headache.
If pkg-config wasn't finding libzmq.pc, and thus wasn't providing the correct cflags, then something should fail miserably.

**Comment by joegsn** [comment]
Throwing it out here as a possibility, but if you're going to require that enable-drafts relies on pkg-config, then maybe the pkg-config check for libzmq (when enable-drafts is enabled) should fail if it's not found?  Perhaps something like this, if you don't want to make too many modifications?
```
diff --git a/configure.ac b/configure.ac
index e92970a..9039e85 100755
--- a/configure.ac
+++ b/configure.ac
@@ -80,6 +80,11 @@ PKG_CHECK_MODULES([libzmq], [libzmq >= 0.0.0],
     [
     ],
     [
+        AM_CONDITIONAL([ENABLE_DRAFTS], [test x$enable_drafts != xno])
+        if test "x$enable_drafts" = "xyes"; then
+            AC_MSG_ERROR([enable-drafts requires libzmq to be found by pkg-config.])
+        fi
+
         AC_ARG_WITH([libzmq],
             [
                 AS_HELP_STRING([--with-libzmq],
```

I'm just putting it out there, as it makes sense to me, that if you're going to say "well, you should be using pkg-config" that maybe you should just force using pkg-config when compiling czmq.  Heck, I'd be in favor of zapping the 'else' case in the pkg-check-modules for how to find libzmq if pkg-config can't located it.  At least then I'd never be surprised by it saying the build for czmq with enable-drafts succeeded only to find out it failed like this.

Yes, I get that this wouldn't happen to someone who's .pc files ended up in the correct pkg-config path, but obviously I didn't.

**Comment by bluca** [comment]
Sorry for your troubles building. But pkg-config is not mandatory and it shouldn't be as it might not be available on embedded platforms where autotools is a necessity. As I said, everything can be done manually by adding the required flags via environment variables, by design.

As Doron said, the right approach is to fix the documentation and to make clear that one has to either use pkg-config as a convenience (and how to configure it) or if that is not possible he/she needs to look into the each and every dependency and make sure any required flag is manually added, including the preprocessor flags, and not only the linker flags which are commonly taken for granted.

I will update the readme file and the build page on the wiki.

**Comment by bluca** [comment]
Also, DRAFT APIs in zmq are not always strictly correlated to DRAFT APIs in czmq. It might very well be that they are in that state in only one of the libraries.

**Comment by joegsn** [comment]
I understand what you're saying.  It just surprises me that A requires B, but enabling A does not imply B.  Regardless of how ignorant I'm currently being (pkg-config misconfiguration), or if A might not require B in the future.

I guess documentation will have to be the workaround for ignorance.
