### ISSUE TITLE
Problem: zdir.c, zmsg.c and test_zgossip.h are still LGPL3 licensed

### ISSUE THREAD

**Issue by bluca** [zeromq/czmq#1482]
@hintjens @somdoron  - while doing some license sanity check on some packages I maintain (on Debian: `licensecheck -r .`), I noticed that zdir.c, zmsg.c and test_zgossip.h were not changed to MPL2 with commit eabe063c2588cde0af90e5ae951a2798b7c5f7e4 and still mention the LGPL3:

https://github.com/zeromq/czmq/blob/master/src/zdir.c
https://github.com/zeromq/czmq/blob/master/src/zmsg.c
https://github.com/zeromq/czmq/blob/master/include/test_zgossip.h

Was this intentional, or is it a simple clerical error?

**Comment by hintjens** [comment]
clerical error... would you be able to send a PR?

**Comment by bluca** [comment]
Will do shortly
