### ISSUE TITLE
Can I use my EPOLL with CZMQ/libZMQ?

### ISSUE THREAD

**Issue by matttbe** [zeromq/czmq#1487]
Hello,

First, I want to say that I am discovering ZMQ project for a few days now and I am very impressed by all the possibilities it offers. Thank you for developing and maintaining it!

I am currently playing a bit with (c)ZMQ but with a program which already has its own thread to read events from an EPOLL loop.

I was able to integrate my `zsock`'s FD in the EPOLL system but I was wondering if there were some side effects when doing that. Is it supported by CZMQ/libZQM?

Here is what I am currently doing:

``` c
z_sock = zsock_new(ZMQ_REP);
zsock_bind(z_sock, "ipc:///tmp/test.matttbe.sock");
fd = zsock_fd(z_sock);
add_in_epoll(fd, EPOLLIN | EPOLLERR | EPOLLET, data);
```

Then when I receive an event:

``` c
sock = zsock_resolve(z_sock);
ret = zmq_recv(sock, buffer, 7, ZMQ_DONTWAIT);
```

I am using `zmq_recv()` because I need this `DONTWAIT` option.

Can you confirm me that I can do that? Or should I be careful with some other things?

Thank you again for this great lib!

Matth

**Comment by bluca** [comment]
It can be done, but ZMQ FDs are edge triggered, so before receiving you should check if there is a poll-in event and then get all the messages in one go, as you will not get one notification per message (ie: if you get a notification and 2 messages are available, but receive only one, if you return to polling you will not get a notification for the second one).

```
while(ZMQ_POLLIN & zsock_events(z_sock)) {
  //recv
  //do work
}
```

See ZMQ_FD section at http://api.zeromq.org/master:zmq-getsockopt

**Comment by matttbe** [comment]
Hello Luca,

Thank you for this very quick answer, it has solved my problem!

Thank you for pointing me to this part of ZMQ doc, I didn't see that! I was already using a `while true` loop because of the use of `EPOLLET` but I will do that with `zsock_events`!

I am then closing this ticket, thanks!

**Comment by matttbe** [comment]
Hello,

Just a last quick question: in my `while` loop, if I am using `(ZMQ_POLLIN & zsock_events(z_sock))` as condition, do I have to still use `zmq_recv` with `ZMQ_DONTWAIT` or am I sure that all calls will not block and then I can use cZMQ API?

**Comment by bluca** [comment]
As long as that condition is true recv will not block, so you can use CZMQ's API.

**Comment by matttbe** [comment]
Excellent! :-)
Thank you for this quick answer!
