### ISSUE TITLE
zbeacon fails to reconnect when changing IP addresses (Windows, small interval)

### ISSUE THREAD

**Issue by twhittock** [zeromq/czmq#1501]
zbeacon detects a failure to send, and will then immediately attempt to recreate the socket on whichever interfaces are currently available.

This fails when changing IP addresses, because the bind will assert (address not available) because the interface hasn't finished reconfiguring itself.

Putting a small delay in between the failed send and the reconfigure resolves the issue for me, but it doesn't seem clean. What's the correct method?

```
            if (zsys_udp_send (self->udpsock, self->transmit, &self->broadcast, sizeof (inaddr_t)))
                //  Try to recreate UDP socket on interface
                // <<< HERE WE NEED TO SLEEP OR SOMEHOW DETECT THE INTERFACE IS UP >>>
                s_self_prepare_udp (self);
```

**Comment by bluca** [comment]
Fixed by PR, closing. Thanks!
