### ISSUE TITLE
The NEWS file should contain release notes

### ISSUE THREAD

**Issue by aalex** [zeromq/czmq#1504]
Hi,
I am looking for the release notes for each version.
It should be in the following file:
https://github.com/zeromq/czmq/blob/master/NEWS

We should see a list of bugs fixed and new features implemented. Instead, there are quite a few version numbers under which nothing is written.

**Comment by bluca** [comment]
Yes we've been very lazy with that, sorry. It will be fixed before the next release.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/pull/1542
