### ISSUE TITLE
There should be one branch per major.minor version series

### ISSUE THREAD

**Issue by aalex** [zeromq/czmq#1505]
It would be simpler if there was one branch per major.minor series.

Example branches:
* master
* 2.2
* 3.1
* etc.

This way, it would be easy to checkout the latest version for a given major.minor series. (the micro version number are for bug fixes - if using semantic versioning - http://semver.org )

**Comment by bluca** [comment]
Hi,

We won't maintain older releases on this project, there is going to be only one train. We follow the C4 process: http://rfc.zeromq.org/spec:42/C4/
This means API will not be broken until they are retired, following the C4 lifetime (draft -> stable -> deprecated -> retired)
