### ISSUE TITLE
The required version of ZMQ for the build should be enforced

### ISSUE THREAD

**Issue by aalex** [zeromq/czmq#1506]
I am trying to build CZMQ 2.2.0 against ZMQ 4.1.3 with Visual Studio 2015, but it doesn't work. The packaging of CZMQ 2.2.0 should probably check that the version of ZMQ is 4.0.4. (one that is known to work)

Thank you.

**Comment by bluca** [comment]
Current releases of CZMQ will check what version of ZMQ is being used and compile accordingly, so there is no hard dependency. Older versions of CZMQ might not be compatible with newer versions of ZMQ, but we don't maintain older versions, please use the latest stable instead.

Please do open a new issue if you encounter problems with the latest version of CZMQ.
