### ISSUE TITLE
node.js binding windows build

### ISSUE THREAD

**Issue by sualex** [zeromq/czmq#1507]
**I do need node.js bindings built on windows platform. I have MS Visual Studio 2015 enterprise update 3 installed on build machine. Doing all the npm installations right and running npm install inside .../bindings/nodejs I get (after it correctly builds libzmq in upper dir) :** 

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  libczmq.vcxproj -> D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\Release\libczmq.lib
  libzmq.vcxproj -> D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\Release\libzmq.lib
  binding.cc
  win_delay_load_hook.cc
d:_work\vendor_zeromq\czmq\bindings\nodejs\binding.h(606): error C2059: syntax error: '__leave' (compiling source file ..\binding.cc) [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
d:_work\vendor_zeromq\czmq\bindings\nodejs\binding.h(606): error C2238: unexpected token(s) preceding ';' (compiling source file ..\binding.cc) [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(716): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(1455): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(2060): warning C4244: '=': conversion from 'int64_t' to 'off_t', possible loss of data [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(2087): warning C4244: '=': conversion from 'int64_t' to 'off_t', possible loss of data [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(2224): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(4077): error C2059: syntax error: '__leave' [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(4502): error C2589: '__leave': illegal token on right side of '::' [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(4502): warning C4091: '': ignored on left of 'void' when no variable is declared [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(4502): error C2143: syntax error: missing ';' before '::' [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(4502): error C2059: syntax error: '::' [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(4502): error C2143: syntax error: missing ';' before '{' [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(4502): error C2447: '{': missing function header (old-style formal list?) [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
..\binding.cc(6084): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data [D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\build\czmq.vcxproj]
prebuild ERR! build error
prebuild ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onExit (D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\node_modules\node-gyp\lib\build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:106:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:191:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
prebuild ERR! not ok
prebuild ERR! build Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onExit (D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\node_modules\node-gyp\lib\build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! czmq@0.0.1 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the czmq@0.0.1 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the czmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs czmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls czmq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:_WORK\vendor_ZEROMQ\czmq\bindings\nodejs\npm-debug.log

**VS2013 toolset shows the same result. I'm not a very skilled c++ man and have no time to figure out why it doesn't like that '_leave' statement :) . Can anyone help to get around of that? Or nodejs bindings are unbuildable on windows in current state? Did anyone try to do the same? Thanks a lot.**

**Comment by bluca** [comment]
The nodejs bindings are generated from here:

https://github.com/zeromq/zproject/blob/master/zproject_nodejs.gsl

Unfortunately I don't have a Windows machine to test it and I also am really not familiar with node. I hope some other contributor can chip in.
