### ISSUE TITLE
Why doesn't zsock have `terminated()` fn?

### ISSUE THREAD

**Issue by petehayes102** [zeromq/czmq#1509]
I've noticed that while `zpoller` (et. al.) has logic for determining whether polling was interrupted, `zsock` doesn't. This is problematic where CZMQ captures SIGTERM and doesn't share it with the application: if the application is polling a single socket, it makes it impossible to distinguish between a connection/transmission issue and a valid signal.

The patch to `zsock.c` would be pretty trivial, I think, though I'm wondering if there's a technical reason why this hasn't been done already? If not, I'll PR it!

**Comment by bluca** [comment]
zsys_interrupted is set whenever sigint or sigterm are catched, that's the canonical way to check. Is that not enough for some use cases?

**Comment by petehayes102** [comment]
Yep that's fine. I was just wondering why `zpoller` had a helper fn `zpoller_terminated()` and `zsock` didn't. Upon further inspection, it seems `zpoller` has extra rules around what constitutes "terminated". I think I've answered my own question! Sorry.

**Comment by bluca** [comment]
No problem!
