### ISSUE TITLE
CZMQ won't compile with CFLAGS="-DNDEBUG"

### ISSUE THREAD

**Issue by Meijuh** [zeromq/czmq#1519]
Simply run `make CFLAGS="-DNDEBUG"`, the result is:

src/zclock.c: In function 'zclock_test':
src/zclock.c:222:13: error: unused variable 'usecs' [-Werror=unused-variable]
     int64_t usecs = zclock_usecs ();
...

**Comment by bluca** [comment]
We don't support NDEBUG because that will disabled asserts, which we intentionally use to flag illegal use of the APIs.

**Comment by Meijuh** [comment]
Couldn't we fix this such that NDEBUG is undefined, something like:

    #ifdef NDEBUG
    undef NDEBUG
    #endif

The reason I find this useful is that I have an environment variable `CFLAGS="-DNDEBUG"`, meaning I have to unset it specifically for CZMQ in my CI environment.

**Comment by bluca** [comment]
That's fine for me, would you send a PR for it?
