### ISSUE TITLE
CZMQ fails: Symbol not found: _zsys_handler_reset

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1545]
I get this after I compile ZMQ and CZMQ either with or without `--enable-drafts`. But I don't get the error after I compile directly from master (with `--enable-drafts`).

```
dyld: lazy symbol binding failed: Symbol not found: _zsys_handler_reset
  Referenced from: /usr/local/lib/libczmq.dylib
  Expected in: flat namespace

dyld: Symbol not found: _zsys_handler_reset
  Referenced from: /usr/local/lib/libczmq.dylib
  Expected in: flat namespace
```

I'm on macOS 10.12.1.

EDIT: I meant *after* compiling, not when compiling.

**Comment by bluca** [comment]
Strange, this is not a DRAFT api, so it's simply exported.

Is this when building czmq itself? Or a program linking to it?

**Comment by paddor** [comment]
I don't get the error when building, but when starting a process that links to it dynamically, like CZTop's test suite.

**Comment by bluca** [comment]
Mmh can't reproduce on Linux:

```
#include <stdio.h>
#include <czmq.h>

int main (int argc, char **argv)
{
    zsock_t *s = zsock_new_rep("inproc://asd");
    zsys_handler_reset();
    zsock_destroy(&s);
    printf("bye!\n");

    return 0;
}
```

````
$ gcc `pkg-config --libs --cflags libczmq` test.c -o test
$ ./test
bye!
````

Unfortunately I don't have an OSX system. Could it be due to some quirks of OSX dylibs or the LD_LIBRARY_PATH or equivalent?

Also I can see the symbol using readelf -a on the shared library, again on Linux, so it looks like it's exported correctly:

```
readelf -a /usr/lib/x86_64-linux-gnu/libczmq.so.4.0.0 | grep zsys_handler_reset
00000025df08  012800000006 R_X86_64_GLOB_DAT 0000000000043840 zsys_handler_reset + 0
   296: 0000000000043840   100 FUNC    GLOBAL DEFAULT   11 zsys_handler_reset
```

Would you be able to help by doing some more digging into the OSX built shared library? I assume there's readelf there as well.

**Comment by tpitale** [comment]
I'll try to do some digging. For those who find this later, install `readelf` with homebrew on a mac: `brew install binutils`. Tool is installed with `g` prefix.

`greadelf -a /usr/local/lib/libczmq.dylib | grep zsys_handler_reset` results in:
`readelf: Error: Not an ELF file - it has the wrong magic bytes at the start`

@bluca @paddor Ideas on what other tool might get me the information to see if the symbol is in the `dylib`?

**Comment by tpitale** [comment]
I found `nm`:

```
nm -gU /usr/local/lib/libczmq.dylib | grep zsys_handler_reset     
0000000000032420 T _zsys_handler_reset
```

**Comment by bluca** [comment]
So the symbol is there... Sorry, I'm really not an expert on OSX (don't even own a OSX machine), so I really have no idea what's going wrong there

**Comment by tpitale** [comment]
I've fixed the problem locally by installing zmq and czmq with homebrew using `--HEAD`.

`zeromq/HEAD-4a24805` and `czmq/HEAD-7ea67c9`

**Comment by bluca** [comment]
So I guess it's a problem of LD_LIBRARY_PATH or what's called on OSX?

@paddor does that fix it for you as well?

**Comment by paddor** [comment]
Not getting error anymore, so closing this issue.
