### ISSUE TITLE
Problem: interface change breaks czmqpp.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#1546]
It appears that there must have been a breaking change to the `czmq` public API as `czmqpp` is showing a [build break](https://travis-ci.org/libbitcoin/libbitcoin-explorer/jobs/128136973). Could someone please confirm if this is intended? Thanks!

**Comment by bluca** [comment]
Hi,

Yes, I opened an issue on czmqpp a while ago: https://github.com/zeromq/czmqpp/issues/43

As discussed on the mailing list for a good while now, we retired the deprecated APIs.

Best thing would be to solve the issue above, otherwise punting the CI to v3.0.2 could do as a stop gap.

**Comment by evoskuil** [comment]
Ah, sorry I missed it and thanks for posting. I'll follow up there.
