### ISSUE TITLE
Problem: v3.0.2 requires sudo because of docs install.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#1547]
See discussion: https://github.com/zeromq/czmqpp/issues/43#issuecomment-258660990

**Comment by bluca** [comment]
We decided not to branch/fork for releases and keep one repo/branch, so we can't fix this. The issue is that there is no manual config switch, and if the packages are available it will build and install the docs.

For CI scripts, a workaround might be to make sure those packages for doc building are not available:

```
AC_CHECK_PROG(czmq_have_asciidoc, asciidoc, yes, no)
AC_CHECK_PROG(czmq_have_xmlto, xmlto, yes, no
```

Would that work for your use case?

**Comment by evoskuil** [comment]
This is why we use release branches, it gets really hard to patch a down-level major release - and upgrading isn't always an option for the customer. I realize it's a philosophical decision, but from my experience it doesn't hold up well over time.

Our installer isn't just for CI, it's the primary means by which customers deploy. With multiple dependent libraries and the vagaries of building boost (with optionally ICU) in the proper configuration, and several other conditional dependencies, and the zeromq stack for our client-server libraries, it's really essential - at least until we are packaged (not soon). So we generate the installer script for each repository, and we test it via CI. This ensures that the installer always works and makes it easy to build up our CI runs (yml is also generated).

So we can't really generate these statements into the build artifacts, because they aren't limited to CI use. Doing so would create a lot of additional work and break the link between CI and tested installers.

**Comment by bluca** [comment]
A possible solution would be to retroactively tag v3.0.3 at the point where --without-documentation was added, which is commit 1b5d637250b001e9dd39ef0416e49fc0039d171f
Would that work for you? If so, could you please manually test that commit to make sure it works fine for you library and applications?

I don't mind doing this tagging as it's pretty cheap, and a bugfix release point is arbitrary anyway. We won't publicly announce it anywhere to avoid confusion.

**Comment by sappo** [comment]
Or we can fork czmq to its own repository as we've done with libzmq and
provide it with zproject updates.

Am 08.11.2016 12:50 nachm. schrieb "Luca Boccassi" <notifications@github.com

**Comment by bluca** [comment]
The problem with forking and maintaining 3.0.x is that, well, we'd have to maintain it :-)

And it would make sense only if we could take the bug fixes and leave behind all ABI and API breakages. I had a quick look before releasing 4.0, but there were so many and so intertwined that reverting all of them was going to be a serious pain. And then backporting fixes would be even more problematic.

I just checked, and even that commit I linked above is ABI/API incompatible with 3.0.2 :-(

**Comment by evoskuil** [comment]
But this implies the only version that people can expect to use is latest, since there is no option to patch a  down-level version in a supportable way. It's not that one must back-port all patches, there's a reason for new versions. But the inability to do so basically makes the down-level version, no matter how recent, unsupportable.

**Comment by evoskuil** [comment]
@sappo Why would forking to a new repo be preferrable to branching? These are roughy equivalent to me. Thanks to both of you for your thoughts on it.

**Comment by sappo** [comment]
@evoskuil branches are mostly invisible except if you know what you're looking for. Also browsing them on github is painful IMO. Forking them to another repository increases visibility to users who require the old version.

My suggestions is that @evoskuil forks czmq 3. Then he can patch it! If there are others that require the old czmq 3 version to be supplied with patches we can move the fork to the zeromq community.

**Comment by evoskuil** [comment]
@sappo 
> branches are mostly invisible except if you know what you're looking for.

Isn't that exactly what you want? Why else would you move it outside of the community?

We maintain one other fork for a similar reason and I can do this here, but it just sort of sucks in both cases. People always ask why we aren't using the main repository and question what changes we are making.

**Comment by bluca** [comment]
We talked this over in all the meetings and events we had, and the general agreement was always against branches. I don't necessarily agree 100% with that, but that's the rule we agreed on, and it's part of the C4.1 process.

In general we _do_ want the latest version to be used. That's why I came up with the DRAFT mechanism, so that new things wouldn't be exposed until they are stable, so the latest version can be used safely. But I can understand a request to keep a legacy repo which is API compatible.

The fork would be in the org, just like https://github.com/zeromq/zeromq4-1 and https://github.com/zeromq/zeromq4-x it could be czmq3-x and it would be forked at the v3.0.2 tag. It would have to be kept ABI/API compatible with v3.0.2. If you are up for that, I think it's the cleanest solution, and I can set it up.

**Comment by evoskuil** [comment]
I understand, and I appreciate the efforts. I've just completed the work to use a libbitcoin fork of my personal czmq fork, which I maintain with the nuget packaging sources that I believe were lost in the zproject transition. So I'm quite alright with it at present. It's temporary in any case, since we have dropped it in future releases (in favor of plain zeromq).

**Comment by evoskuil** [comment]
It appears that the same docs issue exists with the zeromq 4.2.0 package. Would it be possible to get a patched tag/release to resolve it for that repo?

Coincidentally we recently stopped using sudo in our CI builds, so we've apparently missed this problem until this re-visitation of previous version builds, This was one of the concerns I had about dropping the sudo builds in order to get onto Travis fast platforms.

**Comment by evoskuil** [comment]
Actually I have that last part backwards, the problem is happening on the non-sudo builds in our previous version. I'm not exactly sure why we aren't seeing it in our newer non-sudo builds. Would it be different if we are building directly from git sources vs. a tarball?

**Comment by bluca** [comment]
Interesting, I'll have a look tonight.
I think we don't build the docs on Travis to speed it up, might be worth adding one linux build for them.

**Comment by bluca** [comment]
Can't see this problem building from git or from tarball, using --with-docs=no or --with-docs=yes. Configuring with --prefix=/tmp/test make install works just fine in all cases.

What are the configure arguments you are using?

**Comment by evoskuil** [comment]
The configuration options that are getting set are reflected [here](https://travis-ci.org/evoskuil/libbitcoin-client/jobs/174466448#L909):
```
configure: --disable-perf --disable-drafts --disable-curve-keygen --with-libsodium --with-pkgconfigdir=/home/travis/build/evoskuil/libbitcoin-client/my-prefix/lib/pkgconfig
```
It looks like the tarball dependencies are not getting the installer options passed through. The build-from-tarball dependencies is new code in our previous version installer, so this is probably just a bug in that feature, for both czmq and zeromq.

**Comment by evoskuil** [comment]
Parameter passing for the `--prefix` option was the issue :<.

In other news, we see [these warnings](https://travis-ci.org/evoskuil/libbitcoin-client/jobs/174642185#L1070-L1071) when building libzmq v4.2.0 (release tarball):

```
checking for asciidoc... no
checking for xmlto... no
configure: WARNING: You are building an unreleased version of 0MQ and asciidoc or xmlto are not installed.
configure: WARNING: Documentation will not be built and manual pages will not be installed.
```
Also, we are encountering [unknown pragma failures](https://travis-ci.org/evoskuil/libbitcoin-client/jobs/174642185#L1488-L1494) when building czmq v3.0.2 (release tarball) in clang:

```
  CC     src/src_libczmq_la-zactor.lo
In file included from src/zactor.c:34:
In file included from ./src/../include/czmq.h:30:
In file included from ./include/czmq_library.h:24:
In file included from ./include/czmq_prelude.h:210:
/home/travis/build/evoskuil/libbitcoin-client/my-prefix/include/zmq_utils.h:40:32: error: 
      unknown warning group '-Wcpp', ignored [-Werror,-Wunknown-pragmas]
#pragma GCC diagnostic warning "-Wcpp"
                               ^
/home/travis/build/evoskuil/libbitcoin-client/my-prefix/include/zmq_utils.h:41:32: error: 
      unknown warning group '-Werror', ignored [-Werror,-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-Werror"
```

I should be able to suppress `-Wunknown-pragmas` - just seems a little obtuse to be suppressing errors caused by warning suppression. But given this is czmq 3.0.2 that's what I'll do.

**Comment by evoskuil** [comment]
I was able to complete the czmq 3.0.2. clang builds using `-Wno-unknown-pragmas`, although this just converts the errors to heavily repeating warnings.
```
  CXX    src/authenticator.lo
In file included from src/authenticator.cpp:20:
In file included from ./include/czmq++/authenticator.hpp:24:
In file included from ./include/czmq++/context.hpp:23:
In file included from /home/travis/build/evoskuil/libbitcoin-client/my-prefix/include/czmq.h:30:
In file included from /home/travis/build/evoskuil/libbitcoin-client/my-prefix/include/czmq_library.h:24:
In file included from /home/travis/build/evoskuil/libbitcoin-client/my-prefix/include/czmq_prelude.h:210:
/home/travis/build/evoskuil/libbitcoin-client/my-prefix/include/zmq_utils.h:40:32: warning: 
      unknown warning group '-Wcpp', ignored [-Wunknown-pragmas]
#pragma GCC diagnostic warning "-Wcpp"
                               ^
/home/travis/build/evoskuil/libbitcoin-client/my-prefix/include/zmq_utils.h:41:32: warning: 
      unknown warning group '-Werror', ignored [-Wunknown-pragmas]
#pragma GCC diagnostic ignored "-Werror"
                               ^
```
Similarly there are heavily repeating deprecation warnings. These should be reduced to a single warning for the build. In any case I'm closing out this issue as a case of user error.

**Comment by bluca** [comment]
Ah that's great that it works now :-) We have clang builds in the CI, I'll have a look to see if there are similar warnings in the latest version.

**Comment by bluca** [comment]
I don't see warnings when building with Clang on Linux or OSX in the CI on latest master, so I think we already fixed those.

**Comment by evoskuil** [comment]
Okay, but for future depreciations I'd recommend isolating the warnings so that they don't repeat for each inclusion of the primary header in the library build itself. Otherwise every release will be crippled by that output.

**Comment by evoskuil** [comment]
Also, thanks for the great work, and great support.
