### ISSUE TITLE
Problem: zgossip_msg_test is DRAFT but run as non-draft in czmq_selftest.c

### ISSUE THREAD

**Issue by bluca** [zeromq/czmq#1548]
zgossip_msg_* are internal APIs and not intended to be exported.

zgossip_msg_* APIs are generated as DRAFT:

https://github.com/zeromq/czmq/blob/master/src/zgossip_msg.h#L29
https://github.com/zeromq/czmq/blob/master/src/czmq_classes.h#L266

But zgossip_msg_test is listed among the stable APIs in czmq_selftest:

https://github.com/zeromq/czmq/blob/master/src/czmq_selftest.c#L61

@sappo any idea what's going on here? I can't for the life of me figure out why zproject is generating the API list as DRAFT but when it comes to add the test to czmq_selftest, then draft is false.

**Comment by sappo** [comment]
@bluca this is a zproto generated. I'll fix it later. I have done the same for zyre last week.

**Comment by bluca** [comment]
I've seen that, but that change in zyre actually created the problem there as well:

```
+    { "zre_msg", zre_msg_test },
      { "zyre_peer", zyre_peer_test },
      { "zyre_group", zyre_group_test },
      { "zyre_node", zyre_node_test },
  #ifdef ZYRE_BUILD_DRAFT_API
      { "zyre", zyre_test },
      { "zyre_event", zyre_event_test },
 -    { "zre_msg", zre_msg_test },
  #endif // ZYRE_BUILD_DRAFT_API
```

https://github.com/zeromq/zyre/pull/488/commits/5c957a100053795a888cf14e42db28a819e06ffb

But it's a useful starting point trying to debug this.

**Comment by bluca** [comment]
So making zgossip_msg not private moves indeed the test in the right place:

```
-    { "zgossip_msg", zgossip_msg_test },
 #ifdef CZMQ_BUILD_DRAFT_API
     { "zproc", zproc_test },
     { "ztimerset", ztimerset_test },
     { "ztrie", ztrie_test },
+    { "zgossip_msg", zgossip_msg_test },
 #endif // CZMQ_BUILD_DRAFT_API
```

This sounds like a zproject issue, I'll keep looking.

**Comment by sappo** [comment]
Where exactly does the problem occur?

**Comment by bluca** [comment]
Found it, it's this check here:

https://github.com/zeromq/zproject/blob/master/zproject_class_api.gsl#L55

**Comment by bluca** [comment]
So the background is, and a PR will come soon, that I found an issue with the way I implemented the DRAFT APIs: in C++, we have to explicitly set the visibility to global to make a libzmq symbol public and exported in the SO.

But this is C, and all global symbols are exported by default! So even when building with --enable-drafts=no, the shared object leaks all the draft symbols.

The solution is to introduce a $project_PRIVATE macro in zproject that is used in src/$project_classes.h instead of $project_EXPORT that sets the visibility to hidden.

But then I hit a build failure, since zgossip_msg_test is used by czmq_selftest, which can't found anymore the zgossip_msg_test symbol.

I think the right solution here is to stop adding the $class_test to $project_selftest if it's private.
Private symbols should not be exported and visible to external binaries like the $project_selftest

**Comment by sappo** [comment]
I follow your argument. But i.e. zyre has a couple of private classes which contain important test code. If we exclude those we must find another we to test those private classes.

**Comment by bluca** [comment]
Yes indeed - my proposal is that a private class test is run by the public class that uses the private one.

**Comment by sappo** [comment]
Hmm...it's not perfect but should work.

**Comment by bluca** [comment]
Yes it's not elegant and has to be fixed manually which is annoying, but I'm of course open to other ideas. But the symbols leakage is bad and needs to be fixed ASAP. I'll cut a new release before it causes problems to distros (had to patch it manually for Debian!).

**Comment by bluca** [comment]
https://github.com/zeromq/zproject/pull/711
Will send the fix for the symbols afterwards

**Comment by bluca** [comment]
https://github.com/zeromq/zproject/pull/712

Will let the CI run the tests of the regenerated CZMQ and then send a regen + add back the test to zgossip_test
