### ISSUE TITLE
No online documentation?

### ISSUE THREAD

**Issue by jtanx** [zeromq/czmq#1563]
Version 4 has been marked as stable, but I don't see any online documentation on this API. Am I missing something here?

Thanks!

**Comment by bluca** [comment]
The documentation in the main landing page of the repo applies: https://github.com/zeromq/czmq

But yes czmq.zeromq.org should be updated. Unfortunately I do not have permissions to do so. @sappo any idea how we can update that site?

**Comment by sappo** [comment]
I don't have the permissions either. Maybe @somdoron does.

**Comment by sappo** [comment]
Hi @squidfunk,
all details about the czmq API can be found in the `README.md` online https://github.com/zeromq/czmq/blob/master/README.md and on the released tarballs as well. Also there is a man page `man zactor` which contains the same information.

**Comment by sappo** [comment]
Okay, I see. There is another section that might help https://github.com/zeromq/czmq#toc2-8450 including a template on how to implement an actor.

**Comment by squidfunk** [comment]
Thanks, I will look into it!

**Comment by sappo** [comment]
@squidfunk if this is not enough, please open another ticket i.e. "Improve zactor documentation" and then we can discuss what is missing to guide beginners to learn the zactor api quickly :)

**Comment by bluca** [comment]
@sappo you regenerated the zguide right? Any chance you could do the same for the CZMQ website given you are familiar with the tools?

**Comment by sappo** [comment]
@bluca I'm able to regenerate the guide. But I couldn't publish it as I don't have access to the wikidot zguide wiki and neither the czmq wikidot wiki. I request a new wiki for the zguide but the wikidot folks are not very responsive.

**Comment by bluca** [comment]
Ah I see. If it's not too much could you please request a new one for CZMQ too?

**Comment by somdoron** [comment]
@sappo @bluca I'm trying to get control for those websites. Maybe we can transform them to work on gitbook, someone already did it for rfc.zeromq.org, so it might be easier, I will try to find who.

**Comment by somdoron** [comment]
@yrashk how hard will it be to use gitbook with czmq and zguide?

**Comment by sappo** [comment]
@somdoron czmq should be fairly simple as we already as a markdown representation namely `README.md`. The zguide is a different beast I tried the migrate it to Pieter's latests publishing tool `mkbook` but it does not support images or code snippets which are required for the guide. Porting the zguide is a lot of work.

**Comment by somdoron** [comment]
@sappo so for now can we host the czmq documentation of gitbook? I can change the DNS.
@yrashk did it and already have some experience.

**Comment by sappo** [comment]
It will be a copy of the github landing page in gitbook style, but yes!

**Comment by somdoron** [comment]
@sappo @bluca you should have an invitation on wikidot to the czmq and zguide.
Please confirm and let me know when you joined.

**Comment by sappo** [comment]
ACK

**Comment by bluca** [comment]
Got it, thanks!

**Comment by bluca** [comment]
Fixed by @sappo - thanks!

http://czmq.zeromq.org/
