### ISSUE TITLE
CZMQ fails tests on MacOSX, possibly due to randof() macro

### ISSUE THREAD

**Issue by jimklimov** [zeromq/czmq#1569]
As detailed in PR #1567 which in particular revised the `randof()` macro, the Travis tests still fail on MacOS by getting a random array index which is too big (and it being such is unexpected and an error that we catch by `assert()` - or segfault otherwise).

Probably the `rand()` and/or `random()` functions and/or the `RAND_MAX` system-define involved in the macro have a different syntax on MacOS than on other tested OSes (Linux and illumos/Solaris).

Maybe the heavy-lifting and choice of routine (`random()` should be preferable if both are available, from what I read) better belongs in autoconf checks rather than a C macro.

**Comment by bluca** [comment]
yeah autoconf would be better for this kind of thing, on the other hand it also needs to be implemented in cmake

anyone with OSX able to help to get the right definitions?

**Comment by bluca** [comment]
@jimklimov I can't see this test failure happening, can you still reproduce it?

**Comment by jimklimov** [comment]
No, and I don't think it popped out at me directly either - when I was just hacking on this area, I saw some CI tests fail (build 385 in your travis - see https://travis-ci.org/bluca/czmq/jobs/181979236 for details) and reported it.

I see that the recent builds are all green, so the problem either is fixed by some other developments (good) or is quite sporadic (bummer to catch).

Probably this issue can be closed for now, and kept in mind if the failure does pop up again...

**Comment by bluca** [comment]
Ok, missed that. Let's close for now given it's never happened again. There are enough builds happening, that hopefully it means it's been fixed by some other change :-)
