### ISSUE TITLE
Problem: Ruby bindings don't work on Windows

### ISSUE THREAD

**Issue by kou** [zeromq/czmq#1581]
Because `:uint64_t` type is used. It doesn't exist in ffi gem. We should use `:uint64` instead. `:uint64` exists in ffi gem.

I've fixed it in zeromq/zproject#771.

Solution: Regenerate Ruby bindings.

**Comment by bluca** [comment]
Could you please send a PR to regenerate?

**Comment by kou** [comment]
I've created #1582 .
