### ISSUE TITLE
Problem: CZMQ does not support new DRAFT handshake success/failure monitor events

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1589]
With recent versions of CZMQ and ZMQ, CZTop's test suite for zmonitor sometimes fails because of an undocumented event `UNKNOWN`. According to the build history ([#346](https://travis-ci.org/paddor/cztop/builds/188271308), [#347](https://travis-ci.org/paddor/cztop/builds/188271708), [#348](https://travis-ci.org/paddor/cztop/builds/188271732)) on Travis CI, it appears to happen randomly.

When it happens, CZMQ prints a warning:

```
E: 17-01-02 15:58:07 illegal socket monitor event: 4096
```

According to [zmq.h](https://github.com/zeromq/libzmq/blob/master/include/zmq.h#L409-L420) the event 4096 (`0x1000`) does not exist.

The relevant test example (in Ruby) looks like this:

```ruby
describe CZTop::Monitor do
  subject { CZTop::Monitor.new(rep_socket) }
  let(:actor) { subject.actor }
  i = 55578
  let(:endpoint) { "tcp://127.0.0.1:#{i+=1}" }
  let(:req_socket) { CZTop::Socket::REQ.new(endpoint) }
  let(:rep_socket) { CZTop::Socket::REP.new(endpoint) }

  after(:each) do
    subject.terminate
  end

  describe "#next" do
    it "gets the next event" do
      subject.listen("ALL")
      subject.start
      req_socket # connects
      req_socket.disconnect(endpoint)
      subject.actor.options.rcvtimeo = 100
      assert_equal "ACCEPTED", subject.next[0]
      rep_socket.ffi_delegate.destroy
      assert_equal "CLOSED", subject.next[0] # sometimes UNKOWN
      assert_equal "MONITOR_STOPPED", subject.next[0]
    end
  end
end
```

Any ideas?

**Comment by bluca** [comment]
That's a new event to track curve handshake success/failure:

https://github.com/zeromq/libzmq/blob/master/include/zmq.h#L566

It should be disabled unless DRAFT APIs are enabled. Did you build libzmq with --enable-drafts?

**Comment by paddor** [comment]
I see, so CZMQ doesn't recognize these new events yet. 

Some of the builds do enable draft API. But for example job [#346.4](https://travis-ci.org/paddor/cztop/jobs/188271312) uses stable versions of ZMQ and CZMQ, not using `--enable-drafts`. Weird thing though: According to the console output of the build job, at least CZMQ still enables the draft API. Do I need to pass `--enable-drafts=no` to avoid it? Does ZMQ behave the same?

I use the two scripts in [here](https://github.com/paddor/czmq-ffi-gen/tree/master/ci-scripts) to build the two libraries, which are pretty straight forward. Does the draft API have to be explicitly disabled?

**Comment by bluca** [comment]
For development ease a check was added, and DRAFT APIs will be automatically enabled if cmake/configure detects that they are being used in a git repository (check for .git directory). If that's the case for your build then yes you have to manually disable them.

We should also start supporting the new events in CZMQ anyway, so I'll change the title
