### ISSUE TITLE
on windows/debug, zclock test unstable

### ISSUE THREAD

**Issue by bbdb68** [zeromq/czmq#1605]
it often fails on line 225
    assert ((zclock_usecs () - usecs) >= 10000);

assertions, but not every run. Only occurs in debug mode.

**Comment by bluca** [comment]
From src/zclock.c:

```
    The Win32 Sleep() call defaults to 16ms resolution unless the system
    timer resolution is increased with a call to timeBeginPeriod() permitting
    1ms granularity.
```

The test is sleeping for 10ms, so maybe this is the problem. Could you please give it a test?
