### ISSUE TITLE
windows/release self tests run with assert macro disabled

### ISSUE THREAD

**Issue by bbdb68** [zeromq/czmq#1610]
this requires a change in the appveyor configuration file. 

I will do it after czmq is updated with new zproject including 
https://github.com/zeromq/zproject/pull/843 
so that the effect of changing appveyor file can be easy checked.

**Comment by bluca** [comment]
There were a couple of things missing, I've fixed them:

https://github.com/zeromq/zproject/pull/844
https://github.com/zeromq/zproject/pull/845

And regenerated:

https://github.com/zeromq/czmq/pull/1611

**Comment by bluca** [comment]
@bbdb68 it's up to date now, so please send the config change whenever you are ready

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/pull/1612
