### ISSUE TITLE
4.0.2 tarfile: self test fails; 

### ISSUE THREAD

**Issue by WyoMurf** [zeromq/czmq#1621]
On an ubuntu 16.04, I pulled the latest tarballs for zeromq and czmq;
made and installed zeromq, no previous installation on this system.

When I built czmq, I did a make check and got:

/bin/bash ./libtool --mode=execute ./src/czmq_selftest
Running czmq selftests...
 * zactor: OK
 * zarmour: OK
 * zcert: OK
 * zcertstore: OK
 * zchunk: OK
 * zclock: OK
 * zconfig: OK
 * zdigest: OK
 * zdir: OK
 * zdir_patch: OK
 * zfile: OK
 * zframe: OK
 * zhash: OK
 * zhashx: OK
 * ziflist: OK
 * zlist: OK
 * zlistx: OK
 * zloop: OK
 * zmsg: OK
 * zpoller: OK
 * zsock: OK
 * zsock_option: E: 17-02-11 11:06:08 zsock heartbeat_ivl option not supported by libzmq version 4.1.4, run with libzmq >= 4.2.0

E: 17-02-11 11:06:08 zsock heartbeat_ivl option not supported by libzmq version 4.1.4, run with libzmq >= 4.2.0

lt-czmq_selftest: src/zsock_option.inc:4129: zsock_option_test: Assertion `zsock_heartbeat_ivl (self) == 2000' failed.
Makefile:1829: recipe for target 'check-local' failed
make[2]: *** [check-local] Aborted (core dumped)
make[2]: Leaving directory '/home/murf/czmq-4.0.2'

So, what did I do wrong? is the version that libzmq is reporting incorrect?

==============ANOTHER THING, while I'm here===================

I was looking at the doc for czmq, and in the czmq(7) page, I see that it is not complete,
it ends with: E: unhandled condition

=====================Done==================================

**Comment by bluca** [comment]
What's the version of libzmq? Where did you get it from?

Are you sure you don't have the libzmq package installed from Ubuntu? Because it's complaining that you have 4.1.4, which is exactly the version shipped by Xenial: http://packages.ubuntu.com/xenial/libzmq5

**Comment by WyoMurf** [comment]
Yeah, I suspected that first, but searched the whole system and nothing else found...
but another search done and sigh, yes, I did have it installed, and my install didn't complete.
So, I will shamefully close this ticket!

**Comment by bluca** [comment]
Perfect, glad it's all sorted
