### ISSUE TITLE
Doc problem?

### ISSUE THREAD

**Issue by WyoMurf** [zeromq/czmq#1622]
Was browsing on czmq.zeromq.org, and looking at the man page for the latest 
release, and found that czmq(7) is truncated, the last bit says:

 E: unhandled condition

A small nit, I know, but it's the biggest bug I can find right now.

**Comment by bluca** [comment]
Yes I can see it:

http://czmq.zeromq.org/czmq4-0:czmq

@sappo any clue what's wrong there?

**Comment by sappo** [comment]
Good catch, this page needs some updates anyhow. I'll have a look at it
tomorrow.

Am 11.02.2017 22:18 schrieb "Luca Boccassi" <notifications@github.com>:

**Comment by sappo** [comment]
Fixed!

@bluca perl has been wrong :mask:

**Comment by bluca** [comment]
Unbelievable! :-D
