### ISSUE TITLE
Looking for build czmq for iOS

### ISSUE THREAD

**Issue by whisper-bye** [zeromq/czmq#1628]
I have found some way too old to build it, so
Is there a way to build libczmq.a for iOS?
thx!

**Comment by bluca** [comment]
@febeling hi you sent a fix for iOS once, do you still build CZMQ there? Any tips to share to build it by any chance? Thanks!

**Comment by febeling** [comment]
@bluca - na, I didn't do that in a long time, so I can't help with the current state, unfortunately.

**Comment by bluca** [comment]
Ok, thank you.

@whisper-bye I think a few people build with cmake for the apple osx SDK/xcode, maybe that could work? If you find a way please report back so we can add it to the readme

**Comment by whisper-bye** [comment]
@bluca 
Ok, I will try to do it by my self, but it looks very hard...

**Comment by bluca** [comment]
Sorry, but I really don't know anything about iOS builds.
I would recommend sending a mail to the mailing list, maybe someone can help:
http://zeromq.org/docs:mailing-lists

**Comment by azawawi** [comment]
Please take a look at my forks of [libsodium-ios](https://github.com/azawawi/libsodium-ios) and [libzmq-ios](https://github.com/azawawi/libzmq-ios). These are the Ruby scripts that I use to generate [SwiftyZeroMQ](https://github.com/azawawi/SwiftyZeroMQ/tree/master/Libraries) binaries for Apple desktop/mobile platforms. The idea is simple. You compile the needed platforms and then pack them into a [universal binary](https://en.wikipedia.org/wiki/Universal_binary) library. Please take a look [here](https://github.com/azawawi/SwiftyZeroMQ/blob/master/Documentation/Manual.md#bundled-zeromq-library) for the included architectures per platform. Also you may need to enable [BitCode](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html) for all mobile platforms depending on the minimum supported version.

**Comment by whisper-bye** [comment]
@azawawi 
Good catch! but how about czmq?

**Comment by azawawi** [comment]
@whisper-bye 
Read the README.md and then try to modify from line \#[250](https://github.com/azawawi/libzmq-ios/blob/master/libzmq.rb#L250) till line \#[267](https://github.com/azawawi/libzmq-ios/blob/master/libzmq.rb#L267). Have fun 👍

**Comment by whisper-bye** [comment]
thanks all!
I will report back with my progress later.

**Comment by bluca** [comment]
Thanks @azawawi ! Any chance you could add some basic pointers to http://zeromq.org/intro:get-the-software in a new iOS section?

**Comment by azawawi** [comment]
@bluca Thanks. It is already on my to-do list 👍
