### ISSUE TITLE
Why not available on jessie?

### ISSUE THREAD

**Issue by lucaszanella** [zeromq/czmq#1629]
I see that it's only available on stretch and sid, may I ask why? It seems that this project is kinda old, why it's only available on the newest  and unstable debian?

**Comment by bluca** [comment]
Only Debian Developers can upload packages to Debian, and at the time Jessie was released no one did. And once it's released new packages cannot be added.

You can find packages builds for Jessie from the latest head of master on our OBS project:

http://download.opensuse.org/repositories/home:/zeromq:/git-stable/Debian_8.0/
