### ISSUE TITLE
zbeacon listener gets stuck

### ISSUE THREAD

**Issue by detlevcasanova** [zeromq/czmq#1630]
Hello !

We are having some difficulties with (C)ZMQ. A device is sending `zbeacons` until a client connects to it.
Once the client is connected, beacons are suspended and restarted once the client disconnects.

In a setup where the same client is disconnecting and reconnecting every 30 seconds, after a certain amount of time (we have seen between 2 minutes up to 8 hours), the client hangs.

After some debugging, we realized that the hang occurs when getting the `zframe` from the beacon listener.

Using a `zloop`, a handler is used as a reader to process incoming beacons. The process is as follow:
 * The handler is called
 * The peer address is read (`zstr_recv()`)
 * The frame from the peer is read (beacons are filtered on a fixed string) (`zframe_recv()`)
 * Connection is established

When it hangs, it happens on `zframe_recv()` (which, according to strace, calls `poll(fd, 1, -1)`, as expected) but no data is coming in.

We also realized that the peer address is not valid (and after adding debug in the code, it looks like `s_self_handle_udp()` is not called before the beacon handler is called by `zloop`).

Digging deeper, we saw that the string was not random, it is always `wfUD3"^Q`, which corresponds, in hexadecimal, to `0x7766554433225E51`.

That's where I am stuck. It looks like a signal `zmsg` (`zmsg_new_signal()`) but can't find how it would get there and can't reproduce the issue with valgrind.

Going maybe a bit too far, `0x7766554433225E51 - 0x1100 = 0x7766554433224D51` which would make the last 2 letters `MQ` (reminding ZMQ). `0x1100` is the expected value of the zmsg_signal encoding.

The current workaround is to call `zsock_set_rcvtimeo(listener, 500);` on the beacon listener but it looks like it is not enough and the `zactor` thread for the `zbeacon` seems to be broken. Not knowing the full impact of this behavior, this can't be kept like this.

Can you enlighten us ? Is that a bug or expected behavior ? Could it be related to this issue: https://github.com/zeromq/czmq/issues/1260 ?

**Comment by detlevcasanova** [comment]
Never mind, It is apparently fixed on master.

**Comment by bluca** [comment]
There was a regression in libzmq a couple months back, but it was fixed quickly
