### ISSUE TITLE
Problem: Null pointer exception in ziflist if network adapters are added/removed whilst being enumerated

### ISSUE THREAD

**Issue by kaidoe** [zeromq/czmq#1632]
Observed a null pointer exception due to polling for ziflist changes whilst adding/removing devices. According to MSDN GetAdapterAddresses may need to be called multiple times in cases where a device has been added/removed.

> Note that it is possible for the buffer size required for the IP_ADAPTER_ADDRESSES structures pointed to by the AdapterAddresses parameter to change between subsequent calls to the GetAdaptersAddresses function if an adapter address is added or removed.

From: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365915(v=vs.85).aspx

**Comment by bluca** [comment]
Could you please send a PR to fix it?

**Comment by kaidoe** [comment]
Yes, just in the process of doing so.. #1633

**Comment by bluca** [comment]
Great, thanks!

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/pull/1633
