### ISSUE TITLE
zbeacon crash on android

### ISSUE THREAD

**Issue by bbdb68** [zeromq/czmq#1641]
the beacon crash during the 'configure' call on android. Unfortunately I am not able to get a stack trace, I use czmq as a unity plugin 

The czmq 4.0.2 version works fine

**Comment by sappo** [comment]
Do you use the latest master? If so try to deactivate draft classes during configure `--enable-drafts=no`. The new draft class zsubproc currently does not compile on android which is about to be fixed.

**Comment by bbdb68** [comment]
I did use a recent master, but not the last one and android compilation went fine.

**Comment by sappo** [comment]
#1640 fixed the android issue on master. Maybe try it with latest master.

**Comment by bbdb68** [comment]
unfortunately the crash is still present with lastest master

**Comment by bluca** [comment]
Without the backtrace it's a bit hard, do you have at least a line number?

**Comment by bbdb68** [comment]
Here is a logcat output

03-16 10:40:36.006  2687  2792 F libc    : src/zbeacon.c:210: s_self_prepare_udp: assertion "rc == 0" failed
03-16 10:40:36.006  2687  2792 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 2792 (UnityMain)

looks like an ipv6 issue ( BTW  zsys_ipv6 returns 0)

**Comment by bluca** [comment]
if zsys_ipv6 is 0 then it cannot be an ipv6 issue, as all ipv6 interfaces are ignored
this is likely some issue with the network configuration, can you add some debugs?
printing first of all the getaddrinfo error with gai_strerror(rc) and then name and ziflist_address (iflist)

**Comment by bbdb68** [comment]
I'll try to do so, but fyi the same use case works just by dropping the 4.0.2 czmq.so instead of the one from master.

**Comment by bbdb68** [comment]
here is the output

03-16 13:57:48.773  5320  5400 W zsys    : name='wlan0'
03-16 13:57:48.773  5320  5400 W zsys    : address='192.168.0.102'
03-16 13:57:48.773  5320  5400 W zsys    : Invalid value for ai_flags

last line is the return from gai_sterror(rc)

**Comment by bluca** [comment]
hint.ai_flags = AI_NUMERICHOST | AI_V4MAPPED;

Looks like Android doesn't support AI_V4MAPPED:

http://stackoverflow.com/questions/39674147/getaddrinfo-on-android-returning-error-eai-badflags

**Comment by bbdb68** [comment]
I just traced it

 ai flag=2052

**Comment by bluca** [comment]
I'll ifdef it out when building for android

**Comment by bluca** [comment]
@bbdb68 could you please try again with this change:

```
--- a/src/zbeacon.c
+++ b/src/zbeacon.c
@@ -117,7 +117,10 @@ s_self_prepare_udp (self_t *self)
     struct addrinfo *send_to = NULL;
     struct addrinfo hint;
     memset (&hint, 0, sizeof(struct addrinfo));
-    hint.ai_flags = AI_NUMERICHOST | AI_V4MAPPED;
+    hint.ai_flags = AI_NUMERICHOST;
+#ifndef CZMQ_HAVE_ANDROID
+    hint.ai_flags |= AI_V4MAPPED;
+#endif
     hint.ai_socktype = SOCK_DGRAM;
     hint.ai_protocol = IPPROTO_UDP;
     hint.ai_family = zsys_ipv6 () ? AF_INET6 : AF_INET;
```

**Comment by bbdb68** [comment]
I just did it and it works :-) Thanks @bluca !

**Comment by bbdb68** [comment]
just let me test it end to end...

**Comment by bluca** [comment]
thanks, I'll prepare a PR meanwhile

**Comment by bbdb68** [comment]
end-to-end test OK :+1:

**Comment by sappo** [comment]
@bbdb68 it sounds like a neat setup you're using czmq for. If you can make the time somehow I really would love the hear more about your environment. Maybe as part of the README if it fits or as a blog post. Just an idea.
