### ISSUE TITLE
Build fail for msvc/vs2012 build

### ISSUE THREAD

**Issue by timwild** [zeromq/czmq#1646]
I was following the build instructions for Windows in the README. The libsodium build went without a hitch, libzmq went without a hitch.

Got to the czmq build and it exits with the following error:

Did not find libzmq, aborting.
Please clone from https://github.com/zeromq/libzmq.git, and then build.
*** ERROR, build terminated early: see build.log

I cannot find the build.log to find specific issues

However, when looking at the build.bat file I can see the following line: 

```
SET packages=
IF EXIST "..\..\..\..\libzmq\builds\msvc\vs2012\libzmq.import.props" (
    COPY /Y "..\..\..\..\libzmq\builds\msvc\vs2012\libzmq.import.props" . > %log%
    IF errorlevel 1 GOTO error
) ELSE (
    ECHO Did not find libzmq, aborting.
    ECHO Please clone from https://github.com/zeromq/libzmq.git, and then build.
    GOTO error
)
```

I've validated that the file exists on that specific path. I do have Visual Studio 2012 Enterprise installed. Any assistance is greatly appreciated.

**Comment by timwild** [comment]
I've actually corrected this. It only included a different file for the sodium.import.props.  

The libzmq.import.props didnt exist in the vs2012 folder. I tried copying the file from the vs2015 folder, but now the error has changed

Build finds the file but promptly dies here:

```
c:\czmq\builds\msvc\vs2012>build.bat
Building without uuid
Building without systemd
Building CZMQ... ()
Platform=x86
Configuration=DynDebug
*** ERROR, build terminated early: see build.log
```

I do see the Visual Studio .sln file.  When I open that I get:

```
C:\czmq\builds\msvc\vs2012\libczmq\libczmq.vcxproj : error  : Unable to read the project file "libczmq.vcxproj".
C:\czmq\builds\msvc\vs2012\libzmq.import.props(114,43): The project file could not be loaded. The 'div' start tag on line 113 position 10 does not match the end tag of 'option'. Line 114, position 43.
```

I had a few where it was mentioning the meta start tag doesnt match the end head tag.  I closed all the meta tags with ``` /> ```

After doing that, I'm getting these. I'm thinking there's something more serious going on as this was a generated file.

**Comment by timwild** [comment]
I did find the build file. I've attached the full copy here.

It looks like it's looking for a zsp directory, which does not exist.


[build.log.txt](https://github.com/zeromq/czmq/files/863111/build.log.txt)

**Comment by bluca** [comment]
@vyskocilm any idea? Some issue with how zproject handles the binary in the Windows stuff?

**Comment by vyskocilm** [comment]
Hi, unfortunately not, I have almost no experience in building software on
windows.

Dne 22. 3. 2017 23:47 napsal uživatel "Luca Boccassi" <
notifications@github.com>:

**Comment by timwild** [comment]
I've tried historical versions 3.0.0 and 3.0.1.  3.0.1 has the same exact issue. 3.0.0 doesnt compile; it cant find zmq.h even if I copy it into the include folder.

Figured I'd pass that along if it helps.

**Comment by mlodew** [comment]
These are issues I encountered as well. The first one is an error in the build.bat file for all versions of visual studio except for vs 2015. For example vs 2013 looks in the folder libzmq/builds/msvc/vs2013 for libzmq.import.props but this file is only in the libzmq/builds/msvc/vs2015 folder. This error is hard to fix since the build.bat files are automatically generated by zproject.
The second issue arises because the zsp project folder was missing in the vsXXXX folders. But I see that the folder was added 24 days ago and therefore it should work now. But then issue #1617 still exists. 
The only way, I was able to build czmq on Windows without problems was using cmake and some manual scripting. So after compiling libzmq and libsodium czmq can be compiled for example for vs2013 and x64:
```
set CZMQ_FOLDER=D:\github\czmq
set CZMQ_BUILDDIR=D:\github\czmq_build
SET ZEROMQ_DIR=D:\github\libzmq
SET SODIUM_DIR=D:\github\libsodium

SET CMAKE_GENERATOR=Visual Studio 12 2013
SET MSVCVERSION=v120
SET MSVCYEAR=vs2013
SET platform=x64
SET configuration=Release

if "%Platform%"=="x64" set "CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64"
SET ZEROMQ_INCLUDE_DIR=%ZEROMQ_DIR%\include
SET SODIUM_INCLUDE_DIR=%SODIUM_DIR%\src\libsodium\include
SET ZEROMQ_LIBRARY_DIR=%ZEROMQ_DIR%\bin\%Platform%\%Configuration%\%MSVCVERSION%\dynamic
copy "%ZEROMQ_LIBRARY_DIR%\libzmq.lib" "%ZEROMQ_LIBRARY_DIR%\zmq.lib"
SET SODIUM_LIBRARY_DIR=%SODIUM_DIR%\bin\%Platform%\%Configuration%\%MSVCVERSION%\dynamic

SET CZMQ_BUILDDIR=%CZMQ_BUILDDIR%_%MSVCVERSION%_%platform%_%configuration%_dynamic
md "%CZMQ_BUILDDIR%"
cd "%CZMQ_BUILDDIR%"
cmake -G "%CMAKE_GENERATOR%" -D CMAKE_INCLUDE_PATH="%ZEROMQ_INCLUDE_DIR%;%SODIUM_INCLUDE_DIR%" -D CMAKE_LIBRARY_PATH="%ZEROMQ_LIBRARY_DIR%;%SODIUM_LIBRARY_DIR%" -D CMAKE_C_FLAGS_RELEASE="/MT" -D CMAKE_CXX_FLAGS_RELEASE="/MT" -D CMAKE_C_FLAGS_DEBUG="/MTd" "%CZMQ_FOLDER%"
cd "%CZMQ_FOLDER%"
```
This is also the way, the CI tests for successful compilation.
