### ISSUE TITLE
Off-by-one error in zarmour causes corruption

### ISSUE THREAD

**Issue by donbowman** [zeromq/czmq#1656]
Using valgrind, i trips on this for some input cases [i'm not sure which ones offhand].
I am also getting corruptions in memory without it, so i do believe its correct.

specifically, s_base64_decode() I think the size needs +2 [null + expansion?].

The below diff fixes for me.

```
diff --git a/src/zarmour.c b/src/zarmour.c
index abb1004..3030a49 100644
--- a/src/zarmour.c 
+++ b/src/zarmour.c
@@ -164,7 +164,7 @@ s_base64_decode (const char *data, size_t *size, const char *alphabet, size_t li
     const byte *ceiling = (const byte *) (data + length);
 
     length -= linebreakchars;
-    *size = 3 * (length / 4) + ((length % 4)? length % 4 - 1 : 0) + 1;
+    *size = 3 * (length / 4) + ((length % 4)? length % 4 - 1 : 0) + 2;
     byte *bytes = (byte *) zmalloc (*size);
     if (!bytes)
         return NULL;

```

**Comment by bluca** [comment]
Would you be able to send a PR to fix it? Bonus points if you can change the unit tests to catch it too

**Comment by donbowman** [comment]
will do, i guess i should not be lazy

**Comment by donbowman** [comment]
https://github.com/zeromq/czmq/pull/1657
has been created.

I don't see an easy way to make a test case (since it needs either valgrind or to instrument the code to check the 1-byte overrun on the malloc)

**Comment by donbowman** [comment]
I have made a mistake in the PR, i will go back and spend more time on it.

**Comment by donbowman** [comment]
OK, the error is slightly different than i thought.
calling decode(encode(array)) does not return the same length.

If i pass in an array of 10 '0', I get back 14 'A' and '=='.
If i then run decode on this, I get a size of 11 back, 1 larger.

**Comment by donbowman** [comment]
This patch shows the error
diff --git a/src/zarmour.c b/src/zarmour.c
index 65cffcf..c218e75 100644
--- a/src/zarmour.c
+++ b/src/zarmour.c
@@ -930,6 +930,16 @@ zarmour_test (bool verbose)
     s_armour_test_long (self, test_data, 256, verbose);
 #endif
 
+    byte v[10];
+    memset(&v, 0, sizeof(v));
+    zarmour_set_mode(self, ZARMOUR_MODE_BASE64_STD);
+    char *enc = zarmour_encode(self, v, sizeof(v));
+    zchunk_t *zc = zarmour_decode(self, enc);
+    assert(zchunk_size(zc) == sizeof(v));
+    assert(!memcmp(zchunk_data(zc), v, sizeof(v)));
+    zchunk_destroy(&zc);
+    free(enc);
+
     zarmour_destroy (&self);
