### ISSUE TITLE
czmq doesn't compile on mingw32 due to redefinition of int32_t with vs2010

### ISSUE THREAD

**Issue by tnguyen-Alta** [zeromq/czmq#1668]
I am new to czmq. I have a problem as czmq built error C2371: 'int8_t' redefinition in czmq_prelude.h. I am using vs2010 to build czmq. My libzmq version is 4.1.1. Below is where the error indicates:

#   if (!defined (__MINGW32__) \
    || (defined (__MINGW32__) && defined (__IS_64BIT__)) \
    && !defined (ZMQ_DEFINED_STDINT))
    typedef __int8 int8_t;
    typedef __int16 int16_t;
    typedef __int32 int32_t;
    typedef __int64 int64_t;
    typedef unsigned __int8 uint8_t;    
    typedef unsigned __int16 uint16_t;
    typedef unsigned __int32 uint32_t;
    typedef unsigned __int64 uint64_t;
#   endif

**Comment by bluca** [comment]
The check specifically looks for mingw32 so it's a bit weird - check what ./configure is doing, if it can detect mingw32 correctly
