### ISSUE TITLE
s_zhashx_rehash() does not follow its documentation

### ISSUE THREAD

**Issue by jimklimov** [zeromq/czmq#1674]
According to comments for the `s_zhashx_rehash()` routine at
https://github.com/zeromq/czmq/blob/master/src/zhashx.c#L197
if returns -1 if memory errors occur. This is also inspected in e.g. zhash_insert a few lines below.

However, following https://github.com/zeromq/czmq/commit/bf2b1265d877a7406ce731fda7285c1b10b5ae9c this code is no longer returned, `assert`ing the pointer instead (which makes sense according to comments in that commit).

I am not sure what is the right way out from the discrepancy - amend the docs/comments (and checks for exit code), or fall back to runtime checks? In particular, are `assert`s guaranteed to crash on errors in production (non-debug) builds?

**Comment by bluca** [comment]
I would recommend fixing the docs, changing behaviour is never nice.
We do rely on asserts to do sanity checks, and we don't disable them in the builds. Nor do distributions, so it should be safe.

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/issues/1677
