### ISSUE TITLE
zgossip state machine has issues with reconnections.

### ISSUE THREAD

**Issue by JustinAzoff** [zeromq/czmq#1689]
Hi!

I've been working to track down an issue with how zgossip behaves after a crash.  I think I have tracked down the problem to an issue with how the state machine works after the binding side crashes.  This may also be an issue with the zproto templates in general and affect other things.

zgossip works fine if all processes are both binding and connecting to each other. On a crash the process that restarts will connect and send a HELLO.  However if the process that restarts is a BIND only process (part of a discovery service), the clients that CONNECT to it end up in an invalid state.

Reproducing this is tricky, but the minimal test case appears to be a server that BINDS and two or more clients that CONNECT to the server and PUBLISH a tuple.

* Start server
* Start both clients.  Verify that both tuples show up on the server and both clients.
* Kill and restart the server
* See that the server does not show the 2 original tuples
* Start a third client
* See that the two original clients do not see the tuple published by the new client.

After a re-connection the state machine gets out of sync.  The client thinks it is already connected but the server is still waiting for a hello.  If the client tries to publish a new tuple it will get an INVALID and then it will sync up again.  If the client never tries to publish a new tuple it will just sit there and never move to the connected state and never receive new tuples.

I think heartbeats could help here, but not without some changes as it appears that ping/pong are valid in any state and would not trigger an INVALID.  I think if ping/pong was enabled and changed to be only valid in the connected state then that would fix things.  I tried just having the client re-publish a tuple as a heartbeat, but since it's a duplicate tuple that is a NOOP.

Does that make sense?  I can try to come up with a patch that enables ping/pong for zgossip and makes it valid only in the connected state.. or maybe it needs a 2nd set of ping/pong events for the connected state so a state mismatch can be detected?

What made this a little tricky to track down is if I setup a topology of 2+ zgossip discovery nodes that bind/connect to each other, I can connect clients to them and kill/restart one at a time and clients are still happy.  As long as I don't kill all of them at the same time. If all are restarted at the same time then clients end up in the same state.

**Comment by JustinAzoff** [comment]
Possibly related, I also want to see about implementing the support for ttl on PUBLISH.  That may require having the clients re-publish the tuples at regular intervals.  If the clients were to do that after reconnecting then they would trigger an INVALID and that would help solve this problem too.

**Comment by bluca** [comment]
Could you please share the code for the minimal test case you have via gist/pastebin?
