### ISSUE TITLE
Bufferoverflow  if_indextoname on Windows

### ISSUE THREAD

**Issue by diorcety** [zeromq/czmq#1700]
When investigating on #1699, I fall on this issue
https://github.com/zeromq/czmq/blob/master/src/zsys.c#L1002
In the doc:
"The if_indextoname() function returns the name of the network interface corresponding to the interface index ifindex. The name is placed in the buffer pointed to by ifname. The buffer must allow for the storage of at least IF_NAMESIZE bytes."
Sure by default IF_NAMESIZE is set to 32 on linux, but on Windows it's 256. We should use the IF_NAMESIZE definition.

**Comment by bluca** [comment]
Good catch. Can you send a PR for it?
