### ISSUE TITLE
Man page for zsock APIs like zsock_new()

### ISSUE THREAD

**Issue by nayabbashasayed** [zeromq/czmq#1706]
Current 0MQ version is 4.2.1

I've been reading [zguide](http://zguide.zeromq.org/page:all) (Written for v3.2).

The latest [C examples](https://github.com/booksbyus/zguide/tree/master/examples/C) won't work with v4.2.1.

Since **zctx** and so many APIs are deprecated with 4.0, I've decided to use version greater then 4.0. But where do I find the man pages for v4.2.1 APIs? I could only found the page for classes like [zsock class](http://czmq.zeromq.org/czmq4-0:zsock).

**Comment by bluca** [comment]
There are 2 different libraries here.

The core library, libzmq, is version 4.2.1.

This is the C bindings, which is called CZMQ, and it's at version 4.0.2.

These are the CZMQ manpages:

http://czmq.zeromq.org/czmq4-0:_start

These are the libzmq manpages:

http://api.zeromq.org/

**Comment by nayabbashasayed** [comment]
Thanks..
