### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by benghopy** [zeromq/czmq#1709]
**gcc version: the gcc path value is /opt/buildroot-gcc463/usr/bin**
Using built-in specs.
COLLECT_GCC=mipsel-linux-gcc
COLLECT_LTO_WRAPPER=/opt/buildroot-gcc463/usr/bin/../libexec/gcc/mipsel-buildroot-linux-uclibc/4.6.4/lto-wrapper
Target: mipsel-buildroot-linux-uclibc
Configured with: ./configure --prefix=/opt/buildroot-gcc464_2013/usr --sysconfdir=/opt/buildroot-gcc464_2013/etc --enable-shared --disable-static --disable-gtk-doc --disable-doc --disable-docs --disable-documentation --with-xmlto=no --with-fop=no --target=mipsel-buildroot-linux-uclibc --with-sysroot=/opt/buildroot-gcc464_2013/usr/mipsel-buildroot-linux-uclibc/sysroot --disable-__cxa_atexit --with-gnu-ld --disable-libssp --disable-multilib --with-gmp=/opt/buildroot-gcc464_2013/usr --with-mpfr=/opt/buildroot-gcc464_2013/usr --enable-target-optspace --enable-tls --disable-libmudflap --enable-threads --with-mpc=/opt/buildroot-gcc464_2013/usr --disable-decimal-float --with-arch=mips32r2 --with-abi=32 --with-pkgversion='Buildroot 2013.11' --with-bugurl=http://bugs.buildroot.net/ --enable-languages=c,c++ --with-build-time-tools=/opt/buildroot-gcc464_2013/usr/mipsel-buildroot-linux-uclibc/bin --disable-libgomp
Thread model: posix
gcc version 4.6.4 (Buildroot 2013.11)

**The make error information:**
/bin/sed: can't read /opt/buildroot-gcc464_2013/usr/mipsel-buildroot-linux-uclibc/lib/libstdc++.la: No such file or directory
libtool: link: `/opt/buildroot-gcc464_2013/usr/mipsel-buildroot-linux-uclibc/lib/libstdc++.la' is not a valid libtool archive

I see the libczmq.la file:
~The name that we can dlopen(3).
dlname='libczmq.so.3'

~ Names of this library.
library_names='libczmq.so.3.0.0 libczmq.so.3 libczmq.so'

~ The name of the static archive.
old_library='libczmq.a'

~ Linker flags that can not go in dependency_libs.
inherited_linker_flags=''

~Libraries that this one depends upon.
dependency_libs=' -L/usr/lib /usr/lib/libzmq.la -lrt -lpthread /opt/buildroot-gcc464_2013/usr/mipsel-buildroot-linux-uclibc/lib/libstdc++.la'

**why the path is /opt/buildroot-gcc464_2013/usr/mipsel-buildroot-linux-uclibc/lib/ not /opt/buildroot-gcc463/usr/mipsel-buildroot-linux-uclibc/lib/ ?**

**Comment by bluca** [comment]
That's the path that it's been passed via the --prefix variable as the log says:
```
Configured with: ./configure --prefix=/opt/buildroot-gcc464_2013/usr
```

**Comment by benghopy** [comment]
But this is the toolchain's configure logs, I just set the czmq's configure --prefix=~/install, but in the same configure at ZeroMQ, it is '/opt/buildroot-gcc463/usr/bin/../lib/gcc/mipsel-buildroot-linux-uclibc/4.6.4/../../../../mipsel-buildroot-linux-uclibc/lib/libstdc++.la'?

**Comment by benghopy** [comment]
I fixed this make error: using a soft link /opt/buildroot-gcc464_2013 to /opt/buildroot-gcc463

**Comment by vyskocilm** [comment]
I am closing this - it looks workaround was found. Feel free to reopen if needed @benghopy
