### ISSUE TITLE
No build for vs2017

### ISSUE THREAD

**Issue by aworldnervelink** [zeromq/czmq#1717]
libzmq provides a build for vs2017, but czmq does not. I am not able to build the project using the latest Visual Studio Community 2017.

**Comment by bluca** [comment]
Would you be able to send a PR to add it?

**Comment by aworldnervelink** [comment]
I have no familiarity with the project and in fact I have not worked in C for many years… building this has been a challenge. If I can get some hints about what would need to change in the new subdirectory I will take a shot at it, but I can’t guarantee very good results. :)

**Comment by bluca** [comment]
All the VS files are autogenerated from zproject:

https://github.com/zeromq/zproject/blob/master/zproject_vs20xx.gsl

So it should be just a matter of filling the gaps, copying what is done for previous versions and adjust as needed.

**Comment by aworldnervelink** [comment]
Hmmm... I'll continue looking at this but without an understanding of how the template system works I don't know if I'll have any success. I also tried to install VS2015 but that did not work properly so I still have no way to build CZMQ.

**Comment by sleepndevelop** [comment]
Hello,
i have the same issue with VS2017 Community.

I've tried editing the msvc/vs2015/build.bat file
replacing all occurences of "vs2015" with "vs2017" and replacing
SET version=14
with
SET version=15
and i have run vs2015/build.bat

But then when i have tried to compile the solution with VS17 i've got many compile errors, for example   ztrie_destroy_data_fn and ztrie_t identifiers are not defined.

Where are those identifiers defined ? Maybe it's just a matter of including additional headers.

@aworldnervelink You have tried building with VS2015 and you got the same compile errors as me?

**Comment by sleepndevelop** [comment]
I also have CMake and MingW32 installed, should i try the Cmake way?

**Comment by aworldnervelink** [comment]
I was able to build libzmq with VS2015 and I did not see any errors. I didn’t get anywhere with czmq.

Now I am trying to build both with MinGW and also having trouble there…

**Comment by sappo** [comment]
Any contribution to improve msvc and mingw are welcome. Maybe try to adopt the libzmq msvc scripts for czmq.

**Comment by sleepndevelop** [comment]
@aworldnervelink Try following the same procedure as i did with VS2017 , i am almost sure i used the VS Developer command prompt and not standard CMD prompt.

After you managed to generate the VS solution, before compiling it add this #define on top of czmq_library.h file:
#define CZMQ_BUILD_DRAFT_API

This avoids all those compile errors i got saying it could not find identifier definitions ( zargs_t , etc. ... )

I have only compiled the libczmq.lib static library, did not try the other projects in the solution

**Comment by aworldnervelink** [comment]
*sigh* My VS2017 cannot find its own include files (e.g. vcruntime.h). Uninstalling/reinstalling didn’t fix it. I’ll have to keep investigating over the weekend.

**Comment by sleepndevelop** [comment]
Does it happen with a different solution as well? 
Try creating a non-blank Win32 or console project and compile it.

I guess you messed up the include directories in the Project settings

**Comment by aworldnervelink** [comment]
I finally solved the include problem… I had to go into every .vcxproj file and change <PlatformToolset> to 141. This apparently got it looking in the right place.

Now I am getting a bit of a build and then a failure:

unresolved external symbol _czmq_private_selftest

Still digging…

**Comment by sleepndevelop** [comment]
At least can you build the licbczmq project?
That's the only one that matters if you need just the static library.
The other projects in the solution are not that important

**Comment by aworldnervelink** [comment]
No, it failed before that library was built. Maybe I can cut out all of the other projects and just build the static library?

**Comment by aworldnervelink** [comment]
I removed all of the other projects and configurations, leaving only the static debug and release czmq. The build produced a .lib! That only took three weeks.

I will try linking this into my project over the weekend and see if it works. Thanks for the suggestions!

**Comment by sleepndevelop** [comment]
It was not necessary to remove the others. From the solution explorer window you see the list of projects in it, just right-click on libczmq than from the dropdown menu choose "Only libczmq project" => "Compile only libczmq" or something like that. Then do the same for linking it
