### ISSUE TITLE
zsock fails a test sometimes

### ISSUE THREAD

**Issue by jimklimov** [zeromq/czmq#1726]
From travis,

````
21: czmq_selftest: /home/travis/build/jimklimov/czmq/src/zsock.c:2097: zsock_test: Assertion `server' failed.
````

Could this be yet another timing-related issue?

**Comment by bluca** [comment]
```
   2096     server = zsock_new_server ("tcp://127.0.0.1:5561");
   2097     assert (server);
```

My best guess is that hard-coded port is already used - should be switched to 127.0.0.1:* and get_endpoint like I did a while ago to all libzmq tests. Will take care of that.
