### ISSUE TITLE
propagate malloc failures up the call stack (optionally)

### ISSUE THREAD

**Issue by garlick** [zeromq/czmq#1749]
In #1193 it looks like a case was made for replacing ENOMEM propagation in czmq with assertions, and this idiom is now reflected in the code.  It's arguable that this is  _not_ correct behavior for a library, e.g. see

https://stackoverflow.com/questions/9050616/c-api-design-what-to-do-when-malloc-returns-null

Asserting in the library for a transient outside condition presumes too much about the application and the cost/benefit of attempting recovery, even if in some cases it won't succeed.

One approach to changing this behavior in czmq would be to
1) ensure all allocations (including strdup) use the internal `zmalloc()` function.  The current `zmalloc()` implementation asserts internally on failure (unless some #defines, but these are not normally used?)
2) replace the (separate) assertions found everywhere that `zmalloc()` return value is non-NULL, with code that tests for NULL and unwinds and propagates the error to the caller.
3) provide a function for the user to register their own `zmalloc()` replacement

As noted in #1193 this adds some complexity, and takes extra effort to maintain clarity, but IMHO this is just the cost of doing business in C.  (And sorry if this is dredging up an old, settled argument - I wasn't around for those)

**Comment by bluca** [comment]
I'm afraid that is a bit settled at this point :-)

Pieter felt quite strongly about it, and rightly so IMHO: once you are out of memory, in a library that needs to handle multi-message protocols, managing to react safely is very very very hard, because silent or ignored inconsistencies are behind the corner.

Even if the vast majority of the cases could be somewhat handled, the small percentage that slips through will be enough to make the library unreliable, which I think it's worse.

This is especially true for any asynchronous activity, like an actor or like the libzmq I/O thread. You can't return an error from the background thread - so libzmq will assert anyway when out of memory.

**Comment by garlick** [comment]
Thanks @bluca.  Yeah, I understand the issue of diminishing returns on recovering from malloc errors, although in some cases more than others.  For example, recovering from exceeding a memory limit in a single threaded process may be less fraught than recovering in a multi-threaded process, or from a Linux system oom.

This issue is not really about libzmq.  czmq includes some useful classes like hashes and lists that are independent of libzmq and don't necessarily imply the I/O thread.   In a large project that has czmq (and libzmq) as a dependency, it's natural to use those classes as needed, and I'm finding we've done that in places where we don't want to assert on ENOMEM, such as in _our_ libraries.

If this ship has sailed, it's not a huge problem to find other hash, list, etc implementations, but the behavior does seem to limit the usefulness of czmq unnecessarily, so I thought it was worth asking.  Feel free to close this if the proposed changes would push czmq somewhere it was not intended to go.

**Comment by bluca** [comment]
I hadn't considered those classes, was mainly thinking about the networking parts.

If you can implement a recovery, strictly for classes that have a synchronous and single-threaded API like the data structures, and in a way that is 100% safe, I think it could be acceptable. (EG: try to add new item to list, return error if can't allocate like for other errors)

**Comment by bluca** [comment]
IOW, if you have a PR ready, feel free to send it :-)

**Comment by garlick** [comment]
Thanks, not yet, just testing the waters.

**Comment by bluca** [comment]
@garlick any updates on this? Were you able to test your changes successfully?

**Comment by garlick** [comment]
Apologies, other priorities took over.  I'm fine with closing this issue and reopening when I have time if you prefer to have it out of the way in the meanwhile.

**Comment by bluca** [comment]
No don't worry, it's fine to keep it open since it's unsolved, otherwise I'll forget
