### ISSUE TITLE
[Win10 x64] Assertion failed: Successful WSASTARTUP not yet performed

### ISSUE THREAD

**Issue by myd7349** [zeromq/czmq#1751]
I encountered an Assertion failed error on exit while czmq is doing clearing internally.

Environment:
OS: Windows 10 Home Edition(version 10.0.15063) 64bit
Visual Studio: vs2010 and vs2017
libzmq: v4.2.2(7283574c)
czmq: v4.0.2( c545b4f7)
platform.h for czmq:
```c
#define CZMQ_HAVE_WINDOWS 
#define HAVE_LIBZMQ 
#undef HAVE_UUID
#undef HAVE_SYSTEMD
#undef HAVE_LZ4
//  Provide draft classes and methods
#define CZMQ_BUILD_DRAFT_API 
```

Both `libzmq` and `czmq` are built in `Win32`, `Debug` mode.

Code snippet for reproduce this issue:
```c
#include <czmq.h>

int main()
{
    zsock_t *sock = zsock_new(ZMQ_REQ);
    zsock_destroy(&sock);

    return 0;
}
```
Code above does nothing but creates a  czmq 4.x socket and then closes it. I tested it in vs2010 and vs2017. When this program exits, the program crashes:
>Unhandled exception at 0x7507b802 in test.exe: 0x40000015:  %hs.

and I saw an Assertion error in the console:
> Assertion failed: Successful WSASTARTUP not yet performed (E:\dev\ZeroMQ\build\libzmq\src\signaler.cpp:192)

Any advice? Thanks!

**Comment by bluca** [comment]
Is the library built as a dll?
If so send to Windows limitations you need to call zsys_shutdown manually before exiting. See:

https://github.com/zeromq/czmq/issues/989
https://github.com/zeromq/czmq/pull/1608

**Comment by myd7349** [comment]
Yes, I build both libzmq and czmq as dll.

Thanks! @bluca It works. I should search the issue much more carefully.
Nice day! :)
