### ISSUE TITLE
a code mistake in zloop_set_nonstop

### ISSUE THREAD

**Issue by Crossverse** [zeromq/czmq#1752]
https://github.com/zeromq/czmq/blob/c545b4f7a198647bab0148aea6e5cc289e4167cb/src/zloop.c#L681
Must be
self->nonstop = nonstop;

**Comment by bluca** [comment]
Same for zpoller. Could you please send a PR to fix them?

**Comment by Crossverse** [comment]
Sorry. I am a newbie.  What is a PR?

**Comment by c-rack** [comment]
@Crossverse a [Pull Request](https://help.github.com/articles/about-pull-requests/)

**Comment by bluca** [comment]
Fixed by #1753
