### ISSUE TITLE
Travis occasionally fails zproxy

### ISSUE THREAD

**Issue by jimklimov** [zeromq/czmq#1756]
````
 * zproxy: E: (czmq_selftest) 17-09-04 21:48:33 zproxy: invalid endpoints 'tcp://127.0.0.1:61571'
lt-czmq_selftest: ../../../czmq-master/src/zproxy.c:200: s_self_configure: Assertion `*sock_p' failed.
````

**Comment by bluca** [comment]
That's a strange one, maybe this needs an update? https://github.com/zeromq/czmq/blob/master/src/zproxy.c#L94

**Comment by yuanhuihe** [comment]
I faced the same issue:
`E: 18-11-16 19:10:27 zproxy: invalid endpoints 'tcp://127.0.0.1:8013'
E: 18-11-16 19:10:27 zproxy: invalid endpoints 'inproc://alice_channel:5601'
E: 18-11-16 19:10:27 zproxy: invalid endpoints 'inproc://alice_channel:5602'
E: 18-11-16 19:10:27 zproxy: invalid endpoints 'inproc://alice_channel:5603'
`
