### ISSUE TITLE
zloop_start stop intermidiately

### ISSUE THREAD

**Issue by tianchao-haohan** [zeromq/czmq#1761]
Here is the usage of zloop:
```
   /* Create zloop reactor */
    loop = zloop_new ();
    if (loop == NULL) {
        LOGE ("Create zloop error.\n");
        ret = -1;
        goto stopServices;
    }
    zloop_set_verbose (loop, True);

    /* Init pollItem */
    pollItem.socket = getTaskStatusRecvSock ();
    pollItem.fd = 0;
    pollItem.events = ZMQ_POLLIN;
    /* Register poll item 1 */
    ret = zloop_poller (loop, &pollItem, taskStatusHandler, NULL);
    if (ret < 0) {
        LOGE ("Register pollItem for task status handle error.\n");
        ret = -1;
        goto destroyZloop;
    }

    /* Start zloop */
    zloop_set_nonstop (loop, true);
    ret = zloop_start (loop);
    if (ret)
        LOGE ("nTagService get error.\n");
```
zloop verbose: 
```
D: 17-09-17 21:47:05 zloop: register PULL poller (0xf43e00, 0)
D: 17-09-17 21:47:05 zloop polling for 3600000 msec
D: 17-09-17 21:47:05 zloop: interrupted
```
Definiton of TaskStatusRecvSock:
  ```
  zmqHubIntance->taskStatusRecvSock = zsock_new (ZMQ_PULL);
    if (zmqHubIntance->taskStatusRecvSock == NULL) {
        LOGE ("Create taskStatusRecvSock error.\n");
        goto freeZmqHubInstance;
    }
    ret = zsock_bind (zmqHubIntance->taskStatusRecvSock,
                        "inproc://taskStatusExchangeChannel");
    if (ret < 0) {
        LOGE ("Bind taskStatusRecvSock to %s error.\n",
              "inproc://taskStatusExchangeChannel");
        goto freeZmqHubInstance;
    }
```
version:
	libczmq.so.4 => /lib64/libczmq.so.4 (0x00007f2e06139000)
	libzmq.so.5 => /lib64/libzmq.so.5 (0x00007f2e04a17000)
Both of czmq and zeromq are compiled from the source code, which are cloned from latest version.

**Comment by bluca** [comment]
zloop_poller uses a zmq_pollitem_t which takes libzmq sockets, not czmq sockets.

Use zloop_reader with czmq sockets instead. To get the libzmq socket out of a zsock, use zsock_resolve().

**Comment by bluca** [comment]
No problem

**Comment by neel-parikh** [comment]
Hi @bluca 

We use
ZMQ - 4.2.0
CZMQ - 3.0.2
We create sockets using zsocket_new which is CZMQ API and zloop_poller along with it. Does this apply to all the versions or this is a change done recently.

Thanks in advance.

**Comment by bluca** [comment]
No, zsocket can be used directly.

**Comment by neel-parikh** [comment]
Ok great, so this doesn't apply to us.
Thanks for your quick response.

**Comment by bankegg1** [comment]
> zloop_poller uses a zmq_pollitem_t which takes libzmq sockets, not czmq sockets.
> 
> Use zloop_reader with czmq sockets instead. To get the libzmq socket out of a zsock, use zsock_resolve().

thanks brother, i think it for three days and look at the czmq soure , also can't Fix bugs，just your one sentence solves the bug
