### ISSUE TITLE
Problem: Including czmq.h on OpenBSD fails because uint isn't defined

### ISSUE THREAD

**Issue by Vaelatern** [zeromq/czmq#1765]
Specifically in `zrex.h`, there is one use of `uint`.

**Comment by bluca** [comment]
Sounds like there's a fix needed here:

https://github.com/zeromq/czmq/blob/master/include/czmq_prelude.h#L598

Could you please send a PR?

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/pull/1767
