### ISSUE TITLE
Build failed on Ubuntu 16

### ISSUE THREAD

**Issue by Panchatcharam** [zeromq/czmq#1766]
I would like to build czmq on Ubuntu 16 to use that with libcurve. I followed the steps as indicated in the README.md and tried building the czmq but the czmq self-test  fails with following message,

```
Running czmq selftests...
 * zactor: OK
 * zarmour: OK
 * zcert: OK
 * zcertstore: OK
 * zchunk: OK
 * zclock: OK
 * zconfig: OK
 * zdigest: OK
 * zdir: OK
 * zdir_patch: OK
 * zfile: OK
 * zframe: OK
 * zhash: OK
 * zhashx: OK
 * ziflist: OK
 * zlist: OK
 * zlistx: OK
 * zloop: OK
 * zmsg: OK
 * zpoller: OK
 * zsock: OK
 * zsock_option: OK
 * zstr: OK
 * zsys: OK
 * zuuid: OK
Assertion failed: zap_required() (src/plain_server.cpp:50)
 * zauth: Makefile:2255: recipe for target 'check-local' failed
make[2]: *** [check-local] Aborted (core dumped)
make[2]: Leaving directory '/home/developer/work/zeroMQ/czmq'
Makefile:2042: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/developer/work/zeroMQ/czmq'
Makefile:1599: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```
Please advise what I'm missing here and how to get rid of this issue.
I appreciate your help.

Thanks,
Panch

**Comment by jimklimov** [comment]
Just in case: can you retry the build-test a few times? To see if it is an intermittent error, or a reproducible one? There were a few race/contention issues fixed in tests recently - maybe that's another among them?

**Comment by Panchatcharam** [comment]
I did run it repeatedly for fairly about 10 times but that did not help. Could you tell whether you want me to check for any build dependency on my build machine?

**Comment by bluca** [comment]
Instead of building from scratch, use the pre-built binary packages from Ubuntu:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Agit-stable&package=libczmq-dev

**Comment by Panchatcharam** [comment]
I'm seeing my sample program built with the Master branch of czmq is working fine despite the `make check` failed for `zatuh`. I would like to stay with the latest version of `czmq`. What's the version of the pre-built library?

**Comment by bluca** [comment]
The previous link always has the latest commit, this one always has the latest release: https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Arelease-stable&package=libczmq-dev

**Comment by antozz** [comment]
I got the following message on my phone, android 7.1.1, termux:
Running czmq selftests...
 * zactor: OK
 * zarmour: OK
 * zcert: OK
 * zcertstore: OK
 * zchunk: OK
 * zclock: OK
 * zconfig: OK
 * zdigest: OK
 * zdir: OK
 * zdir_patch: OK
 * zfile: OK
 * zframe: OK
 * zhash: OK
 * zhashx: OK
 * ziflist: OK
 * zlist: OK
 * zlistx: OK
 * zloop: OK
 * zmsg: OK
 * zpoller: OK
 * zsock: OK
* zsock: OK
 * zsock_option: OK
 * zstr: OK
 * zsys: OK
 * zuuid: OK
Assertion failed: zap_required() (src/plain_server.cpp:50)
make[2]: *** [Makefile:2254: check-local] Aborted
make[2]: Leaving directory '/data/data/com.termux/files/home/projects/czmq2'
make[1]: *** [Makefile:2042: check-am] Error 2
make[1]: Leaving directory '/data/data/com.termux/files/home/projects/czmq2'
make: *** [Makefile:1598: check-recursive] Error 1

**Comment by bluca** [comment]
Known issue: https://github.com/zeromq/libzmq/issues/2762
