### ISSUE TITLE
stat windows XP visual c++

### ISSUE THREAD

**Issue by diorcety** [zeromq/czmq#1773]
If you want to support windows XP with the new visual c++ version you may want to a work around with this issue https://stackoverflow.com/questions/32452777/visual-c-2015-express-stat-not-working-on-windows-xp . I fall on it with malamute which usez zconfig. Compiled using Visual C++ 2014 v140_xp. Zfile get a 0 length file length. I use a fall back méthode using ftell and fseek in ordre to get the file size.

**Comment by bluca** [comment]
is there a change to do here?

**Comment by diorcety** [comment]
We can put a fallback:
https://github.com/diorcety/czmq/commit/54cc781e6ef2f1a67d472ea05010ee61f2c94a7a

**Comment by bluca** [comment]
Could you please send a PR?

**Comment by diorcety** [comment]
#1774

**Comment by bluca** [comment]
Thanks!
