### ISSUE TITLE
zfile.c -- E0167 argument of type "TCHAR *" is incompatible with parameter of type "const char *"

### ISSUE THREAD

**Issue by sgluss** [zeromq/czmq#1785]
this error is occurring in Windows 10, Visual Studio 2017 targeting x64 with platform toolset 141

error occurs at line 147 in zfile.c:
`self->fullname = strdup (szTempFileName);`

I was able to hack-fix it by adding a cast to szTempFileName:
`self->fullname = strdup ((char*)szTempFileName);`

this enables the build to succeed, but is definitely a banana-in-the-differential type fix. What do you guys think?

**Comment by vyskocilm** [comment]
Hi,

Does make check work?  I don't know a lot about windows programming, but it
looks fine to me. Can you send the pull request?

Dne 10. 11. 2017 6:37 odpoledne napsal uživatel "Samuel Gluss" <
notifications@github.com>:

**Comment by twhittock** [comment]
Perhaps you have somehow enabled wide-char support with the UNICODE define or in the project settings, and converted the standard library calls to wide-char versions. If so, the cast would cause issues.

**Comment by sgluss** [comment]
@vyskocilm : ran the tests, all of them pass:
`
C:\czmq\czmq\builds\msvc\vs2015\x64\DebugDEXE>czmq_selftest.exe
Running czmq selftests...
...
Tests passed OK
`
I'll prepare a PR

@twhittock I already experimented a bit with the project's char settings, I'll try experimenting with it some more just be be sure I was thorough

**Comment by sgluss** [comment]
I tried adjusting the `Character Set` settings in the libczmq project to no avail... without the cast, I get the error no matter what I set. Note the inherited preprocessor settings though, there's unicode right there! 
![libczmqunicodeinpreprocessor](https://user-images.githubusercontent.com/12822580/32692448-1909c586-c6cd-11e7-84cb-0c5cbb3ccc5d.png)
I'll keep digging and see if this is the cause of the problem, any other insights would be great!

**Comment by evoskuil** [comment]
TCHAR macros should not be used in a library that works almost with char. I proposed converting the library to UTF8 Everywhere, but that is a large task. Casting is not a solution.

**Comment by AntonBarwald** [comment]
@evoskuil I guess this is not a "solution/workaround" either? 
```
wcstombs(self->fullname, szTempFileName, MAX_PATH);
```

**Comment by evoskuil** [comment]
Correct, it is not. This will fail to compile in the case where TCHAR compiles as char and may be unsafe (length assumptions). The string should either be obtained using an explicit ANSI/MBCS or UNICIDE API (vs. TCHAR), and if the latter, converted. These are all sort of hacky solutions though. The code may assume char is UTF-8, which is not the case in the Windows builds.

**Comment by evoskuil** [comment]
[Issue 994](https://github.com/zeromq/czmq/issues/994) explains the core issue in more detail.

**Comment by bluca** [comment]
Fixed by: https://github.com/zeromq/czmq/pull/1793

**Comment by sgluss** [comment]
just tested the new code, everything builds fine and the tests pass. Thanks guys!

![Alt Text]( https://media2.giphy.com/media/iiS84hOJXh1Pq/giphy.gif )
