### ISSUE TITLE
Problem: incorrect printf type specifier for VC++.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#1790]
The [following](https://github.com/zeromq/czmq/blob/master/src/ztrie.c#L620-L621) line is incorrect in VC++ builds:

```c
            printf ("%s (params: %zu, endpoint: %s, type: %d)\n",
                self->token, self->parameter_count, is_endpoint, self->token_type);
```
and produces the compiler warning:
```
src\ztrie.c(621): warning C4313: 'printf'  : '%d' in format string conflicts with argument 3 of type 'char *'
```
The "z" type specifier is [reserved for string and not valid for integers](https://msdn.microsoft.com/en-us/library/tcxf1dw6(v=vs.140).aspx). The warning appears to be a little off.

**Comment by bluca** [comment]
The upper case Z is for strings, it looks like Microsoft does not support the lower case one, from that page:

>  The hh, j, z, and t length prefixes are not supported.
