### ISSUE TITLE
Some deprecated functions are not marked as such

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1795]
I noticed something strange while testing the next version of [czmq-ffi-gen](https://github.com/paddor/czmq-ffi-gen) on CI. I test stable version (4.0.2, with drafts=no) and HEAD with drafts=yes. The tests for the stable version have stopped working because `zsock_hwm()` is not part of 4.0.2. The generated Ruby FFI binding would handle this gracefully, if the method was marked DRAFT.

I verified it on my MacBook by compiling 4.0.2 without drafts and running the tests of the recently generated Ruby binding:

```
FFI::NotFoundError:
  Function 'zsock_hwm' not found in [/usr/local/lib/libczmq.dylib]
# /Users/paddor/.gem/ruby/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:275:in `attach_function'
# ./lib/czmq-ffi-gen/czmq/ffi.rb:1496:in `<module:FFI>'
# ./lib/czmq-ffi-gen/czmq/ffi.rb:10:in `<module:CZMQ>'
# ./lib/czmq-ffi-gen/czmq/ffi.rb:9:in `<top (required)>'
# ./lib/czmq-ffi-gen.rb:2:in `require_relative'
# ./lib/czmq-ffi-gen.rb:2:in `<top (required)>'
# ./spec/spec_helper.rb:3:in `require_relative'
# ./spec/spec_helper.rb:3:in `<top (required)>'
# ./spec/czmq-ffi-gen/czmq/ffi_spec.rb:1:in `require_relative'
# ./spec/czmq-ffi-gen/czmq/ffi_spec.rb:1:in `<top (required)>'
```

Am I missing something?

**Comment by bluca** [comment]
zsock_hwm is for versions of libzmq between 2 and 3 - it was removed in version 4.

I re-did how the generated socket options work with this PR: https://github.com/zeromq/czmq/pull/1613

The problem was that the public API changed depending on which version of libzmq you were building against, which is bad.

So now the symbols are always defined - but generate an error when used agains the wrong version of libzmq.

So that's why in version 4.0.2 zsock_hwm is not available - I guess you are building against a modern version of libzmq and hence it's compiled out. That's what I was trying to fix :-)

**Comment by paddor** [comment]
I'm sorry, I don't fully understand. If all symbols (function names? like in `nm -G`) are defined, and they're just no-ops if ZMQ doesn't support them, why is there an error?

Are you saying it's possible to define all symbols and still make it fail while FFI (dlopen?) is trying to attach those functions?

Thanks.

**Comment by bluca** [comment]
What I mean is that when you build CZMQ 4.0.2, zsock_hwm won't exist, so it will fail to load it. That's because the change I pointed out was not there in 4.0.2.
I'm not sure how that binding works - but if you are generating/building it agains the latest master, zsock_hwm will be "added", but then it will fail like that when linked against CZMQ 4.0.2.

**Comment by paddor** [comment]
The binding (FFI boilerplate) is generated by zproject_ruby.gsl of zproject and packaged into czmq-ffi-gen (CZTop builds on top of that to make it feel like Ruby). The binding generator works by reading the API files of CZMQ and generating the FFI boilerplate. 

Right now I have both ZMQ HEAD and CZMQ HEAD installed (using `brew`). The binding generator doesn't generate anything different from what is already in the bindings/ruby/ directory of the CZMQ repository, and thus, the specs of czmq-ffi-gen still don't work.

Is there a way for me to detect the situation around `zsock_hwm()` in the Ruby binding generator to handle attaching that function gracefully? As far as I can see, the information `major_removed = '3'` is only defined in src/sockopts.xml, but not included into the generated api/zsock_option.api file.

**Comment by paddor** [comment]
Or is there a way to close the gap between what the API files define and what CZMQ actually compiles into the shared object? In my opinion, this defies the purpose of the API files.

**Comment by bluca** [comment]
But there is no zsock_hwm in version 4.0.2: https://github.com/zeromq/czmq/blob/v4.0.2/api/zsock_option.api
So if you are generating against that version, then it won't be there?

**Comment by paddor** [comment]
I guess that would be one solution, although it would make impossible to use any unreleased API changes and additions after 4.0.2.

Just for your understanding: The bindings are regenerated periodically by CZMQ developers, and also checked into the CZMQ repo. That's exactly what czmq-ffi-gen is based on; it even uses the CZMQ repo as a Git submodule to get access to those generated Ruby binding files, and symlinks them to [lib/czmq-ffi-gen/czmq/](https://github.com/paddor/czmq-ffi-gen/blob/master/lib/czmq-ffi-gen/czmq)).

If I really was to release czmq-ffi-gen for unreleased CZMQ API, I could just make sure that the specs on CI only run against CZMQ HEAD versions. But as soon as CZMQ's next version is released, I'm gonna be in the same situation again. The generated bindings will contain `zsock_hwm()`, but the actually released CZMQ won't. 

I think I see the problem now: The `state` attribute for zsock options is only set for DRAFT options, but not for DEPRECATED options (as per [C4.2](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)). I'll try to come up with a change for src/zsock_option.gsl so deprecated APIs are marked as such. After that, the state will be read by zproject_class_api.gsl of Zproject and thus it'll be easy for the Ruby binding generator to handle deprecated options gracefully.

**Comment by paddor** [comment]
Okay, I have something that works for the options. It simply marks the options, which have the attribute `major_removed` set, with `state = "deprecated"`. The existing Ruby binding generator actually handles that already (meaning it will generate code that allows the function attachment to fail). So far, so good.

But here's the next obstacle: It seems like some zsys functions (at least `zsys_set_thread_sched_policy()`) also don't exist in a recent CZMQ library. The documentation of 4.0.2, 4.0.3, and 4.0.4 master also don't mention anything about it. May I assume that that/those functions are fairly new and thus should be marked as DRAFT? The zsys.api file is all new (introduced in June 2017), so maybe that's why it's containing a few mistakes.

**Comment by paddor** [comment]
Yeah, turns out it's only `zsys_set_thread_sched_policy()` and `zsys_set_thread_priority()`. Now czmq-ffi-gen's test suite is happy.

**Comment by bluca** [comment]
The policy and priority are new-ish but they are wrappers for the libzmq stable API, so I don't think they sound be draft, as they cannot change anymore

**Comment by bluca** [comment]
> If I really was to release czmq-ffi-gen for unreleased CZMQ API, I could just make sure that the specs on CI only run against CZMQ HEAD versions. But as soon as CZMQ's next version is released, I'm gonna be in the same situation again. The generated bindings will contain zsock_hwm(), but the actually released CZMQ won't.

@paddor sorry I'm not sure I follow here - why wouldn't it contain zsock_hwm after release?
It's a new API - you need to treat it as you would any other new API. It's not deprecated - it's always going to be there to support libzmq 2.x, together with a few more options.

It seems to me that the problems happen when generating a binding against version X (whether it's released or a commit from git) and then using it at runtime with version X - 1. That is always going to break when a new API is added, regardless of what it is - unless there is always a check to see if a symbol actually exist at runtime.
What am I missing?

**Comment by paddor** [comment]
Sorry, I guess I misunderstood the situation around `zsock_hwm()`. I thought it's about to be removed from CZMQ. So it has only been removed in ZMQ, but is going to stay in CZMQ?

> It seems to me that the problems happen when generating a binding against version X (whether it's released or a commit from git) and then using it at runtime with version X - 1. That is always going to break when a new API is added, regardless of what it is - unless there is always a check to see if a symbol actually exist at runtime.

As long as the new API is marked "draft", the current Ruby binding will not crash if the symbol is not available. But I see your point. Maybe I should just change the Ruby binding to do this for every symbol. If an old version of CZMQ is installed, there will always be missing symbols, even the ones marked "stable" by the time the binding was generated.

**Comment by bluca** [comment]
> Sorry, I guess I misunderstood the situation around zsock_hwm(). I thought it's about to be removed from CZMQ. So it has only been removed in ZMQ, but is going to stay in CZMQ?

Yes, it's part of the compat layer for older versions of libzmq.

> As long as the new API is marked "draft", the current Ruby binding will not crash if the symbol is not available. But I see your point. Maybe I should just change the Ruby binding to do this for every symbol. If an old version of CZMQ is installed, there will always be missing symbols, even the ones marked "stable" by the time the binding was generated.

Yes always doing the check is a good solution - IMHO it would also be acceptable to just say that the binding and the binary have to match, but if you want to provide a more robust solution that's great.

**Comment by paddor** [comment]
Sure. Working on a new solution in zproject now. Sorry for mangling the API files. I'll file another PR to fix those.

**Comment by bluca** [comment]
No problem at all, thanks for taking care of it
