### ISSUE TITLE
Zmonitor event names outdated with regards to ZMQ

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1805]
The events [HANDSHAKE_FAILED and HANDSHAKE_SUCCEED](https://github.com/zeromq/czmq/blob/master/src/zmonitor.c#L113-L122) have been changed in ZMQ for better language consistency and to be more fine-grained. As far as I can see, there are [4 of them](https://github.com/zeromq/libzmq/blob/master/src/zmq_draft.h#L56-L66) now.

I could file a PR for this soon, but not right now.

**Comment by bluca** [comment]
Yes thanks for the reminder, it's on my TODO list
