### ISSUE TITLE
Not able to configure static library build

### ISSUE THREAD

**Issue by glaure** [zeromq/czmq#1811]
It would be nice to be able to configure static and shared library builds.
Similar to zmq's CMakeLists, there should be libczmq.so and libczmq-static.a.

If somebody could hint me how to use zproject, I could try it to solve this.

Currently I am editing CMakeLists.txt manually and in fear of the files beginning line:
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

 :-)

Bye Gunther

**Comment by bluca** [comment]
https://github.com/zeromq/zproject

edit the zproject_cmake.gsl file to change the template for cmake - you'll need the gsl program to regenerate, from https://github.com/zeromq/gsl

**Comment by glaure** [comment]
Thanks a lot! I will try my best

**Comment by bluca** [comment]
Fixed by #1813
