### ISSUE TITLE
trouble building for vs2015

### ISSUE THREAD

**Issue by xoorath** [zeromq/czmq#1814]
Hey,

I have my own build script that is using czmq as a dependency, and it's failing when I try to build with vs2015.

The version I'm using is af75f8f1d6cd56fc4ea0248ce0c106f2e557fb6a

Here's what I'm trying to do for the compilation:

```
CD .\node_modules\czmq\builds\msvc
CALL .\configure.bat
CD vs2015
CALL .\build.bat
CD %PROJECT_ROOT%
```

The output is:

```
Configuring CZMQ...
Building with libzmq
Building with uuid
Building without systemd
Building without lz4
Building without draft API (stable + legacy API)
Building without uuid
Building without systemd
Building without lz4
Building CZMQ... ()
Platform=x86
Configuration=DynDebug
*** ERROR, build terminated early: see build.log
The input line is too long.
The syntax of the command is incorrect.
error Command failed with exit code 255.
```

The build.log it mentions is here:  [build.log](https://github.com/zeromq/czmq/files/1552745/build.log)

I'm not sure how this is supposed to be working... If I build from the SLN the first error I run into is here:

![image](https://user-images.githubusercontent.com/769014/33900995-645fb3ea-df3e-11e7-8a91-ac4d78d70c1b.png)

It's complaining that it doesn't know about `zargs_t`, and if I update the struct like so:

![image](https://user-images.githubusercontent.com/769014/33901071-9b09951e-df3e-11e7-8be2-dcb2e5c8c8e7.png)

It seems to build _that_ file just fine.

Am I missing something about building czmq, or is the build just broken right now?

**Comment by xoorath** [comment]
tried again with the latest release in the releases tab: Dec 31, 2016 5dafff4f632c84b0505b7f3de512a0c600d202ea

Same output [build.log](https://github.com/zeromq/czmq/files/1552877/build.log)

**Comment by xoorath** [comment]
If I go back to 135e43aefe23a5f0074b0065cbb3984b2a20700a when the readme was last given the instructions for building on windows, the instructions say to run `build/build-all.bat`, which doesn't seem to exist on that revision.

Instructions, for reference:
```
     git clone git://github.com/zeromq/czmq.git
    cd czmq\builds\msvc
    configure.bat
    cd build
    buildall.bat
    cd ..\..\..\..
```

Note, I've ignored the git clone line and gotten the revision I want specifically from my package manager  and CD'd into the appropriate path.

**Comment by xoorath** [comment]
Going to try this in a standalone area now. I realized using my package manager libsodium, libzmq and czmq were side by side with some other folders I didn't expect to interact. 

I noticed `Building with uuid` and `Building without uuid` both in the output of the origonal post, and low and behold I have a (seemingly unrelated) uuid module that's conflicting here, which I have as a dependency of one of my dependencies.

Will report back when trying in an isolated area.

**Comment by Formulator** [comment]
I solved my VS2015 build issues, by doing this;

`If compiling from the command line, add the following lines to the czmq_selftest.vcxproj file in the czmq_selftest directory for your msvs version:`

`<ClCompile Include="..\..\..\..\src\czmq_private_selftest.c" />`
`<ClCompile Include="..\..\..\..\src\zgossip_msg.c" />`

`after the line`

`<ClCompile Include="..\..\..\..\src\czmq_selftest.c" />`

from jacktrades52 comment in  [this issue](https://github.com/zeromq/czmq/issues/1617)

Then using these slightly modified czmq instructions;

`git clone --depth 1 -b stable https://github.com/jedisct1/libsodium.git`
`cd libsodium\builds\msvc\build`
`buildall.bat`
`cd ..\..\..\..`

`:: if libsodium is on disk, the Windows build of libzmq will automatically use it`
`git clone git://github.com/zeromq/libzmq.git`
`cd libzmq\builds\msvc`
`configure.bat`
`cd build`
`buildall.bat`
`cd ..\..\..\..`

`git clone git://github.com/zeromq/czmq.git`
`cd czmq\builds\msvc`
`configure.bat`
`cd vs2015`
`build.bat`

**Comment by wenhuancai** [comment]
@Formulator LNK2019	 __imp__zmq_poll.
i can't remove the error.
my path include  F:\czmq\czmq\include,F:\czmq\libzmq\include.
lib path is : F:\czmq\czmq\bin\Win32\Debug\v140\dynamic

**Comment by myd7349** [comment]
Take a look at `czmq/include/platform.h`, did you build `czmq` with `CZMQ_BUILD_DRAFT_API` defined?
