### ISSUE TITLE
Problem: Python bindings test fails on OSX 10.12 with Xcode 8.3

### ISSUE THREAD

**Issue by bluca** [zeromq/czmq#1821]
Since Travis bumped the OSX image from 10.11 with Xcode 7.3 to 10.12 with Xcode 8.3 the Python FFI tests fails to load the czmq shared library:

```
python bindings/python/test.py
Traceback (most recent call last):
  File "bindings/python/test.py", line 5, in <module>
    from czmq import *
  File "/Users/travis/build/zeromq/czmq/bindings/python/czmq/__init__.py", line 3, in <module>
    from ._czmq_ctypes import *
  File "/Users/travis/build/zeromq/czmq/bindings/python/czmq/_czmq_ctypes.py", line 55, in <module>
    raise ImportError("Unable to find libczmq")
ImportError: Unable to find libczmq
```

First failure:
https://travis-ci.org/zeromq/czmq/jobs/309938056
Last passing build:
https://travis-ci.org/zeromq/czmq/jobs/308101708

As far as I can see it's nothing we changed. Any idea? @vyskocilm  @jimklimov @paddor @karolhrdina @sappo

**Comment by jimklimov** [comment]
No, not quite... one idea is that we might now build and install the binding with one python version, then run tests with another that indeed does not have our libczmq?

**Comment by bluca** [comment]
A pythonpath problem? Could be, no idea how to check it though

**Comment by myd7349** [comment]
Maybe the `-v` option of Python interpreter will provide more information about the module loading detail.
`python -v test.py`

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/pull/1856 - googling around, it looks like LD_LIBRARY_PATH/DLYB_LIBRARY_PATH do not work on newer versions of OSX
