### ISSUE TITLE
environ not declared on osx

### ISSUE THREAD

**Issue by kerberchain** [zeromq/czmq#1834]
I just noticed a bug compiling on OSX High Sierra. 
src/zproc.c:537:19: error: use of undeclared identifier 'environ'
            env = environ;

To be able to successfully compile you need to comment the else clause at line 537 of src/zproc.c then all is good. OSX does not provide environ support it seems.

**Comment by bluca** [comment]
@jimklimov @vyskocilm could you please have a look? Thanks

**Comment by davidkarim** [comment]
Saw the same issue here; also using High Sierra. Was installing with brew:

```
==> ./configure --prefix=/usr/local/Cellar/czmq/HEAD-a6b87be
==> make
Last 15 lines from /Users/davidkarim/Library/Logs/Homebrew/czmq/03.make:
  CC       src/src_libczmq_la-zproxy.lo
  CC       src/src_libczmq_la-zrex.lo
  CC       src/src_libczmq_la-zgossip_msg.lo
  CC       src/src_libczmq_la-zargs.lo
  CC       src/src_libczmq_la-zproc.lo
  CC       src/src_libczmq_la-ztimerset.lo
  CC       src/src_libczmq_la-ztrie.lo
src/zproc.c:537:19: error: use of undeclared identifier 'environ'
            env = environ;
                  ^
1 error generated.
make[1]: *** [src/src_libczmq_la-zproc.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
  CC       src/src_libczmq_la-czmq_private_selftest.lo
make: *** [all-recursive] Error 1
```

**Comment by vyskocilm** [comment]
Hi - I've no access to OSX. According https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man7/environ.7.html environ exists at least in 10.9. Can you type `man 7 environ` on your system?

**Comment by vyskocilm** [comment]
If I am reading man page correctly

>
>     Shared libraries and bundles don't have direct access to environ, which is only available to the loader
>     ld(1) when a complete program is being linked.  The environment routines can still be used, but if
>     direct access to environ is needed, the _NSGetEnviron() routine, defined in <crt_externs.h>, can >be
>     used to retrieve the address of environ at runtime.

I should use `_NSGetEnviron()` routine. I'll prepare a patch

**Comment by vyskocilm** [comment]
PR done @kerberchain, @davidkarim  please test if it builds and merge it if it does.

**Comment by davidkarim** [comment]
Would love to validate since I am working on High Sierra but I hadn't tried building it manually; before I used brew. Anyways, I did try pulling from vyskocilm:master and building manually but I got a different error. 
```
$ make check
Making check in doc
asciidoc -d manpage -b docbook -f ./asciidoc.conf \
		-azmq_version=4.2.4 -ozmq_bind.xml zmq_bind.txt
xmlto man zmq_bind.xml
xmlto: /Users/davidkarim/Documents/libzmq/doc/zmq_bind.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/Users/davidkarim/Documents/libzmq/doc/zmq_bind.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
Document /Users/davidkarim/Documents/libzmq/doc/zmq_bind.xml does not validate
make[1]: *** [zmq_bind.3] Error 13
rm zmq_bind.xml
make: *** [check-recursive] Error 1
```

**Comment by davidkarim** [comment]
Awesome! Worked using brew.
