### ISSUE TITLE
zsock_resolve is wrong on lots of socket

### ISSUE THREAD

**Issue by zhuizhuhaomeng** [zeromq/czmq#1848]
Issue description
#define ZSOCK_TAG 0x0004cafe
#define ZACTOR_TAG 0x0005cafe

when there are more than 0x0005cafe sockets, zsock_resolve will be wrong for FD.
eg: fd = 0x0005cafe;
zsock_resolve ((void *) &fd) will be libzmq sokect, which is wrong.

just set ZSOCK_TAG and ZACTOR_TAG to be a bigger number will OK.

Environment
libzmq version (commit hash if unreleased):
OS:
Minimal test code / Steps to reproduce the issue
What's the actual result? (include assertion message & call stack if applicable)
What's the expected result?

**Comment by bluca** [comment]
Feel free to send a PR to fix them

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/pull/1849
