### ISSUE TITLE
[WIP] problem: #1840 introduces macro def in zproc.h

### ISSUE THREAD

**Issue by wesyoung** [zeromq/czmq#1851]
tagging this for now so we don't lose track of it while it's being fixed upstream.

solution: https://github.com/zeromq/zproject/blob/a7c75864064502de5fbc9fe2c996d03f7e4f0e20/zproject_vs20xx.gsl#L169 ?

ref: https://github.com/zeromq/czmq/pull/1850

**Comment by bluca** [comment]
Note another option: https://github.com/zeromq/czmq/pull/1841#issuecomment-364952997

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/czmq/pull/1853
