### ISSUE TITLE
problem: travis not checking zproject for changes

### ISSUE THREAD

**Issue by wesyoung** [zeromq/czmq#1852]
@bluca unless i'm missing something dumb- assign this one to me and i'll bang on it a bit (so i don't lose track of it)

ref: https://github.com/zeromq/zyre/pull/570

i think this is a similar issue https://github.com/zeromq/czmq/blob/master/bindings/jni/msvc/vs2010/libczmqjni/libczmqjni.props#L35

https://github.com/zeromq/czmq/pull/1850/files#diff-0a6d5077b18ea6c8e2e07032e443ddcd

as we were seeing on the zyre side (zproject changes not being checked, creating confusion when you're working zproject on both of them)

**Comment by wesyoung** [comment]
err "not a similar issue" just hard to figure out which is correct sometimes since there's not a zproject check to .. baseline against. i think it was partially me thinking about it backwards, but it was hard to tell by looking at the two if what i was doing "added the libzmq" line or if i was removing it- (if that makes sense).

**Comment by bluca** [comment]
Yeah we should add the job to this CI too

**Comment by bluca** [comment]
This was now added, so closing

**Comment by wesyoung** [comment]
sorry- got distracted by something shiny. thanks!
