### ISSUE TITLE
zcertstore strange api

### ISSUE THREAD

**Issue by diorcety** [zeromq/czmq#1857]
There is two strange entries in the api of zcertstore:
`<argument name = "state" type = "buffer" c_type = "void *" />`
Souldn't be ?
`<argument name = "state" type = "anything" />`

And:
```
    <callback_type name = "destructor" state = "draft">
        Destructor for loader state.
        <argument name = "self_p" type = "buffer" c_type = "void **" />
    </callback_type>
```
Souldn't be something like ?
```
    <callback_type name = "destructor" state = "draft">
        Destructor for loader state.
        <argument name = "self_p" type = "anything" />
        <return type = "anything" />
    </callback_type>
```
Or without return and let the caller set to NULL (which is like almost the case?) the given pointer?

**Comment by bluca** [comment]
Not sure, try to check the log and CC the author

**Comment by diorcety** [comment]
@petehayes102 Have you an advice on these points?

**Comment by petehayes102** [comment]
To be honest, I think this was just ignorance on my part. C is not my day job. If `type="anything"` is a more sensible or correct option then we should use that instead.
