### ISSUE TITLE
`make` can't generate manpages

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#1872]
On Ubuntu 16.04, I run `./configure` and then `make`, but that fails with:

```
make
Making all in doc
make[1]: Entering directory '/usr/local/src/czmq-4.1.0/doc'
"./mkman" "zmakecert" "./zmakecert.txt" "./.."
  MKMAN[txt]	./../src/zmakecert.c 	=> ./zmakecert.txt
  MKMAN[doc]	./../src/zmakecert.c 	=> ./zmakecert.doc
asciidoc -d manpage -b docbook -f ./asciidoc.conf \
        -aczmq_version=4.1.0 -ozmakecert.xml zmakecert.txt
xmlto man zmakecert.xml
xmlto: /usr/local/src/czmq-4.1.0/doc/zmakecert.xml does not validate (status 3)
xmlto: Fix document syntax or use --skip-validation option
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/usr/local/src/czmq-4.1.0/doc/zmakecert.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
validity error : Could not load the external subset "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
Document /usr/local/src/czmq-4.1.0/doc/zmakecert.xml does not validate
Makefile:684: recipe for target 'zmakecert.1' failed
make[1]: *** [zmakecert.1] Error 13
rm zmakecert.xml
make[1]: Leaving directory '/usr/local/src/czmq-4.1.0/doc'
Makefile:1588: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

It compiles without errors if I `./configure --with-docs=no` first.

**Comment by bluca** [comment]
Works fine on Debian 9 with asciidoc version 8.6.9-5 and xmlto 0.0.28-1, which versions have you got?

**Comment by paddor** [comment]
```
$ asciidoc --version
asciidoc 8.6.10
$ xmlto --version
xmlto version 0.0.28
```
Weird. But what about that "I/O error"?

**Comment by bluca** [comment]
I have no idea... there's no reference to that URL in the codebase. It's also using /usr/local as a working directory? Is that intended?

**Comment by paddor** [comment]
I downloaded the sources of CZMQ 4.1.0 and unpacked them under /usr/local/src. Is that unusual?

**Comment by bluca** [comment]
Well you'd need to build with root access (sudo) and that is unusual and a bit dangerous :-) Not sure if it's related though

**Comment by paddor** [comment]
I unpacked as root, then changed the owner of the unpacked tree. I build as a normal user and `make install` as root. I thought that's a pretty standard way. How do you build from sources?

**Comment by bluca** [comment]
In my user directory - but I don't think this is relevant, sorry for derailing the issue.

Try to set the env variable:

```
export XML_CATALOG_FILES=/etc/xml/catalog
```

Just found it googling for the error: https://github.com/Linuxbrew/homebrew-xorg/issues/11

**Comment by bluca** [comment]
The packages build fine with the docs in the Ubuntu 16.04 builds on OBS FYI: https://build.opensuse.org/package/live_build_log/network:messaging:zeromq:git-stable/czmq/xUbuntu_16.04/x86_64

So there is something weird going on

**Comment by paddor** [comment]
Unfortunately setting that environment variable doesn't help either. Not a big issue though. Thanks for your relentless support here and on the mailing-list. :)

**Comment by jimklimov** [comment]
I believe this is an aspect (or issue) of docbook(-dtd) packaging. Asciidoc
uses docbook which uses XML for converting markup to final formats like
html or pdf. This requires schema and/or data files to be available -
either preinstalled via packaging or downloaded from internet (lack of it
=> I/O Error). Note there are many X.Y versions, and each one used (or
evaluated whether it applies) must be accessible to the tool, locally or
downloadable.

There are asciidoc/a2x flags to forbid download attempts, but then files
must be present locally.

Pedantically, configure script should have handled that (not try building
docs if the tool does not actually work for auto mode, fail config in this
case if docs=yes were requested). I made a pretty exhaustive solution in
NUT, might port it into zproject some day. But it ain't pretty ;)
