### ISSUE TITLE
CLIENT sockets fail to receive on TCP with timeout set

### ISSUE THREAD

**Issue by lunixbochs** [zeromq/czmq#1873]
macOS 10.13.3, libzmq 4.2.3, libczmq 4.1.0

This test fails to receive on `zframe_t *resp = zframe_recv(client);`, and instead times out with no message received. Could be related to https://github.com/zeromq/czmq/issues/1123?

```c
#include <stdio.h>
#include <czmq.h>

void test(int timeout) {
    printf("[+] test started (timeout=%d)\n", timeout);
    zsock_t *server, *client;
    if (timeout) {
        server = zsock_new_server("@tcp://127.0.0.1:9001");
        client = zsock_new_client(">tcp://127.0.0.1:9001");
        zsock_set_rcvtimeo(client, timeout);
        zsock_set_sndtimeo(client, timeout);
    } else {
        server = zsock_new_server("@tcp://127.0.0.1:9001");
        client = zsock_new_client(">tcp://127.0.0.1:9001");
    }
    zframe_t *ping = zframe_from("ping");
    printf("  [-] client sending\n");
    zframe_print(ping, "c->s");
    zframe_send(&ping, client, 0);
    printf("  [-] client sent\n");

    printf("  [-] server receiving\n");
    zframe_t *req = zframe_recv(server);
    zframe_print(req, "s<-c");

    printf("  [-] server responding\n");
    zframe_t *pong = zframe_from("pong");
    zframe_print(pong, "s->c");
    zframe_set_routing_id(pong, zframe_routing_id(req));
    zframe_send(&pong, server, 0);
    zframe_destroy(&req);

    printf("  [-] client receiving\n");
    zframe_t *resp = zframe_recv(client);
    printf("  [-] client received: %p\n", resp);
    zframe_print(resp, "c<-s");
    zframe_destroy(&resp);
    zsock_destroy(&server);
    zsock_destroy(&client);
    printf("[+] test finished\n\n");
}

int main() {
    test(0);
    test(1000);
}
```

With a timeout, the client ends up timing out after 1s with no frame received, but if the timeout is removed the client works just fine:

```
[+] test started (timeout=0)
  [-] client sending
D: 18-03-04 00:40:27 c->s[004] ping
  [-] client sent
  [-] server receiving
D: 18-03-04 00:40:27 s<-c[004] ping
  [-] server responding
D: 18-03-04 00:40:27 s->c[004] pong
  [-] client receiving
  [-] client received: 0x7fb32f501600
D: 18-03-04 00:40:27 c<-s[004] pong
[+] test finished

[+] test started (timeout=1000)
  [-] client sending
D: 18-03-04 00:40:27 c->s[004] ping
  [-] client sent
  [-] server receiving
D: 18-03-04 00:40:27 s<-c[004] ping
  [-] server responding
D: 18-03-04 00:40:27 s->c[004] pong
  [-] client receiving
  [-] client received: 0x0
Assertion failed: (self), function zframe_print, file src/zframe.c, line 464.
Abort trap: 6
```

**Comment by bluca** [comment]
What's the problem here exactly? If you use timeouts you need to handle the case with proper action, retransmission or otherwise.

**Comment by lunixbochs** [comment]
When you enable a 1s timeout, the CLIENT socket can't receive (and a receive takes *far* less than the 1s timeout, as shown by the non-timeout test), and waits the full timeout duration to return. CLIENT sockets outright fail to receive under any condition here with timeout enabled. I'm assuming there's a bug in the internal polling code.

**Comment by bluca** [comment]
Have you tried receiving again after the first timeout?

**Comment by lunixbochs** [comment]
That works, but that doesn't really help my problem (as I'd need to poll separately to know if it was a timeout or not, so this api still isn't the solution?)

**Comment by bluca** [comment]
The connection is asynchronous so it might just be that the timeout is too short. But anyway if you use timeouts then you need to deal with them one way or another

**Comment by lunixbochs** [comment]
The timeout is not too short. The problem here is clearly that the internal polling fails and refuses to receive a message on the first try that is well within the timeout threshold (<10ms vs 1s timeout). This problem doesn't happen with another socket type like REQ/REP, and doesn't happen with timeouts disabled.

**Comment by bluca** [comment]
There's a reason these new types are marked as draft and not available by default - feel free to send a PR with a fix.

**Comment by lunixbochs** [comment]
https://github.com/zeromq/libzmq/issues/2537#issuecomment-295361581

The code for `pthread_cond_timedwait` is wrong. I'm surprised nobody's noticed. `pthread_cond_timedwait` does not use CLOCK_MONOTONIC or SYSTEM_TIME on any platform by default. It uses `CLOCK_REALTIME/gettimeofday`. Unfortunately we can't even fix it on macOS (as `pthread_condattr_setclock` is missing).

So this is what happens:

1. socket_base::recv locks the "threadsafe" `sync` lock
2. zmq::mailbox_safe_t::recv enters cond_var.wait which is supposed to unlock `sync`
3. pthread_cond_timedwait gets a timestamp in the past (CLOCK_MONOTONIC and SYSTEM_TIME are reset at boot, and thus are always smaller than the current time) and immediately times out, failing to unlock `sync`
4. some other part of the code seems to repeatedly call zmq::mailbox_safe_t::recv until the timeout is satisfied
5. socket_base::recv unlocks `sync`

The issue is that somewhere between 1 and 5, another thread tries to call zmq::mailbox_safe_t::send which attempts to lock `sync`.

This affects thread-safe sockets on all platforms. PR to libzmq incoming.

**Comment by lunixbochs** [comment]
This will be fixed by https://github.com/zeromq/libzmq/pull/2967

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libzmq/pull/2967
