### ISSUE TITLE
Release tarball 4.1.1 fails to build using CMake due to missing ClangFormat

### ISSUE THREAD

**Issue by jirutka** [zeromq/czmq#1882]
```
CMake Error at CMakeLists.txt:611 (include):
  include could not find load file:

    ClangFormat
```

I’m using release tarball https://github.com/zeromq/czmq/releases/download/v4.1.1/czmq-4.1.1.tar.gz.

**Comment by bluca** [comment]
The dist tarball is mainly for ./configure; make; make install, you can use the full tarball of the repo instead https://github.com/zeromq/czmq/archive/v4.1.1.tar.gz
