### ISSUE TITLE
Zpoller.Wait assertion failed

### ISSUE THREAD

**Issue by sc13-bioinf** [zeromq/czmq#1886]
Assertion failed: (self), function zpoller_wait, file src/zpoller.c, line 219.

This happens when calling the jni binding:

poller.Wait(500)

(where poller is an instance of Zpoller)

**Comment by sc13-bioinf** [comment]
After constructing the poller poller.self is 0. So maybe I am not constructing the poller properly. At the moment I am trying:

Zpoller([socketone.self, sockettwo.self])

**Comment by hgourvest** [comment]
You have to do this like this:

new Zpoller([0])
add(socketone.self);
add(sockettwo.self);

because the java binding only transmit the first parametter to the function, and the native function expect to have the last handle to be 0.
