### ISSUE TITLE
Compile errors of src (VS15)

### ISSUE THREAD

**Issue by ONLYA** [zeromq/czmq#1888]
I guess that the "_czmq.import.proj_" may have some problems since **VS15 cannot implement the declared types in the header files in /include** during building the solution.
However, this kind of coding style may have some problems with strict compiler I guess. And also for function declarations after the usage of it.
```
/*
void func1(); //without it, may cause "Missing Identifier func1" error
*/

type_t * /* may cause some errors*/
func()
{
	/* some codes here */
	func1();
}

void func1() //This is much more appreciated I think
{
	/* some function code */
}
```
(I tried to pull requests and before that found declarations in the include directory. LOL)

**_Aditional: LNK1181 error happens for libzmq even if I adjust the directories inside the "libzmq.import.proj" produced by configure.bat._**

**Comment by DevAndreas** [comment]
To solve this issue you can:

- Enable drafts by ./configure.bat --enable-drafts
- OR ./configure.bat --disable-drafts and exclude files from libczmq project in IDE (zargs.c ztimerset.c ztrie.c zproc.c)
- OR build using cmake

`"C:\Program Files\CMake\bin\cmake.exe" -DLIBZMQ_INCLUDE_DIRS="C:\Projects\libzmq\include" -DLIBZMQ_LIBRARIES="C:\Projects\libzmq\bin\Win32\Debug\v140\dynamic\libzmq.lib" -DENABLE-DRAFTS=no CMakeLists.txt`
