### ISSUE TITLE
Useage of zsock_send()

### ISSUE THREAD

**Issue by James-Castles** [zeromq/czmq#1891]
@bluca  
Hi bluca ,
I am confused when using the CZMQ for the API of zsock_send()
My demo code as below:
`int nRes = zsock_send(pipe, "sssssisbss", "backend-complete", request_id,
                                         "result",   result.status,
                                         "code",     result.code,
                                         "body",     response_data.memory, response_data.size,
                                         "duration", result.duration);`

I trace the source code of this API  and found that , as below:
`int
zsock_send (void *self, const char *picture, ...)
{
    va_list argptr;
    va_start (argptr, picture);
    int rc = zsock_vsend (self, picture, argptr);
    va_end (argptr);
    return rc;
}
`

`int
zsock_vsend (void *self, const char *picture, va_list argptr)
{
    assert (self);
    assert (picture);

    zmsg_t *msg = zmsg_new ();
    while (*picture) {
        if (*picture == 'i')
            zmsg_addstrf (msg, "%d", va_arg (argptr, int));
        else
        if (*picture == '1')
            zmsg_addstrf (msg, "%" PRIu8, (uint8_t) va_arg (argptr, int));
        else
        if (*picture == '2')
            zmsg_addstrf (msg, "%" PRIu16, (uint16_t) va_arg (argptr, int));
        else
        if (*picture == '4')
            zmsg_addstrf (msg, "%" PRIu32, va_arg (argptr, uint32_t));
        else
        if (*picture == '8')
            zmsg_addstrf (msg, "%" PRIu64, va_arg (argptr, uint64_t));
        else
        if (*picture == 'u')    //  Deprecated, use 4 or 8 instead
            zmsg_addstrf (msg, "%ud", va_arg (argptr, uint));
        else
        if (*picture == 's')
            zmsg_addstr (msg, va_arg (argptr, char *));
        else
        if (*picture == 'b') {
            //  Note function arguments may be expanded in reverse order,
            //  so we cannot use va_arg macro twice in a single call
            byte *data = va_arg (argptr, byte *);
            zmsg_addmem (msg, data, va_arg (argptr, int));
        }
        else
        if (*picture == 'c') {
            zchunk_t *chunk = va_arg (argptr, zchunk_t *);
            assert (zchunk_is (chunk));
            zmsg_addmem (msg, zchunk_data (chunk), zchunk_size (chunk));
        }
        else
        if (*picture == 'f') {
            zframe_t *frame = va_arg (argptr, zframe_t *);
            assert (zframe_is (frame));
            zmsg_addmem (msg, zframe_data (frame), zframe_size (frame));
        }
        else
        if (*picture == 'U') {
            zuuid_t *uuid = va_arg (argptr, zuuid_t *);
            zmsg_addmem (msg, zuuid_data (uuid), zuuid_size (uuid));
        }
        else
        if (*picture == 'p') {
            void *pointer = va_arg (argptr, void *);
            zmsg_addmem (msg, &pointer, sizeof (void *));
        }
        else
        if (*picture == 'h') {
            zhashx_t *hash = va_arg (argptr, zhashx_t *);
            zframe_t *frame = zhashx_pack (hash);
            zmsg_append (msg, &frame);
        }
        else
        if (*picture == 'm') {
            zframe_t *frame;
            zmsg_t *zmsg = va_arg (argptr, zmsg_t *);
            for (frame = zmsg_first (zmsg); frame;
                 frame = zmsg_next (zmsg) ) {
                zframe_t *frame_dup = zframe_dup (frame);
                zmsg_append (msg, &frame_dup);
            }
        }
        else
        if (*picture == 'z')
            zmsg_addmem (msg, NULL, 0);
        else {
            zsys_error ("zsock: invalid picture element '%c'", *picture);
            assert (false);
        }
        picture++;
    }
    return zmsg_send (&msg, self);
}`

and at the end of the function it call zmsg_send,

zmsg_send as below:
int
zmsg_send (zmsg_t **self_p, void *dest)
{
    assert (self_p);
    assert (dest);
    zmsg_t *self = *self_p;

    int rc = 0;
    void *handle = zsock_resolve (dest);
    if (self) {
        assert (zmsg_is (self));
        zframe_t *frame = (zframe_t *) zlist_pop (self->frames);
        while (frame) {
            rc = zframe_send (&frame, handle,
                              zlist_size (self->frames) ? ZFRAME_MORE : 0);
            if (rc != 0)
                break;
            frame = (zframe_t *) zlist_pop (self->frames);
        }
       #  if (rc == 0)
            zmsg_destroy (self_p);
    }
    return rc;
}

**My question is when zsock_send failed(return -1)  , how to destroy the msg  which zsock_vsend  malloc ?**

Thank you

**Comment by bluca** [comment]
It already destroys the message, you are looking at old code:

https://github.com/zeromq/czmq/blob/master/src/zsock.c#L932

**Comment by James-Castles** [comment]
Thank you @bluca  , If CZMQ for version 4.1.1 , then which version of ZMQ it can matched with ?
Thank you so much

**Comment by bluca** [comment]
every version will work

**Comment by James-Castles** [comment]
@bluca  , Thanks for your reply ,I will try to use ZMQ(4.1.5)&& CZMQ(4.1.1) .

**Comment by James-Castles** [comment]
When I try to build it ,I meet some errors , as below:

`cc1: warnings being treated as errors
src/zproc.c: In function 'zpair_destroy':
src/zproc.c:110: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/zproc.c:112: warning: dereferencing type-punned pointer will break strict-aliasing rules
make[1]: Leaving directory `/tmp/src/czmq-4.1.1'
make[1]: *** [src/src_libczmq_la-zproc.lo] Error 1
make: *** [all-recursive] Error 1`

I use the command:
`    ./configure --host=arm-brcm-linux-gnueabi --prefix=$LO_SDK_TOP_DIR       \
                LIBS=-L$LO_SDK_LIB_DIR                                && \
    make && make install || (cat config.log && exit 1)`

Can you give me some advice  about it ? 
Sorry to reopen it .

**Comment by bluca** [comment]
--enable-drafts=no

**Comment by James-Castles** [comment]
./configure --host=arm-brcm-linux-gnueabi --prefix=$LO_SDK_TOP_DIR  --enable-drafts=no  \ LIBS=-L$LO_SDK_LIB_DIR && \ make && make install || (cat config.log && exit 1)

Am I correct ?  
Thank you
