### ISSUE TITLE
Error when build CZMQ 4.1.1

### ISSUE THREAD

**Issue by James-Castles** [zeromq/czmq#1892]
@bluca 
Sorry , the issues I just post has been closed , so I create a new issues to ask some related issue.

When I try to build it ,I meet some errors , as below:

cc1: warnings being treated as errors src/zproc.c: In function 'zpair_destroy': src/zproc.c:110: warning: dereferencing type-punned pointer will break strict-aliasing rules src/zproc.c:112: warning: dereferencing type-punned pointer will break strict-aliasing rules make[1]: Leaving directory/tmp/src/czmq-4.1.1'
make[1]: *** [src/src_libczmq_la-zproc.lo] Error 1
make: *** [all-recursive] Error 1`

I use the command:
./configure --host=arm-brcm-linux-gnueabi --prefix=$LO_SDK_TOP_DIR \ LIBS=-L$LO_SDK_LIB_DIR && \ make && make install || (cat config.log && exit 1)

Can you give me some advice about it ?

**Comment by James-Castles** [comment]
related to #1892

**Comment by vyskocilm** [comment]
What is the compiler used? Can you run make V=1 and post the full compiler line? I built it with gcc 7 and clang 6 just fine.

**Comment by James-Castles** [comment]
@vyskocilm  ,Thank you , I can build it now 
 Thank you so much for your reply.

**Comment by bluca** [comment]
Ok, closing then
