### ISSUE TITLE
About thread safety

### ISSUE THREAD

**Issue by mark20171009** [zeromq/czmq#1926]
Hello,everyone,following are my steps and question 
My steps
1 I have create about 20 threads in Pos.Environment is Linux
2 in one of the thread ,I Set up a while-cycle as follow
while(1)
{    
      sleep(3);
      printf("waiting...\n");
} 
and then I notice that other thread are running
,but main process are blocked
My question:
 What causes the issue?Does it involve security issues？And how can I deal with this?
please back me ,thank you

**Comment by bluca** [comment]
How is czmq involved in this?
