### ISSUE TITLE
Zclock jni binding - static methods

### ISSUE THREAD

**Issue by hgourvest** [zeromq/czmq#1957]
All member functions should be static.

https://github.com/zeromq/czmq/blob/604ce17c014f96f2a3c244cbae275ed3741787cb/bindings/jni/src/main/java/org/zeromq/czmq/Zclock.java#L23

**Comment by sappo** [comment]
Hi Henri,
the JNI binding is generated by zproject. Would you like to try to solve
this problem yourself.

Am Mi., 28. Nov. 2018, 12:52 hat Henri Gourvest <notifications@github.com>
geschrieben:

**Comment by hgourvest** [comment]
fixed in this merge https://github.com/zeromq/zproject/pull/1134
