### ISSUE TITLE
Where in source do frames get encrypted by libsodium

### ISSUE THREAD

**Issue by need-sleep** [zeromq/czmq#1964]
I've been code surfing the libcurve and czmq repositories and I can't find where frames are encrypted. What cipher is being used? Where in the code is this done? 

Can someone offer a high level walk through of how libcurve/czmq uses libsodium from start to finish? My hope is to get an established pair of keys via getsocketop() and use them to manually encrypt messages being sent on an existing RPC channel between two points.

Thanks

**Comment by myd7349** [comment]
A good start: https://github.com/zeromq/libzmq/blob/master/CMakeLists.txt#L81-L107

**Comment by bluca** [comment]
Doing manual encryption is strongly discouraged and not supported in any way. Here's some documents describing the design:

http://hintjens.com/blog:48
ttps://rfc.zeromq.org/spec:25/ZMTP-CURVE/
