### ISSUE TITLE
libpgm issue not found if installing libczmq from 0mq PPA

### ISSUE THREAD

**Issue by rgerhards** [zeromq/czmq#1983]
Hi, we are using the PPA packages inside rsyslog CI. This worked well for quite a while. However, I now get the following error when compiling rsyslog 0mq components:
```
make[2]: Entering directory '/worker/rsyslog_docker-ubuntu16_rsyslog/build/contrib/omczmq'
  CC       omczmq_la-omczmq.lo
cc1: error: /usr/lib/x86_64-linux-gnu/pgm-5.2/include: No such file or directory [-Werror=missing-include-dirs]
cc1: all warnings being treated as errors
```
I first discovered this on Ubuntu 18.04 in December, and today on 16.04 (fresh container install). Container def is here: https://github.com/rsyslog/rsyslog-docker/blob/master/dev_env/ubuntu/base/16.04/Dockerfile

I was able to work around the issue by falling back to Ubuntu-provided 0mq components. But as it looks there is an issue with the PPA ones.

**Comment by bluca** [comment]
Hi, this is originally a problem in libpgm's pkgconfig file:

https://github.com/steve-o/openpgm/pull/57
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=920259

I can upload an updated version to our PPA, will do so shortly.

**Comment by bluca** [comment]
@rgerhards fixed and published, should work now.

**Comment by rgerhards** [comment]
thx a ton - I'll give it a try a bit later, I have right now other work on the container in testing. Need to finish that first.

**Comment by bluca** [comment]
ok, I'll close in the meanwhile, reopen if there are issues

**Comment by rgerhards** [comment]
Just re-tried. I see the problem again. Do I need to wait for an update cycle or install libpgm from a special location (I didn't do that in the past). I now have an env where I can switch with relative ease. Rolling back to the distro version now.

**Comment by bluca** [comment]
Is it by any chance an i386 build rather than amd64? Because the i386 for Ubuntu 16.04 hadn't published on OBS yet as there was a build-worker stuck. I've killed and restarted it.

If it's the amd64 it's quite weird, as you can see from the libpgm-dev package the Cflags line in the pkg-config file is now correct:

```
Cflags: -I${includedir}/pgm-5.2
```

https://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_16.04/amd64/libpgm-dev_5.2.122~dfsg-2.1_amd64.deb

Can you check in the log the version of the libpgm-dev package that gets installed?

**Comment by rgerhards** [comment]
Indeed, something is fishy here... I see the `apt install` but I don't see it actually being installed. If I manually go into the ready-made container, it is not there, and installing it manually seems to work. Let me dig deeper into that.

**Comment by rgerhards** [comment]
@rgerhards my fault: when I ran into the trouble, I added `apt install libpgm-dev` to the OS packages and forgot to remove that later. So actually libpgm was installed from distro archive. After removing that, everything works great. Thx again for your quick help!

**Comment by bluca** [comment]
Great, glad to hear that

**Comment by bluca** [comment]
No problem - I did not enable the build for tumbleweed as I got it fixed upstream but I guess it's not deployed yet, so I'll enable it temporarily

**Comment by rgerhards** [comment]
thx! I also dug a bit deeper in between. It looks upstream is providing `libpgm-5_2`, but not `libpgm-devel`. Maybe it's a single package, but maybe that was why when I used distro packages the problem persisted.

**Comment by bluca** [comment]
The package is called openpgm-devel, it seems to be available: https://build.opensuse.org/package/binaries/devel:libraries:c_c++/openpgm/openSUSE_Factory it's been submitted to Factory and should be in Tumbleweed proper soon.

In the meanwhile I've enabled it in our PPA, so if you try again it should have the fixed version

**Comment by rgerhards** [comment]
excellent, all well! thx again.
