### ISSUE TITLE
czmq zsock_new_sub/zsock_recv issue with gcc optimization

### ISSUE THREAD

**Issue by foxhlchen** [zeromq/czmq#2001]
I'm writing a czmq Pub/Sub demo. However, Sub doesn't work properly with GCC optimization, when I add -Ox (whatever O1 O2 O3) the problem occurs,  once I drop -Ox argument or use -O0 to turn off optimization, everything is good.

#### PUB:
```
#include <czmq.h>
#include <iostream>

using namespace std;

int main(int argc, char ** argv) {
  zsock_t *socket = zsock_new_pub("tcp://0.0.0.0:8889");
  assert(socket);

  const char *buf = "Hello World";
  while(!zsys_interrupted) {
    zsys_info("Publishing");
    zsock_send(socket, "sb", "TOPIC", buf, strlen(buf) + 1);
    zclock_sleep(1000);
  }


  return 0;
}
```

#### SUB:
```
#include <czmq.h>
#include <iostream>

using namespace std;

int main(int argc, char const *argv[])
{
    zsock_t *socket = zsock_new_sub("tcp://127.0.0.1:8889",  "");
    assert(socket);

    char *topic;
    char *frame;
    uint32_t size;


    long i = 0;
    while (true) {
        int rc = zsock_recv(socket, "sb", &topic, &frame, &size);
        assert(rc == 0);


        cout << topic << endl;


        free(topic);
        free(frame);
    }

    zsock_destroy(&socket);

    return 0;
}
```

the Pub is always OK with or w/o optimization.  

For the SUB, if I turn optimization on,  zsock_recv returns 0,  the value of  frame is correct (="Hellow World"), but topic is NULL (should be "TOPIC"). Once I turn off optimization, the value of topic becomes correct (="TOPIC").

#### OS environment:

CentOS 7

 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 

 ll /usr/local/lib | egrep "zmq|czmq"
-rw-r--r-- 1 root root  4298760 Mar  3 11:05 libczmq.a
-rwxr-xr-x 1 root root      963 Mar  3 11:05 libczmq.la
lrwxrwxrwx 1 root root       16 Mar  3 11:05 libczmq.so -> libczmq.so.4.1.1
lrwxrwxrwx 1 root root       16 Mar  3 11:05 libczmq.so.4 -> libczmq.so.4.1.1
-rwxr-xr-x 1 root root  1862920 Mar  3 11:05 libczmq.so.4.1.1
-rw-r--r-- 1 root root 25659556 Mar  3 11:04 libzmq.a
-rwxr-xr-x 1 root root      954 Mar  3 11:04 libzmq.la
lrwxrwxrwx 1 root root       15 Mar  3 11:04 libzmq.so -> libzmq.so.5.1.3
lrwxrwxrwx 1 root root       15 Mar  3 11:04 libzmq.so.5 -> libzmq.so.5.1.3
-rwxr-xr-x 1 root root  8717784 Mar  3 11:04 libzmq.so.5.1.3

 Build flags
g++ -std=c++11 main.cpp -lzmq -lczmq (-O3)

**Comment by bluca** [comment]
There is something very weird going on here...

If you switch the order of declaration of topic and frame in your example, the opposite happens - it works fine with optimisations, and it breaks with O0.

That's because the problem occurs when doing a malloc into the second variable, when it has a lower address than the other one - which gets corrupted.
The address of the variables get changed by optimisations - the first variable has a lower address than the second one with optimisations turned off, and viceversa with O2.

With the switched declarations:

```
(gdb) b zsock.c:1063
Breakpoint 2 at 0x7ffff7b8a795: file src/zsock.c, line 1063.
(gdb) b zsock.c:1075
Breakpoint 3 at 0x7ffff7b8a802: file src/zsock.c, line 1075.
(gdb) c
Continuing.
[New Thread 0x7fffefe24700 (LWP 11222)]
[New Thread 0x7fffef623700 (LWP 11223)]

Thread 1 "test2" hit Breakpoint 2, zsock_vrecv (self=<optimized out>, picture=0x555555554a66 "sb", 
    argptr=argptr@entry=0x7fffffffddc0) at src/zsock.c:1063
warning: Source file is more recent than executable.
1063	            if (string_p)
(gdb) p string_p
$1 = (char **) 0x7fffffffdeb8
(gdb) p *(char **) 0x7fffffffdeb8
$2 = 0x0
(gdb) n
1103	                *frame_p = frame;
(gdb) 
1184	        picture++;
(gdb) p *(char **) 0x7fffffffdeb8
$3 = 0x555555757b70 "TOPIC"
(gdb) c
Continuing.

Thread 1 "test2" hit Breakpoint 3, zsock_vrecv (self=<optimized out>, picture=0x555555554a67 "b", 
    argptr=argptr@entry=0x7fffffffddc0) at src/zsock.c:1075
1075	                    *size = zframe_size (frame);
(gdb) p *(char **) 0x7fffffffdeb8
$4 = 0x555555757b70 "TOPIC"
(gdb) n
1076	                    *data_p = (byte *) malloc (*size);
(gdb) p data_p
$5 = (byte **) 0x7fffffffdec0
(gdb) p *(char **) 0x7fffffffdeb0
$6 = 0x555555784ed0 "\001"
(gdb) n
1075	                    *size = zframe_size (frame);
(gdb) p *(char **) 0x7fffffffdeb0
$7 = 0x555555784ed0 "\001"
(gdb) p *(char **) 0x7fffffffdeb8
$8 = 0x555555757b70 "TOPIC"
(gdb) n
1076	                    *data_p = (byte *) malloc (*size);
(gdb) p *(char **) 0x7fffffffdeb8
$9 = 0x555500000000 <error: Cannot access memory at address 0x555500000000>
```

It will be difficult to figure out what's going on without looking at the generated assembly... my best guess is hitting some undefined behaviour with the builtin intrinsic implementation of va_arg

**Comment by foxhlchen** [comment]
So It's not a bug of czmq, it's a bug of gcc/glibc?

How can I fix it?? To use the zmq interfaces directly instead of the czmq wrapper?

**Comment by bluca** [comment]
Use zmsg and zframe rather than zsock send/recv

**Comment by bluca** [comment]
@foxhlchen also if you declare the variables this way it works with any optimisation level:

```
    char *frame;
    uint32_t size;
    char *topic;
```

as an additional workaround until someone figures out what the compiler is doing

**Comment by foxhlchen** [comment]
OK, thanks.  Usually, the declaration order can affect the behavior only when the stack or heap was corrupted somewhere.  Maybe that is the problem?

**Comment by bluca** [comment]
Yes, I showed where it happens above
