### ISSUE TITLE
Failed to build czmq on Centos 

### ISSUE THREAD

**Issue by farmerx** [zeromq/czmq#2003]
![image](https://user-images.githubusercontent.com/24504247/56285699-6c106a00-614a-11e9-9cc3-2b94a24fc598.png)

**Comment by bluca** [comment]
You are missing the required dependencies. Don't build the library yourself, use the available packages:

https://software.opensuse.org/download.html?project=network%3Amessaging%3Azeromq%3Agit-stable&package=czmq

**Comment by farmerx** [comment]
![image](https://user-images.githubusercontent.com/24504247/56288777-0aec9480-6152-11e9-9c32-8c2b8e5bceb7.png)

**Comment by bluca** [comment]
Follow the instruction to add the repository, and use yum

**Comment by bluca** [comment]
@farmerx did that work?

**Comment by bluca** [comment]
No answer, assuming the problem is solved
