### ISSUE TITLE
WIndows build procedure now?

### ISSUE THREAD

**Issue by eplumer** [zeromq/czmq#2004]
I am trying to rebuild CZMQ for windows after updating to libzmq 4.3.1 to get the security-related fixes.  Libzmq has deprecated their msvc build projects so I used their recommended CMake procedure.  This generated a very different directory layout and naming structure for the libraries. 

The instructions and bat files for windows build of CZMQ have not changed and still refer to the old libzmq layout and make explicit dependencies on content of the original build\msvc\* directories.  

Is there an update build procedure for window? 

Would an older build of CZMQ work with libzmq 4.3.1?

**Comment by bluca** [comment]
You should be able to use cmake here as well

**Comment by eplumer** [comment]
Unfortunately, the CMake for CZMQ does not find the built LIBZMQ either.
I see issue #1972 that might be related.

**Comment by bluca** [comment]
The CI works fine so have a look at what it does:

https://github.com/zeromq/czmq/blob/master/appveyor.yml

If that doesn't work either, this seems a duplicate of #1972 so please use that issue instead

**Comment by myd7349** [comment]
A quick fix of this problem:

First, build and install `libzmq` on Windows:
```
cd libzmq
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=C:/libzmq
cmake --build . --target install
```
Then, clone `czmq` and replace `Findlibzmq.cmake` with this one: https://github.com/myd7349/Ongoing-Study/blob/master/cpp/CMake/find_libzmq_ng/Findlibzmq.cmake
```
cd czmq
mkdir build
cd build
cmake .. -DCMAKE_PREFIX_PATH=C:/libzmq
```

The CI configuration file has this line: https://github.com/zeromq/czmq/blob/master/appveyor.yml#L53
That is, it renames libs like `libzmq-v141-mt-gd-4_3_2.lib` to `zmq.lib`.

**Comment by bluca** [comment]
thanks - could you please post it to the other issue that's already open?

**Comment by myd7349** [comment]
Sure. I am considering to create a PR for fixing this problem.
