### ISSUE TITLE
Major security vulnerability in gradle wrapper

### ISSUE THREAD

**Issue by atulkulk** [zeromq/czmq#2008]
Hello,

There is a security vulnerability in the gradle wrapper(v2.13) present in the latest czmq-4.2.0. 

https://www.cvedetails.com/vulnerability-list/vendor_id-16071/Gradle.html

Is there any plan to update the gradle wrapper?

Regards,
Atul

**Comment by bluca** [comment]
@sappo is this something you'd have time to look at? Thanks!

**Comment by sappo** [comment]
Sure!
I opened a PR in zproject then will regenerate the wrapper in czmq, zyre, etc
https://github.com/zeromq/zproject/pull/1181

**Comment by bluca** [comment]
Thanks!
