### ISSUE TITLE
undefined symbol: zmq_poller_new

### ISSUE THREAD

**Issue by TsurHerman** [zeromq/czmq#2013]
while trying to build czmq on ubuntu linux arm64 I keep getting the error 
undefined symbol: zmq_poller_new

inspecting the object file I see it exists in libzmq but undefined in czmq
can you shed some light on this issue

```

objdump /usr/local/lib/libzmq.so -t | grep zmq_poller_new                                                                  17:00:56
0000000000066de0 g     F .text	000000000000006c              zmq_poller_new


```

> 
> objdump /usr/local/lib/libczmq.so -t | grep zmq_poller_new                                                                    17:02:39
> 0000000000000000       F *UND*	0000000000000000              zmq_poller_new
> 
>

**Comment by somdoron** [comment]
How did you install libzmq? You probably have to compile from source and include the DRAFT flag.

**Comment by TsurHerman** [comment]
I did it from source with the latest stable build. 
Actually I am trying to get zyre to work. 
I will try removing any zmq apt-get installed and do it again

**Comment by bluca** [comment]
There's no need to build from sources, we provide packages in a repository:

https://software.opensuse.org/download.html?project=home%3Azeromq%3Agit-stable&package=libzyre-dev

**Comment by TsurHerman** [comment]
@bluca I am on arm64, manually adding the repo did not work.

After removing libzmq5 installed by apt-get when I installed GStreamer1.0 ... it works.
But it fails again when I re-install GStreamer using apt-get

**Comment by bluca** [comment]
libczmq-dev is actually available in Ubuntu's repositories too, there's no need for our own.

**Comment by TsurHerman** [comment]
OK I found it, I am working with qmake and qt , and at runtime it would look first in /usr/lib and only then in /usr/local/lib. I fixed that and everything is in order.

Nothing wrong with your code , and the instructions for building from source works flawlessly.

On a positive note, I admire the zmq software suit , you sure take coding seriously.
