### ISSUE TITLE
Error: dangling 'REQ' socket created at ...

### ISSUE THREAD

**Issue by Blobby19** [zeromq/czmq#2018]
Hello,

I try to implement REQ-REP sockets to communicate between cli & daemon running on linux environnment.
Everything seems to be ok on the daemon side with a REP IPC socket, but when I try to create socket using zsock_new or zsock_new_req on the client side, I get this error:
E: 19-09-03 13:14:19 [1192]dangling 'REQ' socket created at client.c:15

```
#include <czmq.h>

int main(int argc, char **argv)
{
	zsock_t *socket = zsock_new_req("ipc:///tmp/mcucomm");
	return 0;
}
```

CZMQ 4.2.0
ZMQ 4.1.6

**Comment by sappo** [comment]
ZeroMQ is complaining that you forgot to cleanup after yourself:

```c
zsock_destroy (&socket);
```

**Comment by jinbeomdev** [comment]
```
zframe_t* frame = zframe_recv(responder);
```
When above statement hit I got error msg
```
E: 21-09-30 09:00:46 [29305]dangling 'REP' socket created at ...
```
Can you give me any advice?

**Comment by jinbeomdev** [comment]
I could avoid it like following
```
while (true) {
  ...
  zframe_t* frame = zframe_recv(responder);
  if (frame == nullptr) {
    continue;
  }
}
```
It works to me but It is wired right? why zframe_recv return NULL not block it?
