### ISSUE TITLE
zbeacon leaks file descriptor from udpsock_send on destroy

### ISSUE THREAD

**Issue by medons** [zeromq/czmq#2021]
Running valgrind:

valgrind --leak-check=yes --show-reachable=no --num-callers=20 --track-fds=yes ./ZLogLogger_test

RESULT AS RELEASED:
2019-09-24 10:06:07.867 - Logger[31284]::~Logger()
==31284== 
==31284== FILE DESCRIPTORS: 4 open at exit.
==31284== Open AF_INET socket 17: 10.0.10.63:5911 <-> unbound
==31284==    at 0x618C4C7: socket (in /usr/lib64/libc-2.17.so)
==31284==    by 0x4E7673F: zsys_udp_new (zsys.c:1044)
==31284==    by 0x4E7C7D0: s_self_prepare_udp (zbeacon.c:105)
==31284==    by 0x4E7CB7E: s_self_configure (zbeacon.c:324)
==31284==    by 0x4E7CB7E: s_self_handle_pipe (zbeacon.c:352)
==31284==    by 0x4E7CB7E: zbeacon (zbeacon.c:506)
==31284==    by 0x4E484B2: s_thread_shim (zactor.c:68)
==31284==    by 0x66C6E24: start_thread (in /usr/lib64/libpthread-2.17.so)
==31284==    by 0x618B34C: clone (in /usr/lib64/libc-2.17.so)
==31284== 
==31284== Open file descriptor 2: /dev/pts/0
==31284==    <inherited from parent>
==31284== 
==31284== Open file descriptor 1: /dev/pts/0
==31284==    <inherited from parent>
==31284== 
==31284== Open file descriptor 0: /dev/pts/0
==31284==    <inherited from parent>
==31284== 
==31284== 
==31284== HEAP SUMMARY:
==31284==     in use at exit: 0 bytes in 0 blocks
==31284==   total heap usage: 1,342 allocs, 1,342 frees, 315,112 bytes allocated
==31284== 
==31284== All heap blocks were freed -- no leaks are possible
==31284== 
==31284== For counts of detected and suppressed errors, rerun with: -v
==31284== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

TESTED change:
static void
s_self_destroy (self_t **self_p)
{
    assert (self_p);
    if (*self_p) {
        self_t *self = *self_p;
        zframe_destroy (&self->transmit);
        zframe_destroy (&self->filter);
        if (self->udpsock_send) // don't close STDIN
            zsys_udp_close (self->udpsock_send);
        if (self->udpsock) // don't close STDIN
            zsys_udp_close (self->udpsock);
        freen (self);
        *self_p = NULL;
    }
}

AFTER change:

2019-09-25 14:18:16.277 - Logger[76493]::~Logger()
==76493== 
==76493== FILE DESCRIPTORS: 3 open at exit.
==76493== Open file descriptor 2: /dev/pts/0
==76493==    <inherited from parent>
==76493== 
==76493== Open file descriptor 1: /dev/pts/0
==76493==    <inherited from parent>
==76493== 
==76493== Open file descriptor 0: /dev/pts/0
==76493==    <inherited from parent>
==76493== 
==76493== 
==76493== HEAP SUMMARY:
==76493==     in use at exit: 0 bytes in 0 blocks
==76493==   total heap usage: 1,051 allocs, 1,051 frees, 275,870 bytes allocated
==76493== 
==76493== All heap blocks were freed -- no leaks are possible
==76493== 
==76493== For counts of detected and suppressed errors, rerun with: -v
==76493== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

**Comment by bluca** [comment]
Fixed a few months ago by https://github.com/zeromq/czmq/pull/2002
