### ISSUE TITLE
How to build a consistent ZeroMQ eco-system on Windows ?

### ISSUE THREAD

**Issue by zedalaye** [zeromq/czmq#2026]
**Problem** : It's hard to build a consistent ZeroMQ eco-system on Windows

**Solution** : Write a script to do it for you

https://gist.github.com/zedalaye/0490a98b3111a11d0ad917cdb706a4ef

I don't know where else to publish that piece of work but it builds:

- openssl (1.0.2, should work with 1.1.x too)
- libsodium (master)
- libzmq (master) with libsodium
- libcurl (master) with openssl and nghttp2 (master, statically linked)
- czmq (master) with libcurl, libmicrohttpd (master, statically linked) and lz4 (master, statically linked)
- zyre (master)

Required toolchain: 

- Visual Studio 2017
- CMake
- Git
- Strawberry Perl and NASM (for OpenSSL)

Hope it will help and you will find a good place somewhere for it :)

**Comment by bluca** [comment]
https://github.com/conda/conda
https://github.com/microsoft/vcpkg

**Comment by myd7349** [comment]
https://github.com/zeromq/czmq#building-on-windows
