### ISSUE TITLE
Error when build ffmpeg

### ISSUE THREAD

**Issue by matanmarciano** [zeromq/czmq#2029]
Hello, I a trying to build ffmpeg with enable zmq:
`./configure --enable-libzmq`

and i got this error:

> ERROR: libzmq >= 4.2.1 not found using pkg-config

**Comment by bluca** [comment]
This is the wrong repository. However, on Debian/Ubuntu run ```sudo apt install libzmq3-dev``` and on Fedora/Suse/Rhel install ```zeromq-devel```
