### ISSUE TITLE
JNI Binding not compatible with other zmq binding due to GetStringUTFChars

### ISSUE THREAD

**Issue by ledergec** [zeromq/czmq#2032]
With czmq v4.2.0:

In the JNI binding all strings are escaped using GetStringUTFChars and descaped using NewStringUTF. 

This makes renders the binding completely incompatible with other language bindings. The data being sent cannot be changed by the binding!

We are trying to interact with cppzmq on the other side which does not do such escaping.

**Comment by ledergec** [comment]
I have figured this one out. I called the ZStr functions. However, I am supposed to call the Zmsg functions.

The following seems to work:

Send:
`    Zmsg zmsg = new Zmsg();
    zmsg.addmem(data, data.length);
    zmsg.send(socket.self);
    zmsg.close();
`

Receive:
`    Zmsg zmsg = Zmsg.recv(socket.self);
    Zframe zframe = zmsg.pop();
    byte[] data = zframe.data();
    zmsg.close();
`

Where the socket is created as follows, depending on the needs:
`    switch (type) {
      case REPLYER:
        socket = Zsock.newRep(endpoint);
        break;
      case REQUESTER:
        socket = Zsock.newReq(endpoint);
        break;
      case PUBLISHER:
        socket = Zsock.newPub(endpoint);
        break;
      case SUBSCRIBER:
        socket = Zsock.newSub(endpoint, "");
        break;
    }
`

Nevertheless, a bit more documentation would be helpful...

**Comment by sappo** [comment]
I think you hit a valid issue here being that the binding changes the data. I'll look into it when I got some time.
