### ISSUE TITLE
ZMQ sockets (zsock_t) do not work in child process after fork

### ISSUE THREAD

**Issue by santupari** [zeromq/czmq#2038]
Hi All,

We are observing an issue where in sockets created in child process do not work after forking.
Below is the sequence of code and I have also attached test code that reproduces issue and as well as working code:
1. Our design has a server which listens to multiple clients and responds
2. Clients uses wrapper API (example : test_tx_rx()) that exchanges messages with server
3. the issue observed when a client calls  test_tx_rx() from parent and then fork and if you call test_tx_rx() from child it fails to communicate with server
4. The fix is to call zsys_shutdown() from child to clean up all initialization done by parent and assume that ZSYS is already initialized. However, as part of this fix we also noticed that there is a mutex that should be re-initialized to avoid deadlock. Hence, we are also attaching a patch that defines new API for re-initializing the mutex.

Please let us know if the patch is valid or how to avoid deadlock in case if the parents threads are accessing the mutex at the same when child is clearing mutex in zsys_shutdown().

Thanks,
Santosh Bidaralli

[zsys_patch_wtih_test_code.zip](https://github.com/zeromq/czmq/files/4079091/zsys_patch_wtih_test_code.zip)

**Comment by bluca** [comment]
Adding a new API is not good for usability.

A better fix is to record the PID on init, and check it on shutdown - if it's different, then a fork happened and the mutex can be reinitialised.

Could you please send a pull request for this change, after testing that it works for your use case? Thanks!

**Comment by santupari** [comment]
Thank you @bluca!
I will make the suggested change in zsys_shutdown(). If my understanding is correct, defining a new static variable in zsys.c to store the parent pid should be sufficient to check it during the init and shutdown.
Please send me the instructions to submit a pull request.
Thanks,
Santosh Bidaralli

**Comment by bluca** [comment]
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests

**Comment by santupari** [comment]
Thanks @bluca ! I found better way of handling this and with below changes there is no need for application to call zsys_shutdown(). Please review these changes and let me know if i can submit a pull request for the same.
 
--- orig/src/zsys.c	2020-01-27 16:07:47.089956960 -0600
+++ git/src/zsys.c	2020-01-27 16:09:34.408025720 -0600
@@ -108,6 +108,10 @@
 //  We keep a list of open sockets to report leaks to developers
 static zlist_t *s_sockref_list = NULL;
 
+//  We keep track of the pid of the process that creates the context
+//  this will detect fork and re-init the context
+static pid_t s_pid = 0;
+
 //  This defines a single zsock_new() caller instance
 typedef struct {
     void *handle;
@@ -150,6 +154,22 @@
 void *
 zsys_init (void)
 {
+    // initialize pid
+    if (s_pid == 0) {
+        s_pid = getpid();
+    }
+    else {
+        // possibly forked - check if we are in child process
+        if (s_pid != getpid()){
+            // Child process
+            // Avoid race conditions with parent
+            ZMUTEX_INIT (s_mutex);
+            // Immediately close parent sockets and context
+            zsys_shutdown();
+            s_pid = getpid();
+        }
+    }
+
     if (s_initialized) {
         assert (s_process_ctx);
         return s_process_ctx;

**Comment by bluca** [comment]
That looks fine, thanks

**Comment by santupari** [comment]
Hi @bluca,
We did thorough testing of the earlier patch in a multi-threaded environment and we were facing intermittent crashes. We worked to come up with a different patch altogether to make zsys_init() thread-safe and as well as handling fork conditions. I have attached the patch for review. Please review the same and let me know for any comments.
[czmq_zsys_fork_issue_2038.zip](https://github.com/zeromq/czmq/files/4283613/czmq_zsys_fork_issue_2038.zip)

**Comment by raveendrapadala** [comment]
@bluca : We are facing similar Crash issue when an application is doing fork inside fork with ZMQ sockets in the parent process. 
So is this patch going to be available in the next release? please confirm.

**Comment by bluca** [comment]
If someone sends a pull request, yes
