### ISSUE TITLE
Encryption in ZeroMQ

### ISSUE THREAD

**Issue by arzoo14** [zeromq/czmq#2066]
My project uses ZeroMQ for communication between data centers. How can I encrypt messages in ZeroMQ?

**Comment by bluca** [comment]
If you are using CZMQ:

https://github.com/zeromq/czmq/tree/master/examples/security

If you are using libzmq:

https://github.com/zeromq/libzmq/blob/master/doc/zmq_curve.txt

If any other binding/implementation, refer to the specific documentation.
