### ISSUE TITLE
Cannot build JNI binding - undefined symbol: zhttp_request_test

### ISSUE THREAD

**Issue by davidzanetti** [zeromq/czmq#2075]
> Task :initCMake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/david/tmp/czmq-4.2.0/bindings/jni

> Task :buildNative
Scanning dependencies of target czmqjni
[  3%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zarmour.c.o
[  6%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zcert.c.o
[  9%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zcertstore.c.o
[ 12%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zchunk.c.o
[ 16%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zclock.c.o
[ 19%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zconfig.c.o
[ 22%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zdigest.c.o
[ 25%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zdir.c.o
[ 29%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_ZdirPatch.c.o
[ 32%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zfile.c.o
[ 35%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zframe.c.o
[ 38%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zhash.c.o
[ 41%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zhashx.c.o
[ 45%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Ziflist.c.o
[ 48%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zlist.c.o
[ 51%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zlistx.c.o
[ 54%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zloop.c.o
[ 58%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zmsg.c.o
[ 61%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zpoller.c.o
[ 64%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zproc.c.o
[ 67%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zsock.c.o
[ 70%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zstr.c.o
[ 74%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zsys.c.o
[ 77%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Ztimerset.c.o
[ 80%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Ztrie.c.o
[ 83%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zuuid.c.o
[ 87%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_ZhttpClient.c.o
[ 90%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_ZhttpServer.c.o
[ 93%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_ZhttpServerOptions.c.o
[ 96%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_ZhttpRequest.c.o
[100%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_ZhttpResponse.c.o
Linking C shared library libczmqjni.so
[100%] Built target czmqjni

> Task :test FAILED
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/bin/java: symbol lookup error: /home/david/tmp/czmq-4.2.0/bindings/jni/libczmqjni.so: undefined symbol: zhttp_request_test

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'Gradle Test Executor 3' finished with non-zero exit value 127
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the user guide at https://docs.gradle.org/5.0/userguide/java_testing.html#sec:test_execution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
7 actionable tasks: 4 executed, 3 up-to-date

**Comment by sappo** [comment]
Hi @davidzanetti, 
I can't reproduce this error on my machine. 

What where the steps you took to get to this error?

**Comment by davidzanetti** [comment]
Hi,

 

The build was done from a download of the git master branch.

That was done to simulate my professional offline build environment.

 

I re-try today from a git clone and confirm the build work perfectly.

 

Regards,

 

David

 

De : Kevin Sapper <notifications@github.com> 
Envoyé : Sunday, 19 April 2020 11:09
À : zeromq/czmq <czmq@noreply.github.com>
Cc : davidzanetti <david.zanetti@gmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [zeromq/czmq] Cannot build JNI binding - undefined symbol: zhttp_request_test (#2075)

 

Hi @davidzanetti <https://github.com/davidzanetti> ,
I can't reproduce this error on my machine.

What where the steps you took to get to this error?
