### ISSUE TITLE
CMake build on OS X fails

### ISSUE THREAD

**Issue by pbosetti** [zeromq/czmq#2077]
On Mac OS 10.15.4 building with CMake fails:
```
cmake -Bbuild -H.
make -Cbuild 
```
produces the first error as:
```
[  0%] Building C object CMakeFiles/czmq-static.dir/src/zactor.c.o
...
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Headers/sys/syslog.h:299:9: error: conflicting types for
      'log'
void    log(int, const char *, ...);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Headers/math.h:373:15: note: previous declaration is here
extern double log(double);
```

On the same system, compilation with `configure` works fine.

**Comment by aaronvark** [comment]
I'm running into the same issue. Replacing the include folder:

`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Kernel.framework/Headers`

with 

`/usr/local/include`

Solves the issue in our project. We're still investigating where that include comes from.

**Comment by sphaero** [comment]
Some suggestions (workarounds) here: https://stackoverflow.com/questions/58300397/cmake-build-failed-on-macos-catalina-10-15

**Comment by sphaero** [comment]
Still an issue, will look into once I get my hands on Macs again

**Comment by stvales** [comment]
Cmake works fine for me on macos 10.15.6. Here is a script relying on homebrew to install cmake and autotools, which builds libsodium, libzmq, czmq and zyre. This scripts does no install anything on system but builds libs and installs them in a local sysroot/usr/local folder.
It's easy to adapt the script to install in /usr/local or any other destination. If CMAKE_PREFIX_PATH and DESTDIR are omitted for the cmake and make commands, /usr/local is used by default.

[bootstrap.sh.txt](https://github.com/zeromq/czmq/files/5214153/bootstrap.sh.txt)

**Comment by sphaero** [comment]
@aaronvark do you know if this is still in issue?
