### ISSUE TITLE
enabling ZMQ_DGRAM sockets

### ISSUE THREAD

**Issue by sphaero** [zeromq/czmq#2093]
Testing the ZMQ_DGRAM sockets is giving some trouble which might need some clarification.

This is continued work from #2092 to support UDP sockets in czmq.
I've modified zsock to include the ZMQ_DGRAM socket. This simple test works:

```
    zsock_t* dgramr = zsock_new_dgram ("udp://*:7777");
    zsock_t* dgrams = zsock_new (ZMQ_DGRAM);
    zsock_bind (dgrams, "udp://127.0.0.1:7778" );

    rc = zstr_sendm( dgrams, "127.0.0.1:7777" );
    assert (rc == 0);
    rc = zstr_send (dgrams, "HELLO");
    assert (rc == 0);

    char *dmessage, *addr;
    zmsg_t *dmsg = zmsg_recv( dgramr );
    assert (dmsg);
    addr = zmsg_popstr (dmsg);
    dmessage = zmsg_popstr (dmsg);
    assert (streq(dmessage, "HELLO"));
```
I can't seem to be able to use `zsock_connect`. Why do I need to bind the sending socket? From zmq's jargon you'd need to use `connect`. Then again why would you need to add the destination address as a first frame if you would use `connect`?

Anyway the docs do mention you can only connect a RADIO socket which is not a DGRAM socket. However I only want to work with DGRAM sockets for this test. Any clarification on this?

Btw a multicast works like this:
```
    zsock_t* mdgramr = zsock_new_dgram ("udp://225.25.25.25:7777");
    zsock_t* mdgrams = zsock_new (ZMQ_DGRAM);
    rc = zsock_bind (mdgrams, "udp://239.0.0.1:7777" );
    assert ( rc == 0 ); // only for tcp the port number is returned
    
    rc = zstr_sendm( mdgrams, "225.25.25.25:7777" );
    assert (rc == 0);
    rc = zstr_send (mdgrams, "HELLO");
    assert (rc == 0);
```

**Comment by somdoron** [comment]
For DGRAM you only bind, no need to call connect.

**Comment by somdoron** [comment]
There is no sender or receiver side, you need to bind for both ( and you can do both). There is no connect because you specify the destination on the send call.

**Comment by sphaero** [comment]
Ok, thanks. Just added #2094. I think that's all what is needed for getting ZMQ_DGRAM into czmq?

**Comment by sphaero** [comment]
#2094 was merged, so closing this
