### ISSUE TITLE
zpoller_new() doesn't accept file handles

### ISSUE THREAD

**Issue by faku99** [zeromq/czmq#2095]
Hi everyone

Today, I have been confronted with an issue regarding the `zpoller_new()` method. When I run the following code:

```
static void actor_fn(zsock_t *pipe, void *args) {
    zfile_t *file = zfile_new("dummy", "file");
    assert(zfile_input(file) == 0);

    FILE *handle = zfile_handle(file);
    assert(handle != NULL);

    zpoller_t *poller = zpoller_new(pipe, handle, NULL);
    assert(poller != NULL);
}
```

it fails on the last assertion and `perror` prints `zpoller_new(): Socket operation on non-socket`. However, according to the [documentation](http://czmq.zeromq.org/czmq-master:zpoller), "*each reader can be a zsock_t instance, a zactor_t instance, a libzmq socket (void \*), or a **file handle***".

Note that if I use the `zmq_poll()` method without using CZMQ, everything works fine.

**Comment by somdoron** [comment]
Which version of libzmq? are draft enabled? Which line of code and file causing the assert? and what OS?

**Comment by faku99** [comment]
* libzmq version: `4.1.1`.
* `zmq_has("draft")` returns `1`.
* `uname -a`: `Linux buildroot 4.14.0-xilinx-g7b5b9941b #2 SMP PREEMPT Mon Jun 8 13:01:11 CEST 2020 armv7l GNU/Linux`
* The library doesn't cause the assert, but `zpoller_new()` returns NULL when it shouldn't

**Comment by somdoron** [comment]
Is `ZMQ_HAVE_POLLER` defined?

**Comment by somdoron** [comment]
and which version of czmq?

**Comment by faku99** [comment]
`ZMQ_HAVE_POLLER` is not defined.
The CZMQ version is 4.1.1 and the libzmq version is 4.2.5 (sorry, I got the two things confused)
