### ISSUE TITLE
zcertstore has no API to get the disk state from a custom loader

### ISSUE THREAD

**Issue by santupari** [zeromq/czmq#2113]
Hello everyone,

We encountered 2 different issues listed below w.r.t CURVE authentication which uses zcertstore internally to store the client keys.
1. If there are multiple client certs with same timestamp or one of the cert has timestamp
      a. On client connection request certstore gets refreshed
      b. after that a new client cert is copied or valid cert is overwritten as the previous cert was invalid or corrupted, the certstore does not get refreshed and there after that connection will never be allowed as there is not change w.r.t timestamp, count and current size of the cert dir
2. If an application wants to load its custom disk loader (which loads all the certs on a change), then there is no API available to access the state store in zcertstore struct.

The above issues are observed on libczmq 4.2.0 version.
I have attached test code along with the patch for zcertstore.c and zcertstore.h.

Please let me know for any clarification.

[czmq_certstore_custom_loader.zip](https://github.com/zeromq/czmq/files/5235592/czmq_certstore_custom_loader.zip)

Thanks,
Santosh Bidaralli

**Comment by bluca** [comment]
Please send a pull request with the patches rather than attachments

**Comment by santupari** [comment]
Thank you @bluca. I will send the pull request at the earliest.

**Comment by Yashashree-Jadhav** [comment]
Hi Everyone,

I am seeing the same issue as mentioned in  1st bullet here:

1. If there are multiple client certs with same timestamp or one of the cert has timestamp. On client connection request certstore
     gets refreshed after that a new client cert is copied or valid cert is overwritten as the previous cert was invalid or corrupted, 
    the certstore does not get refreshed and there after that connection will never be allowed as there is not change w.r.t 
    timestamp, count and current size of the cert dir

Before jumping to 4.2.1, I am curious how does the custom disk loader helps fix this issue.
I see in my case the default disk loader in zcertstore (s_disk_loader ) never makes into this if block:
**********************************************************
   if (dir
    && (state->modified != zdir_modified (dir)
    ||  state->count != zdir_count (dir)
    ||  state->cursize != (size_t) zdir_cursize (dir)))
    {
*********************************************************

**Comment by santupari** [comment]
Yashashree,

You can create a custom disk loader that checks the hash of the directory (cert dir) every time a change is detected instead of count and size.

Thanks,
Santosh
