### ISSUE TITLE
zmsg_save() causing fclose() to crash

### ISSUE THREAD

**Issue by jhalter2** [zeromq/czmq#2122]
Hello. Experiencing a debug assertion fail when calling fclose() on the file that had a message written into it. I'm experiencing this same crash with testing with the exact code used in the documentation for zmsg.

msg = zmsg_new();
  assert(msg);
  rc = zmsg_addmem(msg, "Frame0", 6);
  assert(rc == 0);
  rc = zmsg_addmem(msg, "Frame1", 6);
  assert(rc == 0);

  FILE *file = fopen("/zmsg.test", "w");
  assert(file);
  rc = zmsg_save(msg, file);
  assert(rc == 0);
  fclose(file); //<--------- debug assertion fail, crash

Using Microsoft Visual Studio 2017, Windows 10

**Comment by sphaero** [comment]
I'm not using zfile that often but should you be using fclose? Not zfile_close?

See the tests for examples: https://github.com/zeromq/czmq/blob/5222cb1090ca5a889d4db4d0e66f9282d26f29de/src/zfile.c#L694

**Comment by jhalter2** [comment]
I was going off of the czmq zmsg documentation that uses my original code, with fopen() and fclose(). Using the zfile version of the documentation does seem to work.
