### ISSUE TITLE
When using gdb, zsock_bind fails with "ipc" sockets but not "tcp"

### ISSUE THREAD

**Issue by talkhasib** [zeromq/czmq#2124]
Binding to an "ipc" uri works fine outside gdb. But when I try the same application with gdb, the socket fails to bind with rc = -1
I tried switching the uri to "tcp" and it works both inside and outside of gdb.

I am using 
- Operating System: Debian GNU/Linux 9 (stretch)
- Kernel: Linux 4.9.0-9-amd64
- libczmq-dev version: (4.0.2-7)

**Comment by sappo** [comment]
Hi @talkhasib,
could you provide a code sample and the gdb call you used.
Thanks!

**Comment by talkhasib** [comment]
Turns out to be related to permissions to root folder where I was placing the ipc socket files. gdb does not seem to have write access to root folder. When I changed the location of the files to /tmp things work as expected.

**Comment by talkhasib** [comment]
Thanks @sappo for your help
