### ISSUE TITLE
Building libzmq and czmq in the same CMake tree

### ISSUE THREAD

**Issue by FatihBAKIR** [zeromq/czmq#2126]
Hello,

Putting both `libzmq` and `czmq` in the same CMake tree fails due to both of them adding the `cmake-format` target.

We have them part of the same tree as we put all our dependencies in a single repo and get a static build for multiple OS and architectures, and have enjoyed the simplicity it provides.

Would you be interested in making this use case possible?

**Comment by sphaero** [comment]
Can you be more specific? I have used the zeromq projects as cmake subdirectories which is the way to do this but I'm not sure if this is what you mean.

**Comment by FatihBAKIR** [comment]
Sorry for the lack of clarity. I'm trying to do this:

```
add_subdirectory(libzmq)
add_subdirectory(czmq)
```

Where the libzmq and czmq dirs are pulled in tree.

However, this makes both `libzmq` and `czmq` part of the same build, and since they now share a target name space, both of them adding the `clang-format` target breaks CMake.

It's possible to detect from a cmake file whether it's part of a larger build (https://stackoverflow.com/a/42716588). Disabling this target (and other developer related targets) would allow building both libzmq and czmq in the same build. There might be more hurdles, but I'd be willing to submit pull requests implementing them if it's something the project would accept.

**Comment by sphaero** [comment]
I've not subdir-ed libzmq only czmq

```
add_subdirectory("ext/czmq" EXCLUDE_FROM_ALL)
```
see: https://github.com/hku-ect/gazebosc/blob/b47a399f3313815d60db59a07b1f8dc519cf7118/CMakeLists.txt#L44

**Comment by FatihBAKIR** [comment]
I see, but that would then depend on an external libzmq, right?

Since we are cross compiling for a few platforms, we'd rather have everything in one tree.

**Comment by sphaero** [comment]
Yes, indeed. For czmq we did a fix in the cmake config in zproject. see: https://github.com/zeromq/zproject/pull/1238/files

We probably need to do that for libzmq as well.

**Comment by sphaero** [comment]
Have you been able to fix this?

**Comment by FatihBAKIR** [comment]
Sadly, no. 

I'm not fully experienced with the zeromq's build system and I'm not sure what zproject is and how I can reflect that change to my libzmq and czmq copies.

I don't really have a fix without making big changes to the dependency resolution. For cross compiling I have to manually build both of them and put them in a sysroot, which was made difficult by the manual use of pkg-config, since for instance for a cross arm build, pkg-config still manages to find the host x86 zeromq libraries and break the build. 

To work around this I had to remove the Findzeromq.cmake stuff and let CMake do its thing with the ZeroMQ-config.cmake files it generated. However, this works only when the installed libzmq was built with cmake.

Not to mention I have to disable pretty much every optional dependency since they too are resolved to host libraries.

While I can easily fix the same-tree problems, I'm not quite sure how that would effect the regular, install based workflow. However, I think the current cmake scripts should be changed to first use modern cmake dependency resolution stuff (with imported targets etc.), since you already generate the necessary *-config.cmake files, and second, it should detect it's being built as a subdirectory, and skip the dependency resolution stuff completely and let the main project supply the dependencies.

**Comment by bluca** [comment]
> pkg-config still manages to find the host x86 zeromq libraries and break the build.

Sounds like your cross compilation toolchain is not setup correctly. You can remove all the cmake stuff, and rely entirely on pkg-config - as long as it's configure correctly to look in the right place with the right options, it will just work.

**Comment by FatihBAKIR** [comment]
That's possible, though I've set the correct target and CMAKE_SYSROOT in the toolchain file. Even so, that was a workaround outside the workflow I'm interested in. I simply would like to be able to `add_subdirectory` both the libraries and be done with it.

**Comment by bluca** [comment]
PKG_CONFIG_PATH, PKG_CONFIG_SYSROOT_DIR and --define-prefix are also needed at a minimum. Regarding cmake, feel free to send a pull request to improve things - as long as backward compatibility is retained, there's no problem

**Comment by sphaero** [comment]
I agree the cmake find scripts are not helping with add_subdirectory. I was looking into this myself as well. I had a really [ugly workarond](https://github.com/hku-ect/gazebosc/blob/9fe2921409e7ce25f01872aa0d03b4656d082cb7/CMakeLists.txt#L51). Any suggestions what would this 'modern cmake' approach be like? I'm happy to help getting this resolved

**Comment by sphaero** [comment]
Here's another pointer for modernizing cmake. I think needs to be done for libzmq. It's getting better with czmq et al.

https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1

**Comment by ClausKlein** [comment]
@sphaero @FatihBAKIR please try my draft: "use CPM.cmake" #2200
