### ISSUE TITLE
Error: reference to 'byte' is ambiguous

### ISSUE THREAD

**Issue by linuxpham** [zeromq/czmq#2131]
There is an error when using `czmq` in the c++ 17 project.
I must change : `byte` -> `unsigned char` (manually)
Is there any way automatically?

**Comment by sphaero** [comment]
I'm not sure what you mean. Is this still a valid issue?

**Comment by jack9603301** [comment]
I also encountered this problem

**Comment by sphaero** [comment]
Have you found a fix or workaround?

**Comment by sc0w** [comment]
The behavior of bot closing issues has no sense
