### ISSUE TITLE
Register Callback Method to Monitor Connection Status possible?

### ISSUE THREAD

**Issue by nilsmelchert** [zeromq/czmq#2143]
Hello,
I was wondering, if there is a utility function for registering callback methods, whenever a connect (or disconnect) event happens.
Assuming we have a client-server REQ-REP communication.

**Comment by sphaero** [comment]
you might want to take a loot at: https://github.com/zeromq/czmq/blob/master/src/zmonitor.c

**Comment by nilsmelchert** [comment]
Thank you
