### ISSUE TITLE
zhashx_dup() should use previous hashes comparator and key functions?

### ISSUE THREAD

**Issue by chu11** [zeromq/czmq#2144]
Recently used `zhashx_dup()` to copy a hash, leading to an assert in `zhashx_insert()` while in the middle of the copy iteration in `zhashx_dup()`.

Eventually, I determined the issue was that we use an alternate setting of the key hasher, comparator, duplicator, and destructor.  However in `zhashx_dup()` it does not appear to copy those over.  It only copies over the item duplicator/destructor.

```
    zhashx_t *copy = zhashx_new ();
    if (copy) {
        copy->destructor = self->destructor;
        copy->duplicator = self->duplicator;
```

I think it should be using the same hasher/key functions across the board?

**Comment by bluca** [comment]
Can you send a PR to fix it, please?

**Comment by chu11** [comment]
@bluca sure
