### ISSUE TITLE
configure "checking for zmq_init in -lzmq" doesn't work when compiling with with different tools

### ISSUE THREAD

**Issue by crcunningham** [zeromq/czmq#2148]
I'm trying to compile czmq with an Apple iOS toolchain and I've noticed that part of the configure fails around this line (~13500 in configure): 

```
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for zmq_init in -lzmq" >&5
```

It looks like what's happening is that eventually what happens is $ac_try_link, then $ac_link uses a $CC variable which refers to the system compiler rather then one that is specified using the build flags. 

I'm not super familiar so I can't figure out a way to easily fix this. It looks like we just need to have that $CC refer to the toolchain specified by the build flags (environment variables). 

Extra info: 

I've compiled libsodium and libzmq successfully already. When building czmq I'm referring to the zmq I just build using the --with-libzmq=

Here's a copy of the build script: https://gist.github.com/crcunningham/5541b637f8e86d6b1cb367260b96576a

**Comment by crcunningham** [comment]
Here's the output of running the script: https://gist.github.com/crcunningham/953b6baf18f41fe104455dac4a828880

**Comment by crcunningham** [comment]
Interestingly, when I add 

echo $CC
echo $LD

to the `ac_fn_c_try_link()` function the linker looks correct, but the compiler is wrong. 

```
checking for zmq_init in -lzmq...
gcc
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
```

**Comment by crcunningham** [comment]
It looks like I was pretty wrong here. The error that was happening during the link check was actually that c++ was not being linked. I added a link to my build script and things seem to work now: 

```
--- a/zeromq/libczmq.sh
+++ b/zeromq/libczmq.sh
@@ -38,7 +38,7 @@ SDK=$(xcodebuild -showsdks \
     )
 
 IOS_VERSION_MIN=8.0
-OTHER_LDFLAGS="-L${LIBZMQ_DIST}/lib -lzmq"
+OTHER_LDFLAGS="-L${LIBZMQ_DIST}/lib -lc++ -lzmq"
```

**Comment by crcunningham** [comment]
for anyone who eventually gets here when trying to build czmq for ios i placed my scripts here: https://github.com/crcunningham/zeromq_ios_libraries

**Comment by sappo** [comment]
Hi Chris, thanks for your updates and your script. IMO it would make
perfect sense to include the instructions in your build script in the czmq
README.

It would be great if you could update the README and send a PR.

Cheers
//Kevin

Chris Cunningham <notifications@github.com> schrieb am Mi., 6. Jan. 2021,
23:06:

**Comment by crcunningham** [comment]
let me know if this is what you were thinking: https://github.com/zeromq/czmq/pull/2149/files
