### ISSUE TITLE
Unable to lookup a key with value 1073731826

### ISSUE THREAD

**Issue by ashumundra** [zeromq/czmq#2156]
I am trying to use the insert and lookup APIs. 

While I did not get any error with integer key as big as 1073731826 during the insertion process in zhashx_insert(), while looking up through zhashx_lookup () it failed  and returned NULL. 

I was evaluating the maximum value of the key and thought even if it supported a signed integer range, it could support up to 2^30 and that number 1073741824 seems to be bigger than 1073731826. I have no clue now why it is not working.

**Comment by ashumundra** [comment]
Is it an expectation from users to use only a string key to insert in hash? Can someone please guide here ..

**Comment by sphaero** [comment]
please give some code demonstrating the issue

**Comment by ashumundra** [comment]
This issue is not reproducible now. Let me collect some more test data.
