### ISSUE TITLE
czmq 4.2.1 self tests fail on OSX 10.15 and Windows

### ISSUE THREAD

**Issue by langmm** [zeromq/czmq#2161]
In creating a conda release for czmq 4.2.1 I have encountered errors in the self tests on both OSX 10.15 (Catalina) and Windows. The failing tests can be seen [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=273464&view=results); for these builds I am trying to re-render w/ the new release of zeromq 4.3.4. I had already pushed a version with 4.2.1 that I thought was passing, but on closer inspection, the same errors were present even for the older version of zeromq, they had just been masked.

The errors are slightly different for the two OSs, so let me know if you would prefer separate issues.

### Windows

The zpoller test segfaults. This is intermittent (it did not fail during my initial attempt at a conda release of czmq 4.2.1), but is now failing pretty consistently (possibly zeromq 4.3.4 increases the likelihood by putting pressure on a race condition).

### OSX

None of the self tests run. The error is `make: *** [check-verbose] Illegal instruction: 4` so I think this might be due to changes in the OS (maybe XCode, see discussion under https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10). I have also replicated this when using the master versions of libzmq & czmq and compiling with gcc on Github actions (the linked builds use clang). 

I have a Mac w/ a windows dual boot that I will be installing Catalina on and can use to try to debug this better, but that may not happen for a few weeks. I also have a Github Actions workflow that can be used in the meantime if that is helpful.

**Comment by langmm** [comment]
Possibly related to #2155 & #2142

**Comment by skaes** [comment]
This is fixed in https://github.com/zeromq/czmq/pull/2162

**Comment by langmm** [comment]
Thank you, all good now!

**Comment by langmm** [comment]
After some additional tests I see that the zpoller test still segfaults intermittently on windows. Perhaps this is known behavior though?
