### ISSUE TITLE
Version 4.7.1 compiled fail on windows

### ISSUE THREAD

**Issue by jiazhanfeng1989** [zeromq/czmq#2164]
We used zeromq 4.3.2 and cppzmq 4.6.0 on windows and they work fine,
But after upgrading to zeromq v4.3.4, the compilation failed.

win64-vs14-dbg\include\zeromq/zmq.hpp(2588): error C3646: 'fd': unknown override specifier

# Issue description
we used zeromq  4.3.2 and cppzmq 4.6.0 on windows and they workd fine,
But after upgrading to zeromq  v4.3.4, the compilation failed.

win64-vs14-dbg\include\zeromq/zmq.hpp(2588): error C3646: 'fd': unknown override specifier

# Environment
* OS: windows VS2015

old:  woks fine
zeromq  4.3.2
cppzmq 4.6.0

new:  compile fail
cppzmq v4.7.1
zeromq  4.3.4

# What's the expected result?
Compile OK.

**Comment by bluca** [comment]
Wrong repository

**Comment by jiazhanfeng1989** [comment]
Yes, the issue should be cppzmq,  it's my mistake. I will change it to the correct repository.
