### ISSUE TITLE
Documentation for installing czmq to Msys

### ISSUE THREAD

**Issue by CommanderTvis** [zeromq/czmq#2167]

**Comment by CommanderTvis** [comment]
Don't close it, bot

**Comment by sfhacker** [comment]
Any news on this issue?

**Comment by sphaero** [comment]
Well if anybody knows how please tell. I think I've done it long time ago but I hardly use msys anymore...

**Comment by sfhacker** [comment]
Can you post here the error messages you get so we can better assist you?
Cheers.

**Comment by CommanderTvis** [comment]
no
