### ISSUE TITLE
zloop SIGINT

### ISSUE THREAD

**Issue by zhangtaozt3601** [zeromq/czmq#2169]
/*
Send SIGINT to this program, "main exit" can't print.
Reopen zloop_set_verbose line, "main exit" can print.
Why?
*/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <czmq.h>

int timer_cb(zloop_t* loop, int timer_id, void* args)
{
	printf("timer_id=%d\n", timer_id);
	return 0;
}

int main(int argc, char* argv[])
{
	zloop_t* loop = zloop_new();
	int timer_id = zloop_timer(loop, 1000, 0, timer_cb, NULL);
//	zloop_set_verbose(loop, true);
	zloop_start(loop);
	printf("main exit\n");
	zloop_destroy(&loop);
	sleep(10);
	return 0;
}

**Comment by sphaero** [comment]
if you use verbose `zsys_init` will be called. That probably explains the difference.

**Comment by zhangtaozt3601** [comment]
Right, thank you.
