### ISSUE TITLE
1 out of 1 hunk FAILED -- saving rejects to file src/zarmour.c.rej

### ISSUE THREAD

**Issue by dadams1** [zeromq/czmq#2172]
Patch failure while trying to install czmq on Mac 10.15.7

bash-3.2$ brew install czmq --HEAD
==> Downloading https://github.com/zeromq/czmq/commit/ace06a41da51b1196eef411669
Already downloaded: /Users/aadadams1/Library/Caches/Homebrew/downloads/81276a751e3083aa86f47e078f590ba30f5e443e9004d0453ddd33e7bd365598--ace06a41da51b1196eef411669343cdf7e8665e2.patch
==> Downloading https://github.com/zeromq/czmq/commit/0c7cac3be12707225d03888a60
Already downloaded: /Users/aadadams1/Library/Caches/Homebrew/downloads/4a1ac91e4cd12935193c36c268af845d252903d5372e8c224e38e04bebba0209--0c7cac3be12707225d03888a6047e5133d926751.patch
==> Cloning https://github.com/zeromq/czmq.git
Updating /Users/aadadams1/Library/Caches/Homebrew/czmq--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 4364943 Merge pull request #2165 from sphaero/regen
==> Patching
==> Applying ace06a41da51b1196eef411669343cdf7e8665e2.patch
patching file src/zarmour.c
Hunk #1 FAILED at 655.
1 out of 1 hunk FAILED -- saving rejects to file src/zarmour.c.rej

**Comment by bluca** [comment]
Those patches are maintained on the brew repository, please open an issue/pr there https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/czmq.rb

**Comment by dadams1** [comment]
Thanks. Was able to configure/compile/install manually as long as I suppressed document creation (./configure --with-docs=no).
