### ISSUE TITLE
Windows winsock2 does not define htonll methods

### ISSUE THREAD

**Issue by sphaero** [zeromq/czmq#2181]
It might be caused by zmq.h, if you include winsock2.h before zmq.h it is fixed. I think this belongs in a separate issue. I'll fix it by including winsock2 in zosc.c before anything else like it was.

_Originally posted by @sphaero in https://github.com/zeromq/czmq/pull/2180#discussion_r627742812_

**Comment by sfhacker** [comment]
Any news on this issue?

**Comment by sphaero** [comment]
I don't think so. We would need people running into this issue. It was fixed (workaround) in czmq. I think it's quite an edge case.
