### ISSUE TITLE
JNI bindings build are looking for libczmq in the wrong location

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [zeromq/czmq#2212]
```
[ 96%] Building C object CMakeFiles/czmqjni.dir/src/main/c/org_zeromq_czmq_Zosc.c.o
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libzmq.so', needed by 'libczmqjni.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/czmqjni.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Why is it looking in `/usr/lib/x86_64-linux-gnu/libzmq.so`? The library, by default, is installed to `/usr/local/lib/libzmq.so`

**Comment by bluca** [comment]
it looks in the default libdir of the distribution by default, which is /usr/lib/x86_64-linux-gnu/

**Comment by SpaceMonkeyForever** [comment]
strangely, I started a new bash and tried again and it looked at the right place. It builds fine now.
