### ISSUE TITLE
Python bindings: outdated? python: src/zsock_option.inc:4249: zsock_events: Assertion `self' failed. + other issues.

### ISSUE THREAD

**Issue by SpaceMonkeyForever** [zeromq/czmq#2216]
Hi, I'm trying to use Python bindings here because I need CLIENT/SERVER socket types which are not available in the main/popular Python binding `pyzmq`

I can't get it running on Windows at all because of [this](https://stackoverflow.com/questions/71765296/find-libraryc-on-windows-is-broken) but that's a separate issue.

I'm trying to run it on Linux now. I built it using `./ci_build.sh`, which tells me that the python bindings were not configured

![image](https://user-images.githubusercontent.com/22860578/162086034-a66d2893-0341-4474-9eb1-4c5690378532.png)

Yet, I'm able to run:
`python setup.py test`

successfully:
![image](https://user-images.githubusercontent.com/22860578/162086131-dd2a9499-6c0f-4c58-9d1c-7cbbe699b5a3.png)

So I don't know what to make of that.

When I try to use it:

```
In [2]: from czmq import Zsock, Zstr
In [3]: s = Zsock.new_server(b"localhost:3000")
In [4]: s.has_in()

python: src/zsock_option.inc:4249: zsock_events: Assertion `self' failed.
Aborted (core dumped)
```

- Why is ./ci_build.sh printing that Python bindings are not configured yet the tests succeeed?
- Why does Python crash when I try to create and use a socket?

Thank you

**Comment by SpaceMonkeyForever** [comment]
I solved it by building from top level using `--enable-python-binding=yes` and changing my code to `s = Zsock.new_server(b"tcp://127.0.0.1:4002")` (added 'tcp')

**Comment by sphaero** [comment]
which bindings are you using, I guess ctypes?

We really need some work on these bindings. A PR about your fix would be welcomed

**Comment by SpaceMonkeyForever** [comment]
@sphaero This one https://github.com/zeromq/czmq/tree/master/bindings/python

I'm not sure what CFFI is.

I think the PR would be to just change the documentation to explain that it should be built from top level using the flag --enable-python-binding=yes

**Comment by sphaero** [comment]
yes, that's ctypes. The PR is welcome indeed

**Comment by SpaceMonkeyForever** [comment]
@sphaero created PR. I have a new question btw, this time regarding creating a Bind SUB socket :)
