### ISSUE TITLE
No MSYS2 package

### ISSUE THREAD

**Issue by paddor** [zeromq/czmq#2277]
As mentioned in paddor/czmq-ffi-gen#11, an MSYS2 package of CZMQ [does not exist](https://packages.msys2.org/search?t=pkg&q=czmq) yet.

To make Windows users' lives a little easier, someone should create a package. Does anyone have experience with creating MSYS2 packages?

**Comment by gdelazzari** [comment]
I opened a pull request for adding an MSYS2 package here https://github.com/msys2/MINGW-packages/pull/20544

**Comment by paddor** [comment]
> I opened a pull request for adding an MSYS2 package here https://github.com/msys2/MINGW-packages/pull/20544 

Thank you for the help.
