### ISSUE TITLE
zloop: nonstop does not work as intended (EINTR breaks loop)

### ISSUE THREAD

**Issue by oko256** [zeromq/czmq#2284]
If zloop is set as nonstop and a SIGINT signal arrives while the poll is blocking, regardless of the attached signal handler (which indeed will be run) it will still cause the poll to return failure with errno set to EINTR. For proper nonstop functionality, this should be checked and the loop should be continued regardless of EINTR if nonstop mode is enabled (to be in line with the description of nonstop mode in the first place).

**Comment by sphaero** [comment]
If you have access to Windows have you ever experienced random crashes on poll?

**Comment by oko256** [comment]
I have couple applications that run on Windows and use zpoller extensively, but have not experienced random crashes on poll at all. If there's more information about these cases then I can surely try to help debug those.
