### ISSUE TITLE
zstr_send is too dangerous

### ISSUE THREAD

**Issue by hintjens** [zeromq/czmq#370]
Problem: this function is a security risk, as it makes it too easy to pass user-provided data to printf().

Solution: revert to older API style, where zstr_send() sends a string, and zstr_sendf() sends a formatted string. Ditto for zstr_sendm() and zstr_sendfm().

**Comment by superchalupa** [comment]
Why do you guys keep changing the public API like this? This is not the way to run an infrastructure project that you want people to actively use. I have code that currently runs 1.4 and breaks on 3.

You should have added new functions and put a deprecation warning or some such on the "dangerous" functions.

The way you do this makes it very frustrating for your users.

**Comment by hintjens** [comment]
Sorry about the change. However we don't "keep" making such changes. This
was a method that accepted variable arguments and did not indicate that in
its name. The alternative was to add a compiler hint, which would also have
broken code.

In this case we chose to close a potential security vulnerability, rather
than keep backwards compatibility.

You'll see that CZMQ does mark classes and methods as deprecated, when it's
possible to keep the old API pieces safely.

**Comment by superchalupa** [comment]
I have code that must compile/run on both 1.4 and 3.0, what is the recommended way to accomplish this? I was previously using zstr_send.

**Comment by hintjens** [comment]
You can use zstr_sendf () which is supported both in 1.4.1 and 3.0.x

**Comment by superchalupa** [comment]
Ok, thanks.

Those methods are not documented here: (which is where I was getting my docs).
http://api.zeromq.org/czmq1-4:zstr

And, small note, but they are marked as "deprecated" in the zstr.h in 1.4.

**Comment by hintjens** [comment]
Sorry, the website is out of date. I'll update it asap.

**Comment by sunipkm** [comment]
I don't know if I am dumb but the ZMQ documentation often feels incomplete. Such as, most functions (e.g. zstr_send) does not describe its return values at all.
