### ISSUE TITLE
can't build czmq against a statically built libzmq and libsodium.

### ISSUE THREAD

**Issue by benoitc** [zeromq/czmq#396]
I am trying to build a static version of czmq on macosx with a static version of libzmq and libsodium.

I was able to build statically libzmq and libsodium without errors and tried the following to build czmq statically against them.

My first attempt was to run the following configure:

    env CFLAGS="-I$LIBSODIUM_DIR/include -I$LIBZMQ_DIR/include" \
        LDFLAGS="-lstdc++ -L$LIBSODIUM_DIR/lib -L$LIBZMQ_DIR/lib" \
        ./configure --prefix=$CZMQ_DIR \
        --disable-dependency-tracking \
        --enable-static \
        --disable-shared \
        --with-libsodium=$LIBSODIUM_DIR \
        --with-libzmq=$LIBZMQ_DIR \
        --disable-silent-rules

but It fails with a configure error:

     checking for zmq_init in -lzmq... no
     configure: error: cannot link with -lzmq, install libzmq.

So I try to force the build to use statically built libraries:

    env CFLAGS="-I$LIBSODIUM_DIR/include -I$LIBZMQ_DIR/include" \
        LDFLAGS="-lstdc++ -L$LIBSODIUM_DIR/lib -L$LIBZMQ_DIR/lib" \
        LIBS="$LIBSODIUM_DIR/lib/libsodium.a $LIBZMQ_DIR/lib/libzmq.a" \
        ./configure --prefix=$CZMQ_DIR \
        --disable-dependency-tracking \
        --enable-static \
        --disable-shared \
        --with-libsodium=$LIBSODIUM_DIR \
        --with-libzmq=$LIBZMQ_DIR \
        --disable-silent-rules

> notice the add of the `LIBS=".."` line

The configure step succeeded ut then the build fail with the following error:

    ld: warning: ignoring file ./.libs/libczmq.a, file was built for archive which is not the architecture being linked (x86_64): ./.libs/libczmq.a
    Undefined symbols for architecture x86_64:
      "_zauth_test", referenced from:
          _main in czmq_selftest.o
      "_zbeacon_test", referenced from:
          _main in czmq_selftest.o
      "_zcert_test", referenced from:
          _main in czmq_selftest.o
      "_zcertstore_test", referenced from:
          _main in czmq_selftest.o
      "_zchunk_test", referenced from:
          _main in czmq_selftest.o
      "_zclock_test", referenced from:
          _main in czmq_selftest.o
      "_zconfig_test", referenced from:
          _main in czmq_selftest.o
      "_zctx_test", referenced from:
          _main in czmq_selftest.o
      "_zfile_test", referenced from:
          _main in czmq_selftest.o
      "_zframe_test", referenced from:
          _main in czmq_selftest.o
      "_zhash_test", referenced from:
          _main in czmq_selftest.o
      "_zlist_test", referenced from:
          _main in czmq_selftest.o
      "_zloop_test", referenced from:
          _main in czmq_selftest.o
      "_zmsg_test", referenced from:
          _main in czmq_selftest.o
      "_zmutex_test", referenced from:
          _main in czmq_selftest.o
      "_zpoller_test", referenced from:
          _main in czmq_selftest.o
      "_zsocket_test", referenced from:
          _main in czmq_selftest.o
      "_zsockopt_test", referenced from:
          _main in czmq_selftest.o
      "_zstr_test", referenced from:
          _main in czmq_selftest.o
      "_zsys_test", referenced from:
          _main in czmq_selftest.o
      "_zthread_test", referenced from:
          _main in czmq_selftest.o
      "_ztree_test", referenced from:
          _main in czmq_selftest.o
    ld: symbol(s) not found for architecture x86_64

Another error appear in the log:

    *** Warning: Linking the shared library libczmq.la against the
    *** static library /Users/benoitc/work/erlang-czmq/c_src/.libs/libsodium/lib/libsodium.a is not portable!

    *** Warning: Linking the shared library libczmq.la against the
    *** static library /Users/benoitc/work/erlang-czmq/c_src/.libs/libzmq/lib/libzmq.a is not portable!

not sure if it's an error during the buildstep or an error when linking the lib.  If you need more tests let me know.

**Comment by twhittock** [comment]
Should be fixed by PR #929
