### ISSUE TITLE
zdir_test sensitive to current working directory

### ISSUE THREAD

**Issue by scpeters** [zeromq/czmq#527]
The czmq selftest was failing on mac osx in a [homebrew pull request](https://github.com/Homebrew/homebrew/pull/30243) to upgrade to 2.2.0. In testing on my local machine, I found that `zdir_test` is sensitive to the current working directory of the test process. I managed to fix the test in https://github.com/scpeters/homebrew/commit/f1cdcfebd5e7f699db5d1ee3e2eb9d2186620f8f by changing the current working directory before launching the selftest.

I don't know if the test needs to change, but maybe the requirements for the current working directory for selftest could be documented somewhere.

**Comment by bluca** [comment]
Closing as it was fixed by https://github.com/zeromq/czmq/pull/1127
