### ISSUE TITLE
dependencies of sources aren't tracked

### ISSUE THREAD

**Issue by mrvn** [zeromq/czmq#637]
I changed zlist a bit (e.g. removed zlist_pop) and then called make and fixed errors. Eventually everything was build but then failed to link because zlist_pop wasn't defined. After make clean; make I got a whole new set of errors.

Reason for that would be that dependencies between *.c and *.h files aren't tracked so make doesn't know which *.c files need to be recompiled when I change zlist.h. This can be done as a side effect of running gcc (for those using gcc).

**Comment by twhittock** [comment]
commented out plo files means `--disable-dependency-tracking` - possibly via a `config.site` for the prefix having that set as an environment variable.

the tests summary thing is the parallel test runner, which is just how it is with new autotools. You can enable the serial one, somehow, i think.

Anyway, I'm pretty sure this isn't an issue anymore?
