### ISSUE TITLE
Problem: Need an actor-based API for monitoring directories for changes

### ISSUE THREAD

**Issue by jemc** [zeromq/czmq#826]
My applications need a way to monitor file directories in an efficient, cross-platform way.  I suspect that many other applications as well as CZMQ itself would benefit from such a feature.

CZMQ's `zcertstore` wants this feature:
https://github.com/zeromq/czmq/blob/c5f3eebcd6efff77abc95274ae6457fb7b9047fb/src/zcertstore.c#L44-L45

CZMQ's `zdir` would be able to have an API that integrates with such a feature.

Drops' `drops_agent` wants this feature:
https://github.com/edgenet/drops/blob/master/src/drops_agent.c#L50-L52

**Suggested solution:** Create a new zactor-based class ([like zbeacon](https://github.com/zeromq/czmq/blob/master/include/zbeacon.h)) that uses [inotify on unix](http://man7.org/linux/man-pages/man7/inotify.7.html) and [FindFirstChangeNotification on windows](http://msdn.microsoft.com/en-us/library/aa364417%28VS.85%29.aspx) to poll for changes in zero or more recursive directories.  It would use its zactor-pipe for control messages and use a PUB socket for change notifications.  This way, multiple actors in an application could be listening for changes while prefix filtering to hear changes for only the directories they care about.  The change messages published by the zactor would be normalized to be platform-agnostic.

I'd like this to become a part of czmq, but if its deemed too experimental to go in czmq right now, it can be developed in the zlabs.  Either way, I'll certainly develop and test it locally and make sure it is at least fairly stable before trying to get a patch merged.

**Comment by twhittock** [comment]
Sorry I'm pretty sure this isn't really closed by that PR - just the first step on the way.
