### ISSUE TITLE
msvc 2013 and stdint.h

### ISSUE THREAD

**Issue by Mikhael-Danilov** [zeromq/czmq#870]
When compiling with msvc 2013:
**zmq.h** includes **stdint.h**
but at same time **czmq_prelude.h** do
```
    typedef __int8 int8_t;
    typedef __int16 int16_t;
    typedef __int32 int32_t;
    typedef __int64 int64_t;
    typedef unsigned __int8 uint8_t;    
    typedef unsigned __int16 uint16_t;
    typedef unsigned __int32 uint32_t;
    typedef unsigned __int64 uint64_t;
```
Which lead to  type redefinition errors later

**Comment by Mikhael-Danilov** [comment]
This time type conflict appear early:
When building libzmq definitions in **zmq.h** conflicts with **stdint.h** included by **stdint.hpp** which in turn included by many implementation files

**Comment by Mikhael-Danilov** [comment]
Maybe just remove fixed size integer typedefs from **czmq_prelude.h** and move **zmq.h** include to begin of **czmq_prelude.h** ?

**Comment by hintjens** [comment]
Ah, I see zmq,h is defined very late in czmq.h. That's an error, it should
indeed go at the start. I'll make that change. Here:
https://github.com/zeromq/czmq/pull/878

Still, CZMQ has to also do the work for older versions of libzmq that don't
do it properly. I defined a macro in zmq.h that controls
this: ZMQ_DEFINED_STDINT.

**Comment by jemc** [comment]
@mikhael-danilov
I merged the PR.  Please check that this fixed it.
