### ISSUE TITLE
"Unknow UNIX TYPE" in zuuid on OSX (Travis)

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#876]
```
src/zuuid.c:66:9: error: "Unknow UNIX TYPE"
```

https://travis-ci.org/libbitcoin/libbitcoin-server/jobs/45837697#L1946

**Comment by Predator01** [comment]
I have a similar error in Solaris 11 SPARC 

```
  CC     src/src_libczmq_la-zuuid.lo
src/zuuid.c: In function \u2018zuuid_new\u2019:
src/zuuid.c:84:5: error: #error "Unknow UNIX TYPE"
 #   error "Unknow UNIX TYPE"
     ^
gmake[1]: *** [src/src_libczmq_la-zuuid.lo] Error 1
```

Fixed the error adding: `|| defined(__UTYPE_SUNOS)|| defined(__UTYPE_SUNSOLARIS) `

v 3.0.3, and i think it must be "unknown".

**Comment by bluca** [comment]
Could you please send a PR to fix it?
