### ISSUE TITLE
zmsg_addint/popint

### ISSUE THREAD

**Issue by acornejo** [zeromq/czmq#882]
There is zmsg_addstr/zmsg_popstr but no zmsg_addint/zmsg_popint.

I would think serializing integers in messages would be pretty common,
is there a reason for this omission?

I do realize that if one plans to serialize lots of integers in a
message, then for the sake of space efficiency storing them in separate
frames is not the best of ideas. However, there are plenty of cases
where one is only serializing one or two integers, and having them in
separate frames is not really a performance hit (plus, it is very
convenient when prototyping a protocol and we all know early
optimization is the root of all evil).

Implementing my own zmsg_addint and zmsg_popint was easy enough, but in
the spirit of having a more complete and uniform API I thought of
creating a pull-request; but I wanted to test the water first.

Personally I've only needed to serialize garden-variety integers (i.e. 4
byte integers), but perhaps it would be useful to include all versions.
Something like:

    zmsg_addint8
    zmsg_addint16
    zmsg_addint32
    zmsg_addint64

with the respective

    zmsg_popint8
    zmsg_popint16
    zmsg_popint32
    zmsg_popint64

The implementations are pretty straightforward, but do save quite a bit
of typing, plus not everyone might remember to deal with endianness
properly (however I agree that these days that might not be such a big
of an issue with the x86/arm ubiquity, but still...)

Thoughts?

**Comment by hintjens** [comment]
We had such methods for a while. What turns out to be more useful is the
zsock_send/bsend methods.

**Comment by acornejo** [comment]
Got it. Will learn this "picture" format and start using it instead. Closing this issue.
