### ISSUE TITLE
czmq_selftest -v crash on windows

### ISSUE THREAD

**Issue by Mikhael-Danilov** [zeromq/czmq#891]
Crash in zsys_test ( gethostname called before WSAStartup )

Calling WSAStartup before doing tests seems to fix problem

**Comment by madebr** [comment]
On current Windows CI, the following warning appears (not visible in log)

assertion failed: Succesful WSASTARTUP not yet performed (C:\projects\libzmq\src\signaler.cpp:191

**Comment by bluca** [comment]
Closing as this was fixed by https://github.com/zeromq/czmq/pull/1131
