### ISSUE TITLE
actor and $TERM string

### ISSUE THREAD

**Issue by acornejo** [zeromq/czmq#892]
When using zactor, it is expected that the actor (aka thread) handles a special message that contains as the first frame a string with the string "$TERM" and terminates the actor (aka destroys the thread).

To do this in a clean way, then every message sent to the actor must always have its first frame be a string (which is different from "$TERM"). This is not ideal, especially since it is faster (and sometimes also more convenient) to send and process binary messages between threads (for example, I am sending a zactor_message_t struct which identifies the message type in the first byte).

It is possible to work around this and send binary messages, but it requires some ugly hacks to work around the possibility of receiving the special "$TERM" message. Perhaps a cleaner solution would be to use a TERM signal (maybe -1) instead of a "$TERM" message? I am open to ideas on other ways to handle this, since the current API (while not broken) seems like it could be improved.

**Comment by hintjens** [comment]
The command API is meant to be easy to debug and performance is not
considered to be a requirement. In cases where we do a lot of traffic we
create a second pipe for data, which works with binary messages and has any
shape the application needs. You can see examples of this in Zyre and in
Malamute.

In any case you need to separate synchronous and asynchronous traffic, the
two typically have different profiles for performance and for complexity.
See the "Cheap and Nasty" discussion in the Guide.

-Pieter

**Comment by acornejo** [comment]
Thanks Pieter,

I do agree with the premise that it is much better to have clean and easy to read code than it is to have efficient code.

That being said, I don't see why you feel sending signals is more convoluted (or cheaper and nastier) than strings.

I already use multiple sockets, but only the default pair socket to send and receive synchronous messages to the thread (including the $TERM message). I'll take a look at zyre for ideas, closing this issue for now.

PS: I see you mentioned the command API, is there any API besides the $TERM message? This is part of the reason I disliked this solution, since it forces you to use strings even though you only need one single command.

**Comment by hintjens** [comment]
We've learned, from experience, that it's nice to have a text based command
API for actors.

There is also a signal method (zsock_signal/zsock_wait) which we use for
some cases. However the actor shutdown needs an explicit request and reply
so signals are not appropriate.

As for efficiency, it simply isn't a relevant measure unless you are doing
things often. It's not a tradeoff. There is zero performance cost to using
strings in a command API. If you need performance you cannot use this
socket with its handshaking, you have to make a separate data socket and
work asynchronously.
