### ISSUE TITLE
zpoller czmq_selftest fail on CZMQ master

### ISSUE THREAD

**Issue by HAlakeshwar** [zeromq/czmq#899]
I have cloned the CZMQ master and have built the solution using visual studio 2012. The CMZQ_tests fail at zsock and the issue is reported #898 .After Commenting the test for zsock, the zpoller test fails.

 * zpoller: Assertion failed: zpoller_wait (poller, 500) == &fd, file ..\..\..\..\src\zpoller.c, line 276

the dump file for this issue can be found at https://files.zenhub.io/54b7d289a249c8781446d0d3

This issue is linked to #893 (comment)

Thanks for looking at it.

**Comment by pijyoi** [comment]
Try changing the following line in zpoller_test():
int fd = zsock_fd (bowl);
to
SOCKET fd = zsock_fd (bowl);

A similar change could be made to zsock_test() regarding #898

**Comment by HAlakeshwar** [comment]
I made the change you requested and the tests pass. 
Thanks
