### ISSUE TITLE
Compiling project that uses stdint.h with czmq_main

### ISSUE THREAD

**Issue by HAlakeshwar** [zeromq/czmq#901]
I have a project that uses boost::uuids to generate a uuid and czmq for transport. The compilation fails with message.
include\czmq_prelude.h(446): error C2371: 'int8_t' : redefinition; different basic types

I figure that this is due to both stdint.h and czmq_prelude defining int8_t, int16_t, int32_t, int64_t, uint8_t, uint16_t, uint32_t, uint64_t. 
I over came this issue by adding 
&& !defined (_STDINT) to czmq_prelude.h 

The czmq_tests pass with the change in place. However, I have only run the tests targeting a VS2012 environment. Can you please validate this change. 

Thanks, 
Harsha

**Comment by dkrikun** [comment]
Same problem with Visual Studio 2013

**Comment by sappo** [comment]
@HAlakeshwar just open a pull request and we'll see what our automated travis tests will tell ;)

**Comment by mikofski** [comment]
I'm trying to build czmq with precompiled [zeromq 4.0.4 v120](http://zeromq.org/distro:microsoft-windows) and [libsodium-1.0.3 v120](https://download.libsodium.org/libsodium/releases/) libraries, but I get the same errors for 42 czmq source files.

**Comment by hintjens** [comment]
There's a patch you can apply to 4.0.x to make this work, presumably:

 /*  Define integer types needed for event interface
   */
+#define ZMQ_DEFINED_STDINT 1
 #if defined ZMQ_HAVE_SOLARIS || defined ZMQ_HAVE_OPENVMS
 #   include <inttypes.h>
-#elif defined _MSC_VER && _MSC_VER < 1600
-#   ifndef int32_t
-typedef __int32 int32_t;
-#   endif
-#   ifndef uint16_t
-typedef unsigned __int16 uint16_t;
-#   endif
-#   ifndef uint8_t
-typedef unsigned __int8 uint8_t;
-#   endif
 #else
 #   include <stdint.h>
 #endif

However I'd recommend you use the 4.1 stable release.

**Comment by mikofski** [comment]
Thanks, that's exactly what I did, but through the visual studio properties c/c++ precompiler setting. However, still could not build iruby gem :(

Also, I got test failures with both DynRelease and DynDebug.

Thanks again!

**Comment by bluca** [comment]
Closing as it was fixed in libzmq
