### ISSUE TITLE
zsys_hostname crashes

### ISSUE THREAD

**Issue by miska** [zeromq/czmq#907]
If you have network unresolvable hostname, zsys_hostname crashes. Sometimes, you like to keep your hostname static especially when you are traveling with notebook around. Apart from crashing, your hostname might not be network resolvable and might be just pointed to the localhost. So I would say that zsys_hostname code is quite unreliable even if it is not crashing unless you are in controlled well setup environment. I think different approach might is needed, just don't see any easy and portable way to do it...

**Comment by hintjens** [comment]
Could you provide the line number for the crash, or a stack backtrace?
Thanks.
