### ISSUE TITLE
Problem: --disable-shared builds broken.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#927]
The zproject integration has changed a couple of build behaviors.

I'm not sure if the static (`--disable-shared`) test builds previously worked, because they weren't built by `make`: https://travis-ci.org/libbitcoin/libbitcoin-client/jobs/50451196#L1371

But presently it appears that test builds cannot be disabled. At the same time there is a linking failure for tests: https://travis-ci.org/libbitcoin/libbitcoin-client/jobs/50570598

Also the `--with-makecert` option is no longer available.

**Comment by hintjens** [comment]
Yes, we knew the --with-makecert option was going to suffer. One solution
is to have such an option for ever "main" defined in the project file. I'll
take a look at doing that now.

**Comment by evoskuil** [comment]
Thanks. WRT the shared builds, I should add that the linking failure [occurs](https://travis-ci.org/libbitcoin/libbitcoin-client/builds/50570593) on OSX (Clang) and Linux (GCC & Clang).

**Comment by hintjens** [comment]
I've no clue how to fix the share builds... have gotten the makecert option
working again, will push that.

**Comment by evoskuil** [comment]
The `--without-makecert` option is now working, and using the `-without-test_zgossip` option the static link break in that test build can be avoided.

**Comment by twhittock** [comment]
fwiw, i checked out a pre-zproject version of czmq and configured with --disable-shared in libzmq and czmq, and it failed in exactly the same way on mac. I don't think this is a zproject regression. My guess would be that libzmq maybe used to link in the c++ runtime into its static lib at some point, since the link errors are all stdlib/c++ support things.

**Comment by evoskuil** [comment]
@twhittock That makes sense as we weren't building the tests and only encountered the issue when the they started building.
