### ISSUE TITLE
czmq fails when building statically if zeromq has pgm support

### ISSUE THREAD

**Issue by vriera** [zeromq/czmq#944]
It fails because the configure script does a compile check which doesn't include the libraries for openpgm, so the calls to openpgm functions cause 'undefined reference' errors.

- This is the failure of the configure script:

`checking for zmq_init in -lzmq... no`
`configure: error: cannot link with -lzmq, install libzmq.`
`make: *** [/br/output/build/czmq-v3.0.0/.stamp_configured] Error 1`

- This is the content of config.log:

`[...]`
`configure:13201: checking for zmq_init in -lzmq`
`configure:13226: /br/output/host/usr/bin/mipsel-linux-gcc -std=gnu99 -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -Os  -static -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include    -static -L/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib -lzmq   conftest.c -lzmq  -lpthread -lstdc++ -lm >&5`
`/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib/libzmq.a(libzmq_la-ipc_listener.o): In function 'zmq::ipc_listener_t::set_address(char const*)': `
`ipc_listener.cpp:(.text+0x59c): warning: the use of OBSOLESCENT 'tempnam' is discouraged, use 'mkstemp'`
`/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib/libzmq.a(libzmq_la-zmq.o): In function 'zmq_ctx_new':`
`zmq.cpp:(.text+0x134): undefined reference to 'pgm_init'`
`zmq.cpp:(.text+0x14c): undefined reference to 'pgm_init'`
`zmq.cpp:(.text+0x1d0): undefined reference to 'pgm_error_free'`
`zmq.cpp:(.text+0x1d4): undefined reference to 'pgm_error_free'`
`[...]`

- These are the 'Libs' for openpgm:

`$ grep Libs output/staging/usr/lib/pkgconfig/openpgm-5.1.pc`
`Libs: -L${libdir} -lpgm -lpthread -lm`

- The compilation works after adding those libs to the command we have seen in config.log:

`/br/output/host/usr/bin/mipsel-linux-gcc -std=gnu99 -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64   -Os  -static -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/include -static -L/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib -lzmq conftest.c -lzmq -lpthread -lstdc++ -lm -lpgm -pthread -lm`
`/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib/libzmq.a(libzmq_la-ipc_listener.o): In function 'zmq::ipc_listener_t::set_address(char const*)':`
`ipc_listener.cpp:(.text+0x59c): warning: the use of OBSOLESCENT 'tempnam' is discouraged, use 'mkstemp'`
`/br/output/host/usr/mipsel-buildroot-linux-uclibc/sysroot/usr/lib/libpgm.a(libpgm_noinst_la-getnodeaddr.o): In function 'pgm_getnodeaddr':`
`getnodeaddr.c:(.text+0x37c): warning: gethostbyname is obsolescent, use getnameinfo() instead.`

`$ file conftest`
`conftest: ELF 32-bit LSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, with unknown capability 0xf41 = 0x756e6700, with unknown capability 0x70100 = 0x3040000, not stripped`

- Here is the full build log if you need to look at it:

http://autobuild.buildroot.net/results/dca/dca03ab0a9d63b0de72bdd80564166d85cdec0ca/build-end.log

**Comment by twhittock** [comment]
Works for me on Mac. I wonder if maybe not everything was configured with --disable-shared?

**Comment by vriera** [comment]
Fixed by https://github.com/zeromq/czmq/commit/313714f8b73c23d68b1216bc2df3d0ccc6ab1ffd
