### ISSUE TITLE
zmsg_load API definition cannot be complete

### ISSUE THREAD

**Issue by twhittock** [zeromq/czmq#949]
zmsg_load looks like a 'class member' of zmsg, but can also be a constructor if passed a NULL 1st arg.

This causes issues with definining it using the class API - is the return value 'fresh' or not? It depends on whether the first arg is null (therefore fresh) or a valid zmsg (therefore a reference to the incoming parameter)

It'd maybe make more sense to split it into 2 functions - a new_from_file (or something) and a read to append messages to the existing zmsg. One other thing to note about this method - it silently destroys the input zmsg if there are no frames in the message after loading the file, potentially leaving client code with an invalid reference, if it was passed from above.

**Comment by jemc** [comment]
+1 For having an API where the "freshness" of a return value is statically known.

**Comment by hintjens** [comment]
I'd like to deprecate this method entirely, along with zmsg_save.

**Comment by twhittock** [comment]
OK, should it be deprecated now? What would it be deprecated in favor of?

**Comment by hintjens** [comment]
None of our projects use it. The load/save methods are dubious. The whole
zmsg class is dubious, in fact, and I'd like to start moving CZMQ towards a
single-part model, over time.

**Comment by jemc** [comment]
While we're on the subject, having a way to mark a method as deprecated in the API model might be nice, so that various consumers of the model could respond appropriately, even if its as simple as appending boilerplate deprecation text to the method description.  I may work on this a little later in the week if no one else does.

**Comment by hintjens** [comment]
I'd like to be able to mark every method and global in the API as draft,
stable, or legacy. We don't have raw or retired APIs, I think (raw means no
implementations, retired means no longer implemented).
