### ISSUE TITLE
Wrong CRT in msvc-10.0 build

### ISSUE THREAD

**Issue by dkrikun** [zeromq/czmq#954]
Just spotted out that the `Runtime Library` setting is set to multi-threaded *debug* dll, guess its a bug?

**Comment by hintjens** [comment]
It's generated from zeromq/zproject, so that's the place to check.

**Comment by evoskuil** [comment]
It would be a bug if you don't have a debug build selected and if you haven't explicitly selected its use.

**Comment by evoskuil** [comment]
I don't see a problem.

**Comment by dkrikun** [comment]
https://github.com/zeromq/czmq/blob/master/builds/msvc/properties/ReleaseDEXE.props

This shows debug runtime.

**Comment by evoskuil** [comment]
Yes, that's wrong. Has been for a long time, not the fault of zproject.

**Comment by jemc** [comment]
Closed by #955
