### ISSUE TITLE
x64 warnings in Visual Studio build

### ISSUE THREAD

**Issue by dkrikun** [zeromq/czmq#978]
There are various x64-related warnings (int vs size_t conversions etc.) in the Visual Studio builds. Are those safe?

**Comment by evoskuil** [comment]
No, I don't think you could consider them all safe. For example:
```c
s_z85_decode (const char *data, size_t *size)
{
    ...
    int length = strlen (data);
```
will clearly overflow `length` is `size` is greater than `2³¹-1`. This is not limited to VC builds, it's just that the default warning levels are more strict. I fixed up most of the 32 bit build warnings, but wasn't familiar enough with the code to fix the larger number of warnings in the 64 bit builds. As a result the warnings remain to serve their intended purpose (to warn people about the problem).

**Comment by evoskuil** [comment]
#993 resolves all warnings and fixes the related safety issues.
