### ISSUE TITLE
Meaning of '@'/'>' swapped in documentation

### ISSUE THREAD

**Issue by psequeirag** [zeromq/czmq#979]
I'm noticing that the zsock documentation, in the comment for the smart constructors, states:

> In all of these, the endpoint is NULL, or starts with '@' (connect) or '>' (bind).

But the comments on zsock_attach later say it's the other way around, and it turns out the smart constructors use zsock_attach underneath. So, the comment on the smart constructors should be corrected to be consistent with that of zsock_attach.

**Comment by psequeirag** [comment]
I just realized it's already fixed in master. Closing the issue, then.

**Comment by hintjens** [comment]
It was fixed in master yet still wrong in README.md. I've fixed that now
and pushed the patch. Thanks.
