### ISSUE TITLE
ZBeacon empty filter

### ISSUE THREAD

**Issue by sphaero** [zeromq/czmq#985]
If no filter is set for zbeacon I'd imagine all packets get through, right?
However when I look at the code at https://github.com/zeromq/czmq/blob/master/src/zbeacon.c#L238
the is_valid boolean will remain false so no frame will be sent to the API. The is_valid boolean can only become true if a self->filter is not NULL.

Am I overlooking something?

**Comment by hintjens** [comment]
I think we used the same semantics as in sub sockets. No filter means read
nothing.

**Comment by sphaero** [comment]
check :)
