### ISSUE TITLE
Problem: Unicode paths, etc. not supported in Windows.

### ISSUE THREAD

**Issue by evoskuil** [zeromq/czmq#994]
This is a pervasive problem. For example:

``` c
int
zsys_file_delete (const char *filename)
{
    assert (filename);
#if (defined (__WINDOWS__))
    return DeleteFileA (filename)? 0: -1;
#else
    return unlink (filename);
#endif
}
```

In this example (and all others) a non-ASCII path will only be properly interpreted if all of the characters in the path are members of the current thread's ANSI code page. This may or may not be the case, but in any case there is no way to support characters that span multiple code pages or that don't exist in any.

In most Windows APIs the only way to parameterize the call with Unicode input is to pass `wchar_t` (wide) parameters. For example:

``` c
int
zsys_file_delete (const char *filename)
{
    assert (filename);
#if (defined (__WINDOWS__))
    /* insert code to convert filename to wide_filename here */
    return DeleteFileW (wide_filename)? 0: -1;
#else
    return unlink (filename);
#endif
}
```

However the conversion from `char` to `wchar_t` requires code page mapping. The only solution is to carry the Unicode text throughout the entire code path. Traditionally this has been done in in VC projects by using `wchar_t` everywhere. That of course results in a pervasive conditional string/char.

Code like this has the same problem in reverse (mbcs is ANSI, not Unicode or ASCII):

``` c
    ...
    PWCHAR friendlyName = cur_address->FriendlyName;
    size_t asciiSize = wcstombs (0, friendlyName, 0) + 1;
    char *asciiFriendlyName = (char *) zmalloc (asciiSize);
    wcstombs (asciiFriendlyName, friendlyName, asciiSize);
```

The better approach is to use [utf8 everywhere](http://utf8everywhere.org). This works well and is not hard or disruptive. I've recently implemented the technique across all libbitcoin repos, including two console applications, with good results. It would take some time, and probably be best to start by providing the tools in `libzmq`.

I've hit this issue myself in working with `zcert` paths. That can probably be mitigated by providing a round-trip stream alternative, but it would be best for ZMQ to resolve this universally. I'm interested to hear thoughts on the idea.

**Comment by hintjens** [comment]
I'm absolutely in favor of banning UTF16 and using UTF8 everywhere.

**Comment by evoskuil** [comment]
As a general rule I would wrap such calls with unpublished utility functions to hide the Unicode conversions. These would use published UTF8<->UTF16 conversion utilities that need only be exposed for Windows, built on the native conversion APIs.

In libzmq the issue appears to be limited to dealing with addresses and host names. The parsing code is fine, but any API calls such as in `winsock` that deal with addresses would need to be made conditionally.

A compatibility hit occurs where someone is using the current ANSI code page implementation in non-ASCII environments (it doesn't work across code pages, but it works within a localized context). Callers will need to pass UTF-8 and expect it in results, which is uncommon in Windows (although I expect this to evolve over time). This is of course a no-op if the text is limited to ASCII.

The conversion utilities would allow them caller to easily translate between UTF8 `char` and UTF16 `wchar_t`. But if they were to maintain an ANSI product they would have to translate to/from MBCS as well (typically via UTF16). Just want to point this out, because there is a consequence to changing the interpretation of `char` from ANSI to UTF8.

**Comment by evoskuil** [comment]
I don't want to cause anyone to have to choose between rewriting their app or having it break, so I propose that the wrapper functions switch between UTF8 and ANSI based on build configuration.

This would be a single symbol applicable only to Windows builds (MSVC and MinGW, since it pertains to API calls). The additional effort would be minimal, since the ANSI calls are already in place. The additional work is in converting between UTF8 and UTF16 to implement new Unicode API calls. There would be no additional disruption outside of the unpublished wrappers. Calling convention would remains as-is unless the new symbol was defined, at which point strings would need to be interpreted as UTF8.

I considered relying on the `_UNICODE` or `_MBCS` symbols, but it's preferred to always define `_UNICODE` so that casual use of an API won't accidentally compile as ANSI in a UTF8 environment. We have done this for some time. And the combination of `_MBCS` and `_UNICODE` is not recommended (it's ambiguous and behavior is undefined). So I recommend a new symbol to augment the `_UNICODE` guard when on intends to pass MBCS chars to libzmq/czmq. I think the default should be to *not* define the symbol. This would give preference to UTF8 so that the ANSI behavior could be more easily obsoleted (I would consider it already deprecated). So something like `ZMQ_WINDOWS_MBCS`.
